fileVersion: 1
id: 542c2f91-a181-4150-a401-9d0d2a01e1a8
name: ODS_QBYTE_SS_CLIENT_CONFIGURATION
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f1791090-8b75-41c3-9281-fbb3517efcc4
          stepCounter: 542c2f91-a181-4150-a401-9d0d2a01e1a8
        config: {}
        dataType: NUMBER(3)
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: CLIENT_ID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: f822b10e-ec37-4c8f-bb3c-c9e9bd2881d1
                stepCounter: c3c529f9-4984-4d78-96ae-324cf718a150
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: fcb1a5e3-f6e7-42b7-85b9-803d4d3e98f8
          stepCounter: 542c2f91-a181-4150-a401-9d0d2a01e1a8
        config: {}
        dataType: VARCHAR(30)
        defaultValue: ""
        description: Identifier to determine the client.
        isBusinessKey: true
        name: SECTION_NM
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 58fa5699-2b64-40a3-98b3-7f1d1e9132af
                stepCounter: c3c529f9-4984-4d78-96ae-324cf718a150
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 76c1bdce-a8f6-47ff-8a6c-34dda2bc1e8f
          stepCounter: 542c2f91-a181-4150-a401-9d0d2a01e1a8
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: The configuration setting name.
        isBusinessKey: true
        name: SETTING_NM
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 9c06ffee-cfde-4d95-98c9-72fd7694989f
                stepCounter: c3c529f9-4984-4d78-96ae-324cf718a150
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7226402e-ae0c-4735-a954-c4bdba415111
          stepCounter: 542c2f91-a181-4150-a401-9d0d2a01e1a8
        config: {}
        dataType: VARCHAR(300)
        defaultValue: ""
        description: The configuration setting value.
        isChangeTracking: true
        name: SETTING_VLU
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 821b8049-9937-4c8d-8bba-8bccb00c23c1
                stepCounter: c3c529f9-4984-4d78-96ae-324cf718a150
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 124d2d36-100d-43ed-97c3-fe6a65bcde54
          stepCounter: 542c2f91-a181-4150-a401-9d0d2a01e1a8
        config: {}
        dataType: VARCHAR(1000)
        defaultValue: ""
        description: The description of the configuration setting.
        isChangeTracking: true
        name: SETTING_DESC
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 544c0bc4-c9fb-43da-af5b-7503874be8ed
                stepCounter: c3c529f9-4984-4d78-96ae-324cf718a150
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 75b9e253-c5de-44e3-9acb-2b3d90e46551
          stepCounter: 542c2f91-a181-4150-a401-9d0d2a01e1a8
        config: {}
        dataType: VARCHAR(30)
        defaultValue: ""
        description: The user who created the record.
        isChangeTracking: true
        name: CREATE_USER
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 1efc1cdb-751d-469f-8335-7f85b67b6deb
                stepCounter: c3c529f9-4984-4d78-96ae-324cf718a150
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 14e934ff-cd09-4da2-80cb-eaf963e39a28
          stepCounter: 542c2f91-a181-4150-a401-9d0d2a01e1a8
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: The date the record was created.
        isChangeTracking: true
        name: CREATE_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 2591f463-a667-4ecb-aa98-a65149af3c69
                stepCounter: c3c529f9-4984-4d78-96ae-324cf718a150
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: acb7e0fc-84e0-452e-beee-b5fd2f74dc41
          stepCounter: 542c2f91-a181-4150-a401-9d0d2a01e1a8
        config: {}
        dataType: VARCHAR(30)
        defaultValue: ""
        description: The user who last updated the record.
        isChangeTracking: true
        name: LAST_UPDATE_USER
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: e9c7d948-0b17-480d-9159-bb5998d92093
                stepCounter: c3c529f9-4984-4d78-96ae-324cf718a150
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 716e98bd-d967-42ad-b085-2f22ba2da470
          stepCounter: 542c2f91-a181-4150-a401-9d0d2a01e1a8
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: The date the record was last updated.
        isChangeTracking: true
        name: LAST_UPDATE_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 5ef182ba-eba6-4987-9f58-e50297747d50
                stepCounter: c3c529f9-4984-4d78-96ae-324cf718a150
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 66ed5a67-9d88-4923-9c2e-953a6756db89
          stepCounter: 542c2f91-a181-4150-a401-9d0d2a01e1a8
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: a7417ab5-ea2f-4700-8ba1-2f448bceb1bf
                stepCounter: c3c529f9-4984-4d78-96ae-324cf718a150
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 64ad2d89-18bd-4ddc-b2c2-5c4e71cab13b
          stepCounter: 542c2f91-a181-4150-a401-9d0d2a01e1a8
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 79783420-6ed8-44c1-9c91-40673407f084
                stepCounter: c3c529f9-4984-4d78-96ae-324cf718a150
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 316eae3f-f01d-49b6-8d6b-a6c4ae0c28d0
          stepCounter: 542c2f91-a181-4150-a401-9d0d2a01e1a8
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: Flag field to identify Deleted record
        name: DSS_DELETE_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 26abd071-f0d2-4233-aabd-be16abe15704
          stepCounter: 542c2f91-a181-4150-a401-9d0d2a01e1a8
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Records time when record was set to Delete by the Load process
        name: DSS_DELETE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b3d4d933-5499-4a62-83f3-e493e67c8104
          stepCounter: 542c2f91-a181-4150-a401-9d0d2a01e1a8
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Datetime a business key was started.
        isSystemStartDate: true
        name: DSS_START_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 20bb0b86-11b2-4018-9027-6cb9ba200c90
          stepCounter: 542c2f91-a181-4150-a401-9d0d2a01e1a8
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Datetime a business key was retired.
        isSystemEndDate: true
        name: DSS_END_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 9be3414f-c809-45c2-bf39-ecdf9bb5e909
          stepCounter: 542c2f91-a181-4150-a401-9d0d2a01e1a8
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: Flag to indicate the current (latest) version of a business key.
        isSystemCurrentFlag: true
        name: DSS_CURRENT_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 767f0430-77d6-432c-9226-976a947c6d82
          stepCounter: 542c2f91-a181-4150-a401-9d0d2a01e1a8
        config: {}
        dataType: INTEGER
        defaultValue: ""
        description: Version number of a business key.
        isSystemVersion: true
        name: DSS_VERSION
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 61e5cad4-a304-4da8-8549-fc9db59ac82c
          stepCounter: 542c2f91-a181-4150-a401-9d0d2a01e1a8
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was created in the data warehouse.
        isSystemCreateDate: true
        name: DSS_CREATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 403267a1-0d8a-46a9-803b-b91329aaf9a4
          stepCounter: 542c2f91-a181-4150-a401-9d0d2a01e1a8
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was updated in the data warehouse.
        isSystemUpdateDate: true
        name: DSS_UPDATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          LOAD_QBYTE_SS_CLIENT_CONFIGURATION: c3c529f9-4984-4d78-96ae-324cf718a150
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: TARGET
            nodeName: LOAD_QBYTE_SS_CLIENT_CONFIGURATION
        join:
          joinCondition: FROM {{ ref('TARGET','LOAD_QBYTE_SS_CLIENT_CONFIGURATION') }} LOAD_QBYTE_SS_CLIENT_CONFIGURATION
        name: ODS_QBYTE_SS_CLIENT_CONFIGURATION
        noLinkRefs: []
  name: ODS_QBYTE_SS_CLIENT_CONFIGURATION
  overrideSQL: false
  schema: ""
  sqlType: persistentStage
  type: sql
  version: 1
type: Node
