fileVersion: 1
id: 7e73c9f3-784b-449d-a22d-ca77645620f1
name: LOAD_XSPOC_TBLAPPLICATIONPARAMSTANDARDTYPES
operation:
  config:
    archive_enabled: true
    archive_path: archive
    extlocation: false
    fieldDelim: ~|~
    fieldEnclosed: '"'
    fileFormatType: File Format Values
    filePattern: ''
    fileType: CSV
    inferschema: false
    insertStrategy: INSERT
    intextstage: true
    postSQL: ''
    preSQL: ''
    recDelim: ''
    replaceinvalidcharacters: false
    skipBlankLines: false
    skipHeader: '1'
    stageName: s3_LOAD_XSPOC_TBLAPPLICATIONPARAMSTANDARDTYPES
    stageStorageLocationName: DV2_STG
    stripouterarray: false
    subfolder: ''
    testsEnabled: true
    trimSpace: false
    truncateBefore: true
    usevectscan: false
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 9d855356-2e5f-4696-a3f3-5333e42b12bf
          stepCounter: 7e73c9f3-784b-449d-a22d-ca77645620f1
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: APPLICATIONID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d68926cd-87c9-4e38-85a6-39014d741ab1
          stepCounter: 7e73c9f3-784b-449d-a22d-ca77645620f1
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: PARAMSTANDARDTYPE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c4d270cd-872b-409d-b5fe-8cf7664f01de
          stepCounter: 7e73c9f3-784b-449d-a22d-ca77645620f1
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: ISUSEDFORANALYSIS
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0f0feded-15f2-4046-a209-9eab0ca61ff3
          stepCounter: 7e73c9f3-784b-449d-a22d-ca77645620f1
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: DISPLAYORDER
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 76cd8dd8-f8ac-4e90-a000-de2bdf94f737
          stepCounter: 7e73c9f3-784b-449d-a22d-ca77645620f1
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: ISREQUIREDFORANALYSIS
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d38b38c0-f2fa-4879-912f-e931cd9c4963
          stepCounter: 7e73c9f3-784b-449d-a22d-ca77645620f1
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: ALLOWSNOTE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ca59876b-27a3-4003-8706-41d47e782668
          stepCounter: 7e73c9f3-784b-449d-a22d-ca77645620f1
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ba51ea4f-be66-4e04-8a4d-364e091b0f89
          stepCounter: 7e73c9f3-784b-449d-a22d-ca77645620f1
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences: []
    enabledColumnTestIDs: []
    sourceMapping: []
  name: LOAD_XSPOC_TBLAPPLICATIONPARAMSTANDARDTYPES
  overrideSQL: false
  schema: ""
  sqlType: External:::324
  type: sql
  version: 1
type: Node
