fileVersion: 1
id: 15a0662e-3c25-4ff4-85ef-88e020e7d918
name: LOAD_MOSAIC_RES_WORKSPACE_SETTINGS
operation:
  database: ""
  deployEnabled: true
  description: ""
  locationName: TARGET
  metadata:
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 165bbe68-4e7b-461d-9503-35aeefe99fce
          stepCounter: 15a0662e-3c25-4ff4-85ef-88e020e7d918
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: CURRENT_CASE_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: bd7ea7fb-36cf-48e4-8a99-d4ce031bb35c
          stepCounter: 15a0662e-3c25-4ff4-85ef-88e020e7d918
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: DEFAULT_COMPANY_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 68221e44-8eaa-4229-b288-cd7e47e420bf
          stepCounter: 15a0662e-3c25-4ff4-85ef-88e020e7d918
        config: {}
        dataType: VARCHAR(250)
        defaultValue: ""
        description: ""
        name: DESCRIPTION
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 003f8fe6-de14-447d-9771-320df1af1f72
          stepCounter: 15a0662e-3c25-4ff4-85ef-88e020e7d918
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_BY_USER
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d6cd0ea4-87a7-4366-a75f-e773b54366b2
          stepCounter: 15a0662e-3c25-4ff4-85ef-88e020e7d918
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_DATE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b219bdb3-9622-4464-b856-2346ee394483
          stepCounter: 15a0662e-3c25-4ff4-85ef-88e020e7d918
        config: {}
        dataType: VARCHAR(100)
        defaultValue: ""
        description: ""
        name: NAME
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b90447fe-34e8-4b87-b0b0-dfef0b772690
          stepCounter: 15a0662e-3c25-4ff4-85ef-88e020e7d918
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: PREVIOUS_CASE_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d296f658-9235-4791-acbc-a9c8dfece5db
          stepCounter: 15a0662e-3c25-4ff4-85ef-88e020e7d918
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: PRIVATE_FLAG
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 12d4e7f6-c46d-4a4b-abb9-e902ce616d77
          stepCounter: 15a0662e-3c25-4ff4-85ef-88e020e7d918
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: RESERVE_CAT_GROUP_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d402bb92-3f7c-45af-96fc-74739c435c70
          stepCounter: 15a0662e-3c25-4ff4-85ef-88e020e7d918
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: SEARCH_FILTER_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 489ea2fc-cdeb-451f-8272-19354d6ee257
          stepCounter: 15a0662e-3c25-4ff4-85ef-88e020e7d918
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: USER_PROFILE_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b46f1d97-37ed-4524-b351-9b46e1d9065c
          stepCounter: 15a0662e-3c25-4ff4-85ef-88e020e7d918
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        name: UUID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6005316b-a488-4f27-a5b1-e99a501275f0
          stepCounter: 15a0662e-3c25-4ff4-85ef-88e020e7d918
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: WORKBENCH_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c7607f58-2bc7-4e7b-bffb-e71469f680e5
          stepCounter: 15a0662e-3c25-4ff4-85ef-88e020e7d918
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: WORKSPACE_SETTINGS_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f135af1a-1acc-4b75-8673-2aa8417d47af
          stepCounter: 15a0662e-3c25-4ff4-85ef-88e020e7d918
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        name: DEFAULT_STATIC_HIERARCHY_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f0aa7f77-ec1b-41f7-979f-bae84840c0bd
          stepCounter: 15a0662e-3c25-4ff4-85ef-88e020e7d918
        config: {}
        dataType: VARCHAR(250)
        defaultValue: ""
        description: ""
        name: HIERARCHY_FILTER_NAME
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0ca4b254-0801-4097-8b20-b06b6864e010
          stepCounter: 15a0662e-3c25-4ff4-85ef-88e020e7d918
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        name: ENTITY_STATE_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 59090168-1407-4557-8799-f69a0ad28f64
          stepCounter: 15a0662e-3c25-4ff4-85ef-88e020e7d918
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        name: WORKSPACE_VIEW_TYPE_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3a071828-9ce5-4388-8e80-ba18964c2890
          stepCounter: 15a0662e-3c25-4ff4-85ef-88e020e7d918
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        name: PANEL_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f5cdbeef-945f-4667-bf69-64e3243b5d10
          stepCounter: 15a0662e-3c25-4ff4-85ef-88e020e7d918
        config: {}
        dataType: VARCHAR(200)
        defaultValue: ""
        description: ""
        name: TABLE_COLUMN_SET
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: cf6d86c0-5f8c-45bd-ac98-297008e09cf0
          stepCounter: 15a0662e-3c25-4ff4-85ef-88e020e7d918
        config: {}
        dataType: VARCHAR(200)
        defaultValue: ""
        description: ""
        name: ECONOMIC_COLUMN_SET
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: bca5746c-7474-4b5b-9802-a2aefd0d80dc
          stepCounter: 15a0662e-3c25-4ff4-85ef-88e020e7d918
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        name: ICON_CODE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 64d02a0f-aca9-4e80-84e3-61f71e21d93d
          stepCounter: 15a0662e-3c25-4ff4-85ef-88e020e7d918
        config: {}
        dataType: VARCHAR(250)
        defaultValue: ""
        description: ""
        name: ENTITY_NAME
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0708dcf3-0118-4f7a-a925-17430871f13d
          stepCounter: 15a0662e-3c25-4ff4-85ef-88e020e7d918
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: RESERVE_CATEGORY_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c5761b48-348f-4d90-bc3c-f1c1ab4f632b
          stepCounter: 15a0662e-3c25-4ff4-85ef-88e020e7d918
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: RECON_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1a5ad952-fe5d-443c-8b76-9c973787d334
          stepCounter: 15a0662e-3c25-4ff4-85ef-88e020e7d918
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8bafdb2e-acd0-4535-8941-8d5c685fff9b
          stepCounter: 15a0662e-3c25-4ff4-85ef-88e020e7d918
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
  name: LOAD_MOSAIC_RES_WORKSPACE_SETTINGS
  schema: ""
  sqlType: Source
  type: sourceInput
  version: 1
type: Node
