fileVersion: 1
id: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
name: LOAD_MOSAIC_RES_USER_SETTINGS
operation:
  config:
    archive_enabled: true
    archive_path: archive
    extlocation: false
    fieldDelim: ~|~
    fieldEnclosed: '"'
    fileFormatType: File Format Values
    filePattern: ''
    fileType: CSV
    inferschema: false
    insertStrategy: INSERT
    intextstage: true
    postSQL: ''
    preSQL: ''
    recDelim: ''
    replaceinvalidcharacters: false
    skipBlankLines: false
    skipHeader: '1'
    stageName: s3_LOAD_MOSAIC_RES_USER_SETTINGS
    stageStorageLocationName: DV2_STG
    stripouterarray: false
    subfolder: ''
    testsEnabled: true
    trimSpace: false
    truncateBefore: true
    usevectscan: false
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 015c4761-90e9-4fed-8d8c-d0e5f4563a8a
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: VARCHAR(150)
        defaultValue: ""
        description: ""
        name: ADDITIONAL_REPORT_TEXT
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ac03ca05-f5c4-4871-a6ca-4ecc9515eb0f
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: ALTERNATE_LINE_SHADING
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e4a9b5ed-99e1-4a45-ae8e-c6b37e371086
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: BUDGET_MONTH_RANGE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 4cf1360d-2789-46cc-bd83-64f96a6e5bf7
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: BUDGET_YEAR
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: dde7c123-fc7a-4d8d-88e5-bceebf26f7a6
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: ""
        name: CASH_FLOW_SHORT
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1e8b9837-c3f7-4e8a-94b2-0279d39f3dfc
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: VARCHAR(100)
        defaultValue: ""
        description: ""
        name: CORPORATION_NAME
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f115781a-443e-4f6e-ab90-9f872870d3f4
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_1
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3b9defee-9df3-4579-9850-351d53a39885
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_2
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c8c953f6-b5f8-4b5f-ac5c-d2f9b2165353
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_3
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 826a0f79-b0f1-432c-95ff-dc8b73e3a77c
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_4
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0dc0ed6f-f5cc-4fdd-8ec5-83290c080794
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: NUMBER(24)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_5
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8bf4cdc5-68ea-4f67-918f-ac886a211e70
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: ECONOMIC_INDICATOR_FLAG
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f0e9056d-eb5a-45a9-aa51-e7a3a5c3fe2f
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: EXPECTED_VALUES_FLAG
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0c106f8d-12a8-480b-89bd-10a740b962a5
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: RESERVE_BOE_EQUIV_FLAG
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d7d7e648-35ee-4549-bc64-7cc82283faeb
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: USER_SETTINGS_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 16791a6c-0c0c-4212-a8ba-2d0c0903e84b
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: YEARS_REPORTED
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 80f84cf7-bb5d-42a2-a62f-3f01b821eb6b
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: YEARS_REPORTED_BY_MONTH
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 9d639ed4-3540-4b1f-bac1-ea853b9fbe6b
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_1A
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b4cd7afa-e36a-4190-a2a5-11185e4f5490
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_2A
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e3b529cc-f463-4649-8ef0-19c859906cf6
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_3A
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a891af34-8e8c-4bb9-bb58-6b3ccc30c76e
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_4A
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 357933dc-bdee-4d16-bb8a-b476d463b705
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_1B
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: fc716087-da8c-494e-9bcf-bc64f99dc374
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_2B
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 86b50ddb-9b92-4f85-adad-fbc051290135
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_3B
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 2424ae8a-bdbb-4dbf-8dfe-a25cd8d6f05e
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: ""
        name: VOL_AND_REVENUE_DETAIL_FLAG
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 46e1fe99-336b-4fad-9cab-1b06fec48710
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: ""
        name: ATAX_PKG_FLAG
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 92fae344-3596-4cd0-b1b1-0e947275273e
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: ""
        name: CAPITAL_UNDISCOUNTED_FLAG
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 22f282c6-7014-487f-8f7c-1f6679ba29ee
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: ""
        name: FIRST_YR_ANNUAL_PRFRMNC_FLAG
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: be846987-c1a3-4837-9ba6-e88a5ec935a2
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: ""
        name: INCLUDE_COVER_PAGE_FLAG
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c68f15dc-e641-4f46-a4f1-a5896ecb2e71
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: ""
        name: REPORT_PAGE_NUMBERS
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c4feb054-b58b-4751-8429-fafd1df8fcff
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: VARCHAR(150)
        defaultValue: ""
        description: ""
        name: ADDITIONAL_REPORT_TEXT_2
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: eb0f4485-bd56-49d0-88c3-0dd78c627565
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: ""
        name: OVERWRITE_PROD_DATA
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: cdfbd272-5f6b-46ec-b188-650333905538
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_DATE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f26ad85f-da33-4c12-868a-3b734e88b521
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: VARCHAR(100)
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_BY_USER
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 798684b1-ca53-4719-8aa1-3460637af7bb
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 486de6e4-b2d7-49c7-badc-e49de35b3a25
          stepCounter: 249d8947-ccbf-4a2c-a98e-3c1eb45f82f8
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences: []
    enabledColumnTestIDs: []
    sourceMapping: []
  name: LOAD_MOSAIC_RES_USER_SETTINGS
  overrideSQL: false
  schema: ""
  sqlType: External:::324
  type: sql
  version: 1
type: Node
