fileVersion: 1
id: 2c42e794-1956-47f4-b0cb-b4a29cbe6f56
name: LOAD_XSPOC_TBLFAILUREAPPLICATIONSCAUSES
operation:
  database: ""
  deployEnabled: true
  description: ""
  locationName: TARGET
  metadata:
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3fe50d30-bd05-4f9b-a7e1-93f39125cce3
          stepCounter: 2c42e794-1956-47f4-b0cb-b4a29cbe6f56
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ecc9bbb7-f147-47c6-ba75-9de7de53dccd
          stepCounter: 2c42e794-1956-47f4-b0cb-b4a29cbe6f56
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: APPLICATIONID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1019b502-8788-4e6f-bd21-8a26835c91b9
          stepCounter: 2c42e794-1956-47f4-b0cb-b4a29cbe6f56
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: CAUSEID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 104aa24f-f34e-4ee6-abaa-f9ca89fe283e
          stepCounter: 2c42e794-1956-47f4-b0cb-b4a29cbe6f56
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: fa0a29fe-fe6e-4001-a707-e4c107138994
          stepCounter: 2c42e794-1956-47f4-b0cb-b4a29cbe6f56
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
  name: LOAD_XSPOC_TBLFAILUREAPPLICATIONSCAUSES
  schema: ""
  sqlType: Source
  type: sourceInput
  version: 1
type: Node
