fileVersion: 1
id: 6413e07d-e15d-4105-a61b-a443f53dff18
name: LOAD_XSPOC_TBLOPERATIONSTATEFIELDVALUES
operation:
  config:
    archive_enabled: true
    archive_path: archive
    extlocation: false
    fieldDelim: ~|~
    fieldEnclosed: '"'
    fileFormatType: File Format Values
    filePattern: ''
    fileType: CSV
    inferschema: false
    insertStrategy: INSERT
    intextstage: true
    postSQL: ''
    preSQL: ''
    recDelim: ''
    replaceinvalidcharacters: false
    skipBlankLines: false
    skipHeader: '1'
    stageName: s3_LOAD_XSPOC_TBLOPERATIONSTATEFIELDVALUES
    stageStorageLocationName: DV2_STG
    stripouterarray: false
    subfolder: ''
    testsEnabled: true
    trimSpace: false
    truncateBefore: true
    usevectscan: false
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: bf4a1e81-b9ab-4736-8dd8-65f15e1b410b
          stepCounter: 6413e07d-e15d-4105-a61b-a443f53dff18
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: OPERATIONSTATEFIELDID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 55044680-7e39-4217-b90d-82baa34b52d9
          stepCounter: 6413e07d-e15d-4105-a61b-a443f53dff18
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: VALUE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7fa2fc63-f1c1-4449-8cf7-a6f2df88fc2f
          stepCounter: 6413e07d-e15d-4105-a61b-a443f53dff18
        config: {}
        dataType: VARCHAR(100)
        defaultValue: ""
        description: ""
        name: NAME
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8ba288e2-fa58-438b-8bb6-8b9ac64cb5ee
          stepCounter: 6413e07d-e15d-4105-a61b-a443f53dff18
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: bac82062-485f-4465-a28f-2785c7285fc7
          stepCounter: 6413e07d-e15d-4105-a61b-a443f53dff18
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences: []
    enabledColumnTestIDs: []
    sourceMapping: []
  name: LOAD_XSPOC_TBLOPERATIONSTATEFIELDVALUES
  overrideSQL: false
  schema: ""
  sqlType: External:::324
  type: sql
  version: 1
type: Node
