fileVersion: 1
id: daba6e0c-0f7d-4f98-8ef3-ca45ae884987
name: LOAD_QBYTE_IMAGING_CONFIGS
operation:
  database: ""
  deployEnabled: true
  description: ""
  locationName: TARGET
  metadata:
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 54d1c7ba-a907-4e79-9780-8ca02c886b84
          stepCounter: daba6e0c-0f7d-4f98-8ef3-ca45ae884987
        config: {}
        dataType: VARCHAR(40)
        defaultValue: ""
        description: The document type.
        name: DOCUMENT_TYPE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 4f5456ed-94ef-4101-9132-aecd5246eeb2
          stepCounter: daba6e0c-0f7d-4f98-8ef3-ca45ae884987
        config: {}
        dataType: VARCHAR(40)
        defaultValue: ""
        description: The dde server.
        name: DDE_SERVER
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c1cf04fd-f327-4369-b191-736c3806c947
          stepCounter: daba6e0c-0f7d-4f98-8ef3-ca45ae884987
        config: {}
        dataType: VARCHAR(40)
        defaultValue: ""
        description: The dde topic.
        name: DDE_TOPIC
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0d5d1fff-1145-4211-9455-aa00bd59fa4d
          stepCounter: daba6e0c-0f7d-4f98-8ef3-ca45ae884987
        config: {}
        dataType: NUMBER(10)
        defaultValue: ""
        description: The dde timeout.
        name: DDE_TIMEOUT
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6c271133-b7a2-447d-8eec-430771bdc941
          stepCounter: daba6e0c-0f7d-4f98-8ef3-ca45ae884987
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: The dde command.
        name: DDE_COMMAND
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1c18482e-ba58-4b3a-a59c-a7883f65c01b
          stepCounter: daba6e0c-0f7d-4f98-8ef3-ca45ae884987
        config: {}
        dataType: VARCHAR(40)
        defaultValue: ""
        description: The label on the button.
        name: BUTTON_HINT_LABEL
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: cb43b277-3978-437b-bd0e-31ef896cb49a
          stepCounter: daba6e0c-0f7d-4f98-8ef3-ca45ae884987
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: Virtual directory where the imaging software is stored.
        name: WEB_DIRECTORY
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 2fca28a9-4692-4a7c-b369-9ea3e1379668
          stepCounter: daba6e0c-0f7d-4f98-8ef3-ca45ae884987
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: The starting web page of the imaging software.
        name: WEB_PAGE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a4141f82-54e4-4dc3-a1b7-6d4742b5c57f
          stepCounter: daba6e0c-0f7d-4f98-8ef3-ca45ae884987
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: To store specifics of web page address that relates to the way imaged documents are stored.
        name: WEB_COMMAND
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 44d24fba-2b91-4db4-96a0-24029b391617
          stepCounter: daba6e0c-0f7d-4f98-8ef3-ca45ae884987
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7c5481f8-3c13-4994-8462-06030901ff17
          stepCounter: daba6e0c-0f7d-4f98-8ef3-ca45ae884987
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
  name: LOAD_QBYTE_IMAGING_CONFIGS
  schema: ""
  sqlType: Source
  type: sourceInput
  version: 1
type: Node
