fileVersion: 1
id: def24d7e-f1e3-4e6c-98ec-21c645642e65
name: LOAD_XSPOC_TBLGRAPHVIEWSETTINGS
operation:
  config:
    archive_enabled: true
    archive_path: archive
    extlocation: false
    fieldDelim: ~|~
    fieldEnclosed: '"'
    fileFormatType: File Format Values
    filePattern: ''
    fileType: CSV
    inferschema: false
    insertStrategy: INSERT
    intextstage: true
    postSQL: ''
    preSQL: ''
    recDelim: ''
    replaceinvalidcharacters: false
    skipBlankLines: false
    skipHeader: '1'
    stageName: s3_LOAD_XSPOC_TBLGRAPHVIEWSETTINGS
    stageStorageLocationName: DV2_STG
    stripouterarray: false
    subfolder: ''
    testsEnabled: true
    trimSpace: false
    truncateBefore: true
    usevectscan: false
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e84cc815-e47e-495b-98fb-3fc2aa8c5842
          stepCounter: def24d7e-f1e3-4e6c-98ec-21c645642e65
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: VIEWID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 00e680d8-6d2f-4c0d-a11b-05e9e237a006
          stepCounter: def24d7e-f1e3-4e6c-98ec-21c645642e65
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        name: PROPERTY
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7f8fd258-d847-40b8-ae9a-7787bf44928f
          stepCounter: def24d7e-f1e3-4e6c-98ec-21c645642e65
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        name: VALUE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 42d6e304-2573-4fbe-8427-45d19452c566
          stepCounter: def24d7e-f1e3-4e6c-98ec-21c645642e65
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7c3a3e30-f8ce-4221-8ef0-3ba1a99af6d6
          stepCounter: def24d7e-f1e3-4e6c-98ec-21c645642e65
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences: []
    enabledColumnTestIDs: []
    sourceMapping: []
  name: LOAD_XSPOC_TBLGRAPHVIEWSETTINGS
  overrideSQL: false
  schema: ""
  sqlType: External:::324
  type: sql
  version: 1
type: Node
