fileVersion: 1
id: b37a8bb7-cda8-45ab-963d-a93f32c6cb42
name: LOAD_XSPOC_TBLAPPLICATIONS
operation:
  config:
    archive_enabled: true
    archive_path: archive
    extlocation: false
    fieldDelim: ~|~
    fieldEnclosed: '"'
    fileFormatType: File Format Values
    filePattern: ''
    fileType: CSV
    inferschema: false
    insertStrategy: INSERT
    intextstage: true
    postSQL: ''
    preSQL: ''
    recDelim: ''
    replaceinvalidcharacters: false
    skipBlankLines: false
    skipHeader: '1'
    stageName: s3_LOAD_XSPOC_TBLAPPLICATIONS
    stageStorageLocationName: DV2_STG
    stripouterarray: false
    subfolder: ''
    testsEnabled: true
    trimSpace: false
    truncateBefore: true
    usevectscan: false
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 095fa7bd-1e9a-43db-b1d8-304b7d615821
          stepCounter: b37a8bb7-cda8-45ab-963d-a93f32c6cb42
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: dfbd961c-9eff-40c2-9bbd-ce0b8207b556
          stepCounter: b37a8bb7-cda8-45ab-963d-a93f32c6cb42
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        name: NAME
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: fd26dea9-88b2-42be-92cc-68e37c813c78
          stepCounter: b37a8bb7-cda8-45ab-963d-a93f32c6cb42
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: PHRASEID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 97200c88-7e58-491a-a12a-f21d798ff96c
          stepCounter: b37a8bb7-cda8-45ab-963d-a93f32c6cb42
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5e44f56c-95e7-4e38-a8f7-0bb3bc411122
          stepCounter: b37a8bb7-cda8-45ab-963d-a93f32c6cb42
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences: []
    enabledColumnTestIDs: []
    sourceMapping: []
  name: LOAD_XSPOC_TBLAPPLICATIONS
  overrideSQL: false
  schema: ""
  sqlType: External:::324
  type: sql
  version: 1
type: Node
