fileVersion: 1
id: 38af1032-5673-41a5-a854-73662b7b7d1f
name: LOAD_XSPOC_TBLOPERATIONSTATEFIELDVALUES
operation:
  database: ""
  deployEnabled: true
  description: ""
  locationName: TARGET
  metadata:
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 9264a473-1ceb-4808-87e0-aec40489405c
          stepCounter: 38af1032-5673-41a5-a854-73662b7b7d1f
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: OPERATIONSTATEFIELDID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 2f45fb74-a1f3-4fd6-94e7-d37eea7d0d16
          stepCounter: 38af1032-5673-41a5-a854-73662b7b7d1f
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: VALUE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0de2a19d-1dbf-41e7-83a7-a1ad3f409ac7
          stepCounter: 38af1032-5673-41a5-a854-73662b7b7d1f
        config: {}
        dataType: VARCHAR(100)
        defaultValue: ""
        description: ""
        name: NAME
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d804814b-b491-4364-b23b-85d6b3ea7b2b
          stepCounter: 38af1032-5673-41a5-a854-73662b7b7d1f
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e7317af7-016e-484a-ae3d-de9ddbd264e0
          stepCounter: 38af1032-5673-41a5-a854-73662b7b7d1f
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
  name: LOAD_XSPOC_TBLOPERATIONSTATEFIELDVALUES
  schema: ""
  sqlType: Source
  type: sourceInput
  version: 1
type: Node
