fileVersion: 1
id: cd681544-4c6e-4884-b48b-319cb31f8b16
name: ODS_XSPOC_TBLMOTORSETTINGS
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1718eac2-bcd7-4ba0-b4c5-64e35260b7b6
          stepCounter: cd681544-4c6e-4884-b48b-319cb31f8b16
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: MOTORSETTINGID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: a6ba25f8-7153-4f5d-b5cc-3e51ddface48
                stepCounter: d7545f41-2e9c-4ec7-bb95-ebba7b4c1801
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6d6264dd-8a03-403a-a067-bdc38e50327c
          stepCounter: cd681544-4c6e-4884-b48b-319cb31f8b16
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: NAME
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: c0b15013-800b-401f-ad34-ca70ed73dcbe
                stepCounter: d7545f41-2e9c-4ec7-bb95-ebba7b4c1801
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3313b282-1615-40a9-991f-fdd9b03d9851
          stepCounter: cd681544-4c6e-4884-b48b-319cb31f8b16
        config: {}
        dataType: FLOAT
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: FULLLOADRPM
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 86529f4c-9fc9-4459-8370-acee36d55165
                stepCounter: d7545f41-2e9c-4ec7-bb95-ebba7b4c1801
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 43eed415-7002-40c9-abb1-b4a5a247e897
          stepCounter: cd681544-4c6e-4884-b48b-319cb31f8b16
        config: {}
        dataType: FLOAT
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: MAXLOAD
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: ad3b483e-b37a-474f-8326-658b0e12a232
                stepCounter: d7545f41-2e9c-4ec7-bb95-ebba7b4c1801
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1e1018bb-1e5c-4dd0-ae1e-0b33c0879fba
          stepCounter: cd681544-4c6e-4884-b48b-319cb31f8b16
        config: {}
        dataType: FLOAT
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: MAXSPV
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 810b2ac7-9518-41a0-9fc8-a2a33c8fef92
                stepCounter: d7545f41-2e9c-4ec7-bb95-ebba7b4c1801
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 46f82877-42a5-443b-9bcd-6cdbbea37f03
          stepCounter: cd681544-4c6e-4884-b48b-319cb31f8b16
        config: {}
        dataType: FLOAT
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: RATEDHP
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 30a131a2-c40d-408e-8b86-71efcc91bf03
                stepCounter: d7545f41-2e9c-4ec7-bb95-ebba7b4c1801
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a88c825a-3004-4921-b129-b2faa1a330b4
          stepCounter: cd681544-4c6e-4884-b48b-319cb31f8b16
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: MOTORSIZEID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 0c0380e7-1a89-4c92-9d28-1b3b74988f1f
                stepCounter: d7545f41-2e9c-4ec7-bb95-ebba7b4c1801
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6d5855c4-1bab-44b7-b8fc-3aee974a1ecc
          stepCounter: cd681544-4c6e-4884-b48b-319cb31f8b16
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 11079f13-9feb-40b6-9e8f-d1007a330412
                stepCounter: d7545f41-2e9c-4ec7-bb95-ebba7b4c1801
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3eb611ae-0eee-4f46-b8d0-02bd9e2a8b1b
          stepCounter: cd681544-4c6e-4884-b48b-319cb31f8b16
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: e3b60bd0-39d0-4a52-987b-cc41c0e2fd86
                stepCounter: d7545f41-2e9c-4ec7-bb95-ebba7b4c1801
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 66d8de06-2ff1-492d-80e7-c5d7c2ac7835
          stepCounter: cd681544-4c6e-4884-b48b-319cb31f8b16
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: Flag field to identify Deleted record
        name: DSS_DELETE_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 19d8b5b1-ee43-42e9-8171-f5ea495c8b93
          stepCounter: cd681544-4c6e-4884-b48b-319cb31f8b16
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Records time when record was set to Delete by the Load process
        name: DSS_DELETE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f92263a8-6069-40eb-98b8-2bc2f7e52ea2
          stepCounter: cd681544-4c6e-4884-b48b-319cb31f8b16
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Datetime a business key was started.
        isSystemStartDate: true
        name: DSS_START_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3751cfba-df5b-4b13-a344-19af9c4ea6d4
          stepCounter: cd681544-4c6e-4884-b48b-319cb31f8b16
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Datetime a business key was retired.
        isSystemEndDate: true
        name: DSS_END_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 80f35388-ba75-4f0a-aa57-b729a467f31f
          stepCounter: cd681544-4c6e-4884-b48b-319cb31f8b16
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: Flag to indicate the current (latest) version of a business key.
        isSystemCurrentFlag: true
        name: DSS_CURRENT_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f26542d6-e73e-4a0e-bc3c-b09c1801dab9
          stepCounter: cd681544-4c6e-4884-b48b-319cb31f8b16
        config: {}
        dataType: INTEGER
        defaultValue: ""
        description: Version number of a business key.
        isSystemVersion: true
        name: DSS_VERSION
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 24244893-b846-408e-8e39-ccb6aa30bd96
          stepCounter: cd681544-4c6e-4884-b48b-319cb31f8b16
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was created in the data warehouse.
        isSystemCreateDate: true
        name: DSS_CREATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: adcfcaf9-b146-4669-a7e8-d38a60767810
          stepCounter: cd681544-4c6e-4884-b48b-319cb31f8b16
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was updated in the data warehouse.
        isSystemUpdateDate: true
        name: DSS_UPDATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          LOAD_XSPOC_TBLMOTORSETTINGS: d7545f41-2e9c-4ec7-bb95-ebba7b4c1801
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: TARGET
            nodeName: LOAD_XSPOC_TBLMOTORSETTINGS
        join:
          joinCondition: FROM {{ ref('TARGET','LOAD_XSPOC_TBLMOTORSETTINGS') }} LOAD_XSPOC_TBLMOTORSETTINGS
        name: ODS_XSPOC_TBLMOTORSETTINGS
        noLinkRefs: []
  name: ODS_XSPOC_TBLMOTORSETTINGS
  overrideSQL: false
  schema: ""
  sqlType: '38'
  type: sql
  version: 1
type: Node
