fileVersion: 1
id: 446e7439-75a5-4562-9f31-cf5d8c29fe93
name: ODS_CSLAND_CS_SECURITY
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ac6fabf5-8f0e-442b-b4cb-ad80f79da42c
          stepCounter: 446e7439-75a5-4562-9f31-cf5d8c29fe93
        config: {}
        dataType: VARCHAR(30)
        defaultValue: ""
        description: Process Id
        isBusinessKey: true
        name: PROCESS_ID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 35cb9cf7-3e3d-4df7-beb4-bca555bf5cbe
                stepCounter: 833c6ae3-5277-47a7-9ee1-443cb11c0201
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5a08f233-5711-490b-a0c3-3ada0d24adcc
          stepCounter: 446e7439-75a5-4562-9f31-cf5d8c29fe93
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 5209e34d-8bfe-47ba-8ad3-64faeee0a321
                stepCounter: 833c6ae3-5277-47a7-9ee1-443cb11c0201
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 004dbf70-31bd-465d-892a-5e1a219b2c51
          stepCounter: 446e7439-75a5-4562-9f31-cf5d8c29fe93
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: e298a461-022b-4575-ac57-5ef76ea4c26a
                stepCounter: 833c6ae3-5277-47a7-9ee1-443cb11c0201
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1da964e5-097a-44c2-ad45-3fb3609eeaa5
          stepCounter: 446e7439-75a5-4562-9f31-cf5d8c29fe93
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: Flag field to identify Deleted record
        name: DSS_DELETE_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: fcb1f4b9-4e7d-4d92-81ec-8dad1b510029
          stepCounter: 446e7439-75a5-4562-9f31-cf5d8c29fe93
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Records time when record was set to Delete by the Load process
        name: DSS_DELETE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 82bac14c-9820-4eca-9ffd-84254e5283dc
          stepCounter: 446e7439-75a5-4562-9f31-cf5d8c29fe93
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was created in the data warehouse.
        isSystemCreateDate: true
        name: DSS_CREATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 9229eefc-c24d-45b3-8738-83582fb8f1fe
          stepCounter: 446e7439-75a5-4562-9f31-cf5d8c29fe93
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was updated in the data warehouse.
        isSystemUpdateDate: true
        name: DSS_UPDATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          LOAD_CSLAND_CS_SECURITY: 833c6ae3-5277-47a7-9ee1-443cb11c0201
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: TARGET
            nodeName: LOAD_CSLAND_CS_SECURITY
        join:
          joinCondition: FROM {{ ref('TARGET','LOAD_CSLAND_CS_SECURITY') }} LOAD_CSLAND_CS_SECURITY
        name: ODS_CSLAND_CS_SECURITY
        noLinkRefs: []
  name: ODS_CSLAND_CS_SECURITY
  overrideSQL: false
  schema: ""
  sqlType: '38'
  type: sql
  version: 1
type: Node
