fileVersion: 1
id: 441c1ccc-7185-4432-b4fa-0558a5286917
name: LOAD_XSPOC_TBLAPPLICATIONS
operation:
  database: ""
  deployEnabled: true
  description: ""
  locationName: TARGET
  metadata:
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e2fff44b-b48f-46be-8322-6132564603b9
          stepCounter: 441c1ccc-7185-4432-b4fa-0558a5286917
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 30d4c995-5564-4e68-ad33-1896c90337e8
          stepCounter: 441c1ccc-7185-4432-b4fa-0558a5286917
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        name: NAME
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 53e68bde-44cf-4183-8e79-cf5ae245194a
          stepCounter: 441c1ccc-7185-4432-b4fa-0558a5286917
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: PHRASEID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d04f9808-0876-4084-9fc4-dcd021cae72f
          stepCounter: 441c1ccc-7185-4432-b4fa-0558a5286917
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 676ac728-587a-4679-8ca5-1c7d6a0d277a
          stepCounter: 441c1ccc-7185-4432-b4fa-0558a5286917
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
  name: LOAD_XSPOC_TBLAPPLICATIONS
  schema: ""
  sqlType: Source
  type: sourceInput
  version: 1
type: Node
