fileVersion: 1
id: cfe7e7a6-b356-4cec-ac4c-291d94d2b774
name: LOAD_MOSAIC_RES_APPLICATION_FUNCTION
operation:
  config:
    archive_enabled: true
    archive_path: archive
    extlocation: false
    fieldDelim: ~|~
    fieldEnclosed: '"'
    fileFormatType: File Format Values
    filePattern: ''
    fileType: CSV
    inferschema: false
    insertStrategy: INSERT
    intextstage: true
    postSQL: ''
    preSQL: ''
    recDelim: ''
    replaceinvalidcharacters: false
    skipBlankLines: false
    skipHeader: '1'
    stageName: s3_LOAD_MOSAIC_RES_APPLICATION_FUNCTION
    stageStorageLocationName: DV2_STG
    stripouterarray: false
    subfolder: ''
    testsEnabled: true
    trimSpace: false
    truncateBefore: true
    usevectscan: false
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 67dd2698-77de-484d-83e5-e98a605cb78a
          stepCounter: cfe7e7a6-b356-4cec-ac4c-291d94d2b774
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: APPLICATION_FUNCTION_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 947e4c63-59ef-4c01-bda5-ad81915196b5
          stepCounter: cfe7e7a6-b356-4cec-ac4c-291d94d2b774
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: FUNCTION_TYPE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8b2769f3-0b12-49c8-8dfa-90cc4f877eab
          stepCounter: cfe7e7a6-b356-4cec-ac4c-291d94d2b774
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_BY_USER
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 9b68a79f-c798-4138-9a65-d3abe3d51f19
          stepCounter: cfe7e7a6-b356-4cec-ac4c-291d94d2b774
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_DATE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c437d45e-7784-431c-8684-e8822cca0a12
          stepCounter: cfe7e7a6-b356-4cec-ac4c-291d94d2b774
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: USER_GROUP_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 47d5c127-de0a-45f1-9f22-b9e5413c479f
          stepCounter: cfe7e7a6-b356-4cec-ac4c-291d94d2b774
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5f5cbd14-5987-4ae2-8fa1-121d9b150f9c
          stepCounter: cfe7e7a6-b356-4cec-ac4c-291d94d2b774
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences: []
    enabledColumnTestIDs: []
    sourceMapping: []
  name: LOAD_MOSAIC_RES_APPLICATION_FUNCTION
  overrideSQL: false
  schema: ""
  sqlType: External:::324
  type: sql
  version: 1
type: Node
