fileVersion: 1
id: 051954d5-9b2a-4666-a815-d9445ee93cb1
name: LOAD_MOSAIC_CDM_APPLICATION_FUNCTION
operation:
  config:
    archive_enabled: true
    archive_path: archive
    extlocation: false
    fieldDelim: ~|~
    fieldEnclosed: '"'
    fileFormatType: File Format Values
    filePattern: ''
    fileType: CSV
    inferschema: false
    insertStrategy: INSERT
    intextstage: true
    postSQL: ''
    preSQL: ''
    recDelim: ''
    replaceinvalidcharacters: false
    skipBlankLines: false
    skipHeader: '1'
    stageName: s3_LOAD_MOSAIC_CDM_APPLICATION_FUNCTION
    stageStorageLocationName: DV2_STG
    stripouterarray: false
    subfolder: ''
    testsEnabled: true
    trimSpace: false
    truncateBefore: true
    usevectscan: false
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ea46d7ed-05ea-4bf7-9b12-4316933ccd6f
          stepCounter: 051954d5-9b2a-4666-a815-d9445ee93cb1
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: APPLICATION_FUNCTION_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 15e46446-9e8f-41ba-97ff-8fbc24dbb2b8
          stepCounter: 051954d5-9b2a-4666-a815-d9445ee93cb1
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: FUNCTION_TYPE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5c34d28a-5d55-4540-8f9c-1959989d3904
          stepCounter: 051954d5-9b2a-4666-a815-d9445ee93cb1
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_BY_USER
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a570a1f7-d87d-485b-bfe2-1ee8fc22a6c3
          stepCounter: 051954d5-9b2a-4666-a815-d9445ee93cb1
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_DATE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 295988ea-1638-4746-a28b-dbfb9b7ce0a6
          stepCounter: 051954d5-9b2a-4666-a815-d9445ee93cb1
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: USER_GROUP_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: fa9b8558-72db-4a45-9029-7583a226fb8a
          stepCounter: 051954d5-9b2a-4666-a815-d9445ee93cb1
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 347c8a20-bcef-4100-b25b-14956609800f
          stepCounter: 051954d5-9b2a-4666-a815-d9445ee93cb1
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences: []
    enabledColumnTestIDs: []
    sourceMapping: []
  name: LOAD_MOSAIC_CDM_APPLICATION_FUNCTION
  overrideSQL: false
  schema: ""
  sqlType: External:::324
  type: sql
  version: 1
type: Node
