fileVersion: 1
id: c3c529f9-4984-4d78-96ae-324cf718a150
name: LOAD_QBYTE_SS_CLIENT_CONFIGURATION
operation:
  database: ""
  deployEnabled: true
  description: ""
  locationName: TARGET
  metadata:
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f822b10e-ec37-4c8f-bb3c-c9e9bd2881d1
          stepCounter: c3c529f9-4984-4d78-96ae-324cf718a150
        config: {}
        dataType: NUMBER(3)
        defaultValue: ""
        description: ""
        name: CLIENT_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 58fa5699-2b64-40a3-98b3-7f1d1e9132af
          stepCounter: c3c529f9-4984-4d78-96ae-324cf718a150
        config: {}
        dataType: VARCHAR(30)
        defaultValue: ""
        description: Identifier to determine the client.
        name: SECTION_NM
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 9c06ffee-cfde-4d95-98c9-72fd7694989f
          stepCounter: c3c529f9-4984-4d78-96ae-324cf718a150
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: The configuration setting name.
        name: SETTING_NM
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 821b8049-9937-4c8d-8bba-8bccb00c23c1
          stepCounter: c3c529f9-4984-4d78-96ae-324cf718a150
        config: {}
        dataType: VARCHAR(300)
        defaultValue: ""
        description: The configuration setting value.
        name: SETTING_VLU
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 544c0bc4-c9fb-43da-af5b-7503874be8ed
          stepCounter: c3c529f9-4984-4d78-96ae-324cf718a150
        config: {}
        dataType: VARCHAR(1000)
        defaultValue: ""
        description: The description of the configuration setting.
        name: SETTING_DESC
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1efc1cdb-751d-469f-8335-7f85b67b6deb
          stepCounter: c3c529f9-4984-4d78-96ae-324cf718a150
        config: {}
        dataType: VARCHAR(30)
        defaultValue: ""
        description: The user who created the record.
        name: CREATE_USER
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 2591f463-a667-4ecb-aa98-a65149af3c69
          stepCounter: c3c529f9-4984-4d78-96ae-324cf718a150
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: The date the record was created.
        name: CREATE_DATE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e9c7d948-0b17-480d-9159-bb5998d92093
          stepCounter: c3c529f9-4984-4d78-96ae-324cf718a150
        config: {}
        dataType: VARCHAR(30)
        defaultValue: ""
        description: The user who last updated the record.
        name: LAST_UPDATE_USER
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5ef182ba-eba6-4987-9f58-e50297747d50
          stepCounter: c3c529f9-4984-4d78-96ae-324cf718a150
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: The date the record was last updated.
        name: LAST_UPDATE_DATE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a7417ab5-ea2f-4700-8ba1-2f448bceb1bf
          stepCounter: c3c529f9-4984-4d78-96ae-324cf718a150
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 79783420-6ed8-44c1-9c91-40673407f084
          stepCounter: c3c529f9-4984-4d78-96ae-324cf718a150
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
  name: LOAD_QBYTE_SS_CLIENT_CONFIGURATION
  schema: ""
  sqlType: Source
  type: sourceInput
  version: 1
type: Node
