fileVersion: 1
id: 18c8266f-115a-4d16-8f28-6c10d1084ceb
name: ODS_QBYTE_IMAGING_CONFIGS
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5d70f5fc-3f67-4067-865a-69603622f4d3
          stepCounter: 18c8266f-115a-4d16-8f28-6c10d1084ceb
        config: {}
        dataType: VARCHAR(40)
        defaultValue: ""
        description: The document type.
        isBusinessKey: true
        name: DOCUMENT_TYPE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 3a77503c-69a7-4efc-85fe-001762d36af5
                stepCounter: 23a2cea6-ea61-4672-89b1-6744ea8e5045
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0841e84d-12f4-4e24-851c-f09616f38759
          stepCounter: 18c8266f-115a-4d16-8f28-6c10d1084ceb
        config: {}
        dataType: VARCHAR(40)
        defaultValue: ""
        description: The dde server.
        isChangeTracking: true
        name: DDE_SERVER
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 62329d79-2bf4-444e-bb88-c629cc754a7a
                stepCounter: 23a2cea6-ea61-4672-89b1-6744ea8e5045
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a2586de0-075d-4fb7-b0de-81a80d76728d
          stepCounter: 18c8266f-115a-4d16-8f28-6c10d1084ceb
        config: {}
        dataType: VARCHAR(40)
        defaultValue: ""
        description: The dde topic.
        isChangeTracking: true
        name: DDE_TOPIC
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 76079167-0a1b-42f1-9081-24763fd9bf04
                stepCounter: 23a2cea6-ea61-4672-89b1-6744ea8e5045
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 9e214019-880c-4528-ae8d-cef5b6ecbc98
          stepCounter: 18c8266f-115a-4d16-8f28-6c10d1084ceb
        config: {}
        dataType: NUMBER(10)
        defaultValue: ""
        description: The dde timeout.
        isChangeTracking: true
        name: DDE_TIMEOUT
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 1f18686f-0e04-4a1d-b592-750a010b48a0
                stepCounter: 23a2cea6-ea61-4672-89b1-6744ea8e5045
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: fe7e6570-c960-4d76-b861-4196545a9479
          stepCounter: 18c8266f-115a-4d16-8f28-6c10d1084ceb
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: The dde command.
        isChangeTracking: true
        name: DDE_COMMAND
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 5282bb34-eb54-4ab0-b9b6-852e872b9c37
                stepCounter: 23a2cea6-ea61-4672-89b1-6744ea8e5045
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0d7391c6-2cdc-4add-a92f-5032b55f6e01
          stepCounter: 18c8266f-115a-4d16-8f28-6c10d1084ceb
        config: {}
        dataType: VARCHAR(40)
        defaultValue: ""
        description: The label on the button.
        isChangeTracking: true
        name: BUTTON_HINT_LABEL
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: daee6ea7-acd3-4d43-b755-21d3bd3e0f5d
                stepCounter: 23a2cea6-ea61-4672-89b1-6744ea8e5045
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1199a753-2f5b-4738-a19d-1bfb9921c4a3
          stepCounter: 18c8266f-115a-4d16-8f28-6c10d1084ceb
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: Virtual directory where the imaging software is stored.
        isChangeTracking: true
        name: WEB_DIRECTORY
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 3336a574-1103-420b-af11-8b4ecb0e605c
                stepCounter: 23a2cea6-ea61-4672-89b1-6744ea8e5045
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0d0b4bcd-eb11-4db7-987f-9b54c85a24ba
          stepCounter: 18c8266f-115a-4d16-8f28-6c10d1084ceb
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: The starting web page of the imaging software.
        isChangeTracking: true
        name: WEB_PAGE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 2b9fa6f3-c528-4d83-a82f-408fecb026e8
                stepCounter: 23a2cea6-ea61-4672-89b1-6744ea8e5045
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8816500e-63cf-445d-b4ea-08522bb262af
          stepCounter: 18c8266f-115a-4d16-8f28-6c10d1084ceb
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: To store specifics of web page address that relates to the way imaged documents are stored.
        isChangeTracking: true
        name: WEB_COMMAND
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 51c64934-8d03-49c5-b30d-f071e5a84ec4
                stepCounter: 23a2cea6-ea61-4672-89b1-6744ea8e5045
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8e17308f-c2b4-48b2-ad4f-aea1385776d2
          stepCounter: 18c8266f-115a-4d16-8f28-6c10d1084ceb
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 8198c316-b72a-4ec5-88d8-e5e098ef4c87
                stepCounter: 23a2cea6-ea61-4672-89b1-6744ea8e5045
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5d74fa5b-af1b-4e13-9db4-44fa9b7d3719
          stepCounter: 18c8266f-115a-4d16-8f28-6c10d1084ceb
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 734eee0a-4fc1-408a-a4ba-a9ee633e7517
                stepCounter: 23a2cea6-ea61-4672-89b1-6744ea8e5045
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 00b31dbe-cf44-4186-ac59-91a119724735
          stepCounter: 18c8266f-115a-4d16-8f28-6c10d1084ceb
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: Flag field to identify Deleted record
        name: DSS_DELETE_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c9342b1a-ec06-4a98-a453-0dcb9a747214
          stepCounter: 18c8266f-115a-4d16-8f28-6c10d1084ceb
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Records time when record was set to Delete by the Load process
        name: DSS_DELETE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ea24bf02-1ca3-431c-be71-be9991afe337
          stepCounter: 18c8266f-115a-4d16-8f28-6c10d1084ceb
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Datetime a business key was started.
        isSystemStartDate: true
        name: DSS_START_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a77c41f8-a4a9-475a-9a36-ad8f701ac58a
          stepCounter: 18c8266f-115a-4d16-8f28-6c10d1084ceb
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Datetime a business key was retired.
        isSystemEndDate: true
        name: DSS_END_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 9eb272c2-8374-4dde-ad0b-708d0a64c8ea
          stepCounter: 18c8266f-115a-4d16-8f28-6c10d1084ceb
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: Flag to indicate the current (latest) version of a business key.
        isSystemCurrentFlag: true
        name: DSS_CURRENT_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d89e225b-8aac-4c35-966a-8043df94af00
          stepCounter: 18c8266f-115a-4d16-8f28-6c10d1084ceb
        config: {}
        dataType: INTEGER
        defaultValue: ""
        description: Version number of a business key.
        isSystemVersion: true
        name: DSS_VERSION
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: bd475ef7-9dc8-443f-b36f-866cfa9ec1c2
          stepCounter: 18c8266f-115a-4d16-8f28-6c10d1084ceb
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was created in the data warehouse.
        isSystemCreateDate: true
        name: DSS_CREATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 2157d145-023d-453c-86f3-27c1f289ceeb
          stepCounter: 18c8266f-115a-4d16-8f28-6c10d1084ceb
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was updated in the data warehouse.
        isSystemUpdateDate: true
        name: DSS_UPDATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          LOAD_QBYTE_IMAGING_CONFIGS: 23a2cea6-ea61-4672-89b1-6744ea8e5045
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: TARGET
            nodeName: LOAD_QBYTE_IMAGING_CONFIGS
        join:
          joinCondition: FROM {{ ref('TARGET','LOAD_QBYTE_IMAGING_CONFIGS') }} LOAD_QBYTE_IMAGING_CONFIGS
        name: ODS_QBYTE_IMAGING_CONFIGS
        noLinkRefs: []
  name: ODS_QBYTE_IMAGING_CONFIGS
  overrideSQL: false
  schema: ""
  sqlType: '38'
  type: sql
  version: 1
type: Node
