fileVersion: 1
id: 003c5f80-3bb1-49a4-a31f-19783f461114
name: ODS_XSPOC_TBLGRAPHVIEWSETTINGS
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 876f5f2a-cc34-45d9-8e4a-aceb1be8beb9
          stepCounter: 003c5f80-3bb1-49a4-a31f-19783f461114
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: VIEWID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 3207cafc-ac10-449a-97f0-67c95a9d7e25
                stepCounter: 710e7d0b-0184-47ab-a677-3d1850dfd1c5
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1d66f742-4229-4b33-acb3-b15c9d31de16
          stepCounter: 003c5f80-3bb1-49a4-a31f-19783f461114
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: PROPERTY
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: b59aee18-753a-4356-947f-8304cb7a40c6
                stepCounter: 710e7d0b-0184-47ab-a677-3d1850dfd1c5
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 32ea940c-6ba2-4819-a713-da6b11bc6b12
          stepCounter: 003c5f80-3bb1-49a4-a31f-19783f461114
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: VALUE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 11a7e40c-32fd-4373-b76d-4f943d247888
                stepCounter: 710e7d0b-0184-47ab-a677-3d1850dfd1c5
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: fc1be1a8-8194-43e7-82cd-5fab048ea0dd
          stepCounter: 003c5f80-3bb1-49a4-a31f-19783f461114
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: a7c16113-bd82-43fd-bcbd-1198ab442c5b
                stepCounter: 710e7d0b-0184-47ab-a677-3d1850dfd1c5
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ae394418-7cdc-4e81-b8c0-b0d4c91b233b
          stepCounter: 003c5f80-3bb1-49a4-a31f-19783f461114
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: fb6911fc-db10-4e28-8824-0778745238f2
                stepCounter: 710e7d0b-0184-47ab-a677-3d1850dfd1c5
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 56fa10b3-b6a8-40a0-b3c5-0b5ae2f6bc94
          stepCounter: 003c5f80-3bb1-49a4-a31f-19783f461114
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: Flag field to identify Deleted record
        name: DSS_DELETE_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ec189cad-964b-4862-91dd-3b005a1909de
          stepCounter: 003c5f80-3bb1-49a4-a31f-19783f461114
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Records time when record was set to Delete by the Load process
        name: DSS_DELETE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 914f1322-b7b7-4603-8016-28c41dbcff74
          stepCounter: 003c5f80-3bb1-49a4-a31f-19783f461114
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Datetime a business key was started.
        isSystemStartDate: true
        name: DSS_START_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1dd3052c-0a94-40e9-8b2f-1d64f09a520b
          stepCounter: 003c5f80-3bb1-49a4-a31f-19783f461114
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Datetime a business key was retired.
        isSystemEndDate: true
        name: DSS_END_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7bb31598-5815-4e0c-b25f-5dcb8cc64df3
          stepCounter: 003c5f80-3bb1-49a4-a31f-19783f461114
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: Flag to indicate the current (latest) version of a business key.
        isSystemCurrentFlag: true
        name: DSS_CURRENT_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7e6bac48-5558-4257-b9be-811d0b3e075d
          stepCounter: 003c5f80-3bb1-49a4-a31f-19783f461114
        config: {}
        dataType: INTEGER
        defaultValue: ""
        description: Version number of a business key.
        isSystemVersion: true
        name: DSS_VERSION
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e7e46fc0-a199-4ae0-b3b6-3c3716815f88
          stepCounter: 003c5f80-3bb1-49a4-a31f-19783f461114
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was created in the data warehouse.
        isSystemCreateDate: true
        name: DSS_CREATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ae30785f-165f-4bef-b3ba-a22ea350f120
          stepCounter: 003c5f80-3bb1-49a4-a31f-19783f461114
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was updated in the data warehouse.
        isSystemUpdateDate: true
        name: DSS_UPDATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          LOAD_XSPOC_TBLGRAPHVIEWSETTINGS: 710e7d0b-0184-47ab-a677-3d1850dfd1c5
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: TARGET
            nodeName: LOAD_XSPOC_TBLGRAPHVIEWSETTINGS
        join:
          joinCondition: FROM {{ ref('TARGET','LOAD_XSPOC_TBLGRAPHVIEWSETTINGS') }} LOAD_XSPOC_TBLGRAPHVIEWSETTINGS
        name: ODS_XSPOC_TBLGRAPHVIEWSETTINGS
        noLinkRefs: []
  name: ODS_XSPOC_TBLGRAPHVIEWSETTINGS
  overrideSQL: false
  schema: ""
  sqlType: persistentStage
  type: sql
  version: 1
type: Node
