fileVersion: 1
id: 10d0c19c-40fd-4a8e-8484-8c43bd0d8eee
name: ODS_QBYTE_SMCONFIGURATION
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 674f4f8e-4491-4c8c-a089-9c26ba7c48c8
          stepCounter: 10d0c19c-40fd-4a8e-8484-8c43bd0d8eee
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: ATTRIBUTE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: cfac1424-3d7b-42e3-8e4c-060fa753310f
                stepCounter: 9398afab-340a-4b09-b737-edb0a999b1c5
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e1d13a83-a5a4-4896-80ca-47389992254d
          stepCounter: 10d0c19c-40fd-4a8e-8484-8c43bd0d8eee
        config: {}
        dataType: VARCHAR(512)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: VALUE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 6be9d8a6-ba19-490c-ac61-a70096fe0a56
                stepCounter: 9398afab-340a-4b09-b737-edb0a999b1c5
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 31a4cb5c-d294-4d2b-afbb-97b8e55ea502
          stepCounter: 10d0c19c-40fd-4a8e-8484-8c43bd0d8eee
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 8920b1b6-47b7-41a7-9d68-b7b9cc60c573
                stepCounter: 9398afab-340a-4b09-b737-edb0a999b1c5
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8264b2d9-c031-4a2b-92c7-f885f3f569b6
          stepCounter: 10d0c19c-40fd-4a8e-8484-8c43bd0d8eee
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: fa555704-437d-465b-81a0-c4ddc4a5ac8d
                stepCounter: 9398afab-340a-4b09-b737-edb0a999b1c5
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e4886b97-e2a8-42f8-bcda-52999059570a
          stepCounter: 10d0c19c-40fd-4a8e-8484-8c43bd0d8eee
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: Flag field to identify Deleted record
        name: DSS_DELETE_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e034b4a4-290c-4f4e-865b-68afa7b000dd
          stepCounter: 10d0c19c-40fd-4a8e-8484-8c43bd0d8eee
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Records time when record was set to Delete by the Load process
        name: DSS_DELETE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 149603a1-eff3-4eb9-bcf1-cd07152940fa
          stepCounter: 10d0c19c-40fd-4a8e-8484-8c43bd0d8eee
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Datetime a business key was started.
        isSystemStartDate: true
        name: DSS_START_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 24fabc2b-5816-4b44-931c-da05fe1bc64e
          stepCounter: 10d0c19c-40fd-4a8e-8484-8c43bd0d8eee
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Datetime a business key was retired.
        isSystemEndDate: true
        name: DSS_END_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: dfdccc0e-b39c-4e53-b083-35b1f160837d
          stepCounter: 10d0c19c-40fd-4a8e-8484-8c43bd0d8eee
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: Flag to indicate the current (latest) version of a business key.
        isSystemCurrentFlag: true
        name: DSS_CURRENT_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e3f5e62f-8532-482d-bf57-3c7c24db5963
          stepCounter: 10d0c19c-40fd-4a8e-8484-8c43bd0d8eee
        config: {}
        dataType: INTEGER
        defaultValue: ""
        description: Version number of a business key.
        isSystemVersion: true
        name: DSS_VERSION
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 76ad726f-fe5b-4128-8234-b9971cd73868
          stepCounter: 10d0c19c-40fd-4a8e-8484-8c43bd0d8eee
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was created in the data warehouse.
        isSystemCreateDate: true
        name: DSS_CREATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 23a11ee0-9bed-4018-b064-205b1c4351c1
          stepCounter: 10d0c19c-40fd-4a8e-8484-8c43bd0d8eee
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was updated in the data warehouse.
        isSystemUpdateDate: true
        name: DSS_UPDATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          LOAD_QBYTE_SMCONFIGURATION: 9398afab-340a-4b09-b737-edb0a999b1c5
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: TARGET
            nodeName: LOAD_QBYTE_SMCONFIGURATION
        join:
          joinCondition: FROM {{ ref('TARGET','LOAD_QBYTE_SMCONFIGURATION') }} LOAD_QBYTE_SMCONFIGURATION
        name: ODS_QBYTE_SMCONFIGURATION
        noLinkRefs: []
  name: ODS_QBYTE_SMCONFIGURATION
  overrideSQL: false
  schema: ""
  sqlType: persistentStage
  type: sql
  version: 1
type: Node
