fileVersion: 1
id: 2ce66cf2-34db-4a8b-af59-62d8b2ddb0b3
name: ODS_QBYTE_IMAGING_CONFIGS
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 38757a4f-86ec-451b-a179-04dbe655ba3b
          stepCounter: 2ce66cf2-34db-4a8b-af59-62d8b2ddb0b3
        config: {}
        dataType: VARCHAR(40)
        defaultValue: ""
        description: The document type.
        isBusinessKey: true
        name: DOCUMENT_TYPE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 54d1c7ba-a907-4e79-9780-8ca02c886b84
                stepCounter: daba6e0c-0f7d-4f98-8ef3-ca45ae884987
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 684199cc-4ead-41e0-a09c-8f9c1913dc62
          stepCounter: 2ce66cf2-34db-4a8b-af59-62d8b2ddb0b3
        config: {}
        dataType: VARCHAR(40)
        defaultValue: ""
        description: The dde server.
        isChangeTracking: true
        name: DDE_SERVER
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 4f5456ed-94ef-4101-9132-aecd5246eeb2
                stepCounter: daba6e0c-0f7d-4f98-8ef3-ca45ae884987
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e9568867-f23e-4a95-b987-f4007c2966c5
          stepCounter: 2ce66cf2-34db-4a8b-af59-62d8b2ddb0b3
        config: {}
        dataType: VARCHAR(40)
        defaultValue: ""
        description: The dde topic.
        isChangeTracking: true
        name: DDE_TOPIC
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: c1cf04fd-f327-4369-b191-736c3806c947
                stepCounter: daba6e0c-0f7d-4f98-8ef3-ca45ae884987
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3dfb6b1c-dcd5-4d56-a0e2-84387a0a0e5d
          stepCounter: 2ce66cf2-34db-4a8b-af59-62d8b2ddb0b3
        config: {}
        dataType: NUMBER(10)
        defaultValue: ""
        description: The dde timeout.
        isChangeTracking: true
        name: DDE_TIMEOUT
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 0d5d1fff-1145-4211-9455-aa00bd59fa4d
                stepCounter: daba6e0c-0f7d-4f98-8ef3-ca45ae884987
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 79a6a99e-a38d-4a3c-b436-177dc27523ad
          stepCounter: 2ce66cf2-34db-4a8b-af59-62d8b2ddb0b3
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: The dde command.
        isChangeTracking: true
        name: DDE_COMMAND
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 6c271133-b7a2-447d-8eec-430771bdc941
                stepCounter: daba6e0c-0f7d-4f98-8ef3-ca45ae884987
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 046e659f-9ce6-4512-a4f7-72580b6cdd3b
          stepCounter: 2ce66cf2-34db-4a8b-af59-62d8b2ddb0b3
        config: {}
        dataType: VARCHAR(40)
        defaultValue: ""
        description: The label on the button.
        isChangeTracking: true
        name: BUTTON_HINT_LABEL
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 1c18482e-ba58-4b3a-a59c-a7883f65c01b
                stepCounter: daba6e0c-0f7d-4f98-8ef3-ca45ae884987
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6d9a3d11-02e3-48e9-bef0-8760ebc07490
          stepCounter: 2ce66cf2-34db-4a8b-af59-62d8b2ddb0b3
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: Virtual directory where the imaging software is stored.
        isChangeTracking: true
        name: WEB_DIRECTORY
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: cb43b277-3978-437b-bd0e-31ef896cb49a
                stepCounter: daba6e0c-0f7d-4f98-8ef3-ca45ae884987
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: eaa407ef-e687-407f-b596-43eeaff9b4a5
          stepCounter: 2ce66cf2-34db-4a8b-af59-62d8b2ddb0b3
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: The starting web page of the imaging software.
        isChangeTracking: true
        name: WEB_PAGE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 2fca28a9-4692-4a7c-b369-9ea3e1379668
                stepCounter: daba6e0c-0f7d-4f98-8ef3-ca45ae884987
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e9dd302a-ce23-477d-b0f3-6b0390968255
          stepCounter: 2ce66cf2-34db-4a8b-af59-62d8b2ddb0b3
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: To store specifics of web page address that relates to the way imaged documents are stored.
        isChangeTracking: true
        name: WEB_COMMAND
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: a4141f82-54e4-4dc3-a1b7-6d4742b5c57f
                stepCounter: daba6e0c-0f7d-4f98-8ef3-ca45ae884987
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5d05603e-fa38-4d05-ac4d-06dbb6059066
          stepCounter: 2ce66cf2-34db-4a8b-af59-62d8b2ddb0b3
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 44d24fba-2b91-4db4-96a0-24029b391617
                stepCounter: daba6e0c-0f7d-4f98-8ef3-ca45ae884987
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 07b1ac88-744d-4827-939d-f14e07ac91ca
          stepCounter: 2ce66cf2-34db-4a8b-af59-62d8b2ddb0b3
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 7c5481f8-3c13-4994-8462-06030901ff17
                stepCounter: daba6e0c-0f7d-4f98-8ef3-ca45ae884987
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f3a6a8d3-fe2c-464a-8bf0-4f25d93cc3e8
          stepCounter: 2ce66cf2-34db-4a8b-af59-62d8b2ddb0b3
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: Flag field to identify Deleted record
        name: DSS_DELETE_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 68667018-1988-4dc1-9940-bf2c819a541d
          stepCounter: 2ce66cf2-34db-4a8b-af59-62d8b2ddb0b3
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Records time when record was set to Delete by the Load process
        name: DSS_DELETE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 14d24749-33b5-4f34-b19e-9d1ae1572d81
          stepCounter: 2ce66cf2-34db-4a8b-af59-62d8b2ddb0b3
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Datetime a business key was started.
        isSystemStartDate: true
        name: DSS_START_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0d5eff0a-a5f1-4fdd-8c32-952991684201
          stepCounter: 2ce66cf2-34db-4a8b-af59-62d8b2ddb0b3
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Datetime a business key was retired.
        isSystemEndDate: true
        name: DSS_END_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 592fcded-5cb6-4f7d-96b5-dad9418b0fff
          stepCounter: 2ce66cf2-34db-4a8b-af59-62d8b2ddb0b3
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: Flag to indicate the current (latest) version of a business key.
        isSystemCurrentFlag: true
        name: DSS_CURRENT_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 117e0f3e-56a9-4e97-9181-b1efc9dde116
          stepCounter: 2ce66cf2-34db-4a8b-af59-62d8b2ddb0b3
        config: {}
        dataType: INTEGER
        defaultValue: ""
        description: Version number of a business key.
        isSystemVersion: true
        name: DSS_VERSION
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a4e30f3c-627a-43ce-bf8a-293aacf555e0
          stepCounter: 2ce66cf2-34db-4a8b-af59-62d8b2ddb0b3
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was created in the data warehouse.
        isSystemCreateDate: true
        name: DSS_CREATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6ae64ddd-2193-4eff-902e-0f3bf7baf90a
          stepCounter: 2ce66cf2-34db-4a8b-af59-62d8b2ddb0b3
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was updated in the data warehouse.
        isSystemUpdateDate: true
        name: DSS_UPDATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          LOAD_QBYTE_IMAGING_CONFIGS: daba6e0c-0f7d-4f98-8ef3-ca45ae884987
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: TARGET
            nodeName: LOAD_QBYTE_IMAGING_CONFIGS
        join:
          joinCondition: FROM {{ ref('TARGET','LOAD_QBYTE_IMAGING_CONFIGS') }} LOAD_QBYTE_IMAGING_CONFIGS
        name: ODS_QBYTE_IMAGING_CONFIGS
        noLinkRefs: []
  name: ODS_QBYTE_IMAGING_CONFIGS
  overrideSQL: false
  schema: ""
  sqlType: persistentStage
  type: sql
  version: 1
type: Node
