fileVersion: 1
id: 23a2cea6-ea61-4672-89b1-6744ea8e5045
name: LOAD_QBYTE_IMAGING_CONFIGS
operation:
  config:
    archive_enabled: true
    archive_path: archive
    extlocation: false
    fieldDelim: ~|~
    fieldEnclosed: '"'
    fileFormatType: File Format Values
    filePattern: ''
    fileType: CSV
    inferschema: false
    insertStrategy: INSERT
    intextstage: true
    postSQL: ''
    preSQL: ''
    recDelim: ''
    replaceinvalidcharacters: false
    skipBlankLines: false
    skipHeader: '1'
    stageName: s3_LOAD_QBYTE_IMAGING_CONFIGS
    stageStorageLocationName: DV2_STG
    stripouterarray: false
    subfolder: ''
    testsEnabled: true
    trimSpace: false
    truncateBefore: true
    usevectscan: false
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3a77503c-69a7-4efc-85fe-001762d36af5
          stepCounter: 23a2cea6-ea61-4672-89b1-6744ea8e5045
        config: {}
        dataType: VARCHAR(40)
        defaultValue: ""
        description: The document type.
        name: DOCUMENT_TYPE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 62329d79-2bf4-444e-bb88-c629cc754a7a
          stepCounter: 23a2cea6-ea61-4672-89b1-6744ea8e5045
        config: {}
        dataType: VARCHAR(40)
        defaultValue: ""
        description: The dde server.
        name: DDE_SERVER
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 76079167-0a1b-42f1-9081-24763fd9bf04
          stepCounter: 23a2cea6-ea61-4672-89b1-6744ea8e5045
        config: {}
        dataType: VARCHAR(40)
        defaultValue: ""
        description: The dde topic.
        name: DDE_TOPIC
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1f18686f-0e04-4a1d-b592-750a010b48a0
          stepCounter: 23a2cea6-ea61-4672-89b1-6744ea8e5045
        config: {}
        dataType: NUMBER(10)
        defaultValue: ""
        description: The dde timeout.
        name: DDE_TIMEOUT
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5282bb34-eb54-4ab0-b9b6-852e872b9c37
          stepCounter: 23a2cea6-ea61-4672-89b1-6744ea8e5045
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: The dde command.
        name: DDE_COMMAND
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: daee6ea7-acd3-4d43-b755-21d3bd3e0f5d
          stepCounter: 23a2cea6-ea61-4672-89b1-6744ea8e5045
        config: {}
        dataType: VARCHAR(40)
        defaultValue: ""
        description: The label on the button.
        name: BUTTON_HINT_LABEL
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3336a574-1103-420b-af11-8b4ecb0e605c
          stepCounter: 23a2cea6-ea61-4672-89b1-6744ea8e5045
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: Virtual directory where the imaging software is stored.
        name: WEB_DIRECTORY
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 2b9fa6f3-c528-4d83-a82f-408fecb026e8
          stepCounter: 23a2cea6-ea61-4672-89b1-6744ea8e5045
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: The starting web page of the imaging software.
        name: WEB_PAGE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 51c64934-8d03-49c5-b30d-f071e5a84ec4
          stepCounter: 23a2cea6-ea61-4672-89b1-6744ea8e5045
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: To store specifics of web page address that relates to the way imaged documents are stored.
        name: WEB_COMMAND
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8198c316-b72a-4ec5-88d8-e5e098ef4c87
          stepCounter: 23a2cea6-ea61-4672-89b1-6744ea8e5045
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 734eee0a-4fc1-408a-a4ba-a9ee633e7517
          stepCounter: 23a2cea6-ea61-4672-89b1-6744ea8e5045
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences: []
    enabledColumnTestIDs: []
    sourceMapping: []
  name: LOAD_QBYTE_IMAGING_CONFIGS
  overrideSQL: false
  schema: ""
  sqlType: External:::324
  type: sql
  version: 1
type: Node
