fileVersion: 1
id: bd62feec-5e01-498c-a1e9-53488ce3c424
name: LOAD_XSPOC_TBLAPPLICATIONPARAMSTANDARDTYPES
operation:
  database: ""
  deployEnabled: true
  description: ""
  locationName: TARGET
  metadata:
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0bf5ced8-a3fd-40da-ba14-63b4079b1b45
          stepCounter: bd62feec-5e01-498c-a1e9-53488ce3c424
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: APPLICATIONID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: fa27f98a-713b-45a3-b336-95b78e679cd8
          stepCounter: bd62feec-5e01-498c-a1e9-53488ce3c424
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: PARAMSTANDARDTYPE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 73a1864c-9c65-4621-919a-a7696580272e
          stepCounter: bd62feec-5e01-498c-a1e9-53488ce3c424
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: ISUSEDFORANALYSIS
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b7db4c35-6512-4240-896b-65ad88ea3c07
          stepCounter: bd62feec-5e01-498c-a1e9-53488ce3c424
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: DISPLAYORDER
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b96fd291-6aaf-49e2-914c-5c21767dd7c6
          stepCounter: bd62feec-5e01-498c-a1e9-53488ce3c424
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: ISREQUIREDFORANALYSIS
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 95da48c9-b467-49ee-9682-a34379c457f5
          stepCounter: bd62feec-5e01-498c-a1e9-53488ce3c424
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: ALLOWSNOTE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 210ce95c-5f13-41d9-a07c-ade0e13569a0
          stepCounter: bd62feec-5e01-498c-a1e9-53488ce3c424
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: cd70bdd3-5721-4dbd-ab21-077d01ba5867
          stepCounter: bd62feec-5e01-498c-a1e9-53488ce3c424
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
  name: LOAD_XSPOC_TBLAPPLICATIONPARAMSTANDARDTYPES
  schema: ""
  sqlType: Source
  type: sourceInput
  version: 1
type: Node
