fileVersion: 1
id: 1ad8b3da-1fe4-4ddf-a7cd-6c9ae89bbe49
name: ODS_XSPOC_TBLFAILUREAPPLICATIONSCAUSES
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: fe2c5926-c92a-4755-8e4f-55bca54e2d23
          stepCounter: 1ad8b3da-1fe4-4ddf-a7cd-6c9ae89bbe49
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: ID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 4ffbb151-1132-4110-b0aa-07e38e5704c3
                stepCounter: 18089a79-9e38-400a-9ce5-c2c39d521a98
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: bf0dd4d6-2aef-4394-a002-a410baadb2eb
          stepCounter: 1ad8b3da-1fe4-4ddf-a7cd-6c9ae89bbe49
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: APPLICATIONID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: c3b8a372-6496-487f-ac0e-ff4c4dc692f4
                stepCounter: 18089a79-9e38-400a-9ce5-c2c39d521a98
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 2a56e74f-30a0-4d27-a00e-a43f18d949d5
          stepCounter: 1ad8b3da-1fe4-4ddf-a7cd-6c9ae89bbe49
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: CAUSEID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: e8588c56-725c-4d1b-88b7-7284d6f78e41
                stepCounter: 18089a79-9e38-400a-9ce5-c2c39d521a98
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 691ddd28-8957-49ad-9c99-c51f165b2923
          stepCounter: 1ad8b3da-1fe4-4ddf-a7cd-6c9ae89bbe49
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 68caeaec-10fd-4ffe-843e-ea9dcdef7156
                stepCounter: 18089a79-9e38-400a-9ce5-c2c39d521a98
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e264d267-6c1c-4252-a285-27a0b0fa568d
          stepCounter: 1ad8b3da-1fe4-4ddf-a7cd-6c9ae89bbe49
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: ec92d1e7-7358-4816-9a20-53298d8863ef
                stepCounter: 18089a79-9e38-400a-9ce5-c2c39d521a98
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: bd326853-a3f8-41f6-b356-c9940974f9ed
          stepCounter: 1ad8b3da-1fe4-4ddf-a7cd-6c9ae89bbe49
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: Flag field to identify Deleted record
        name: DSS_DELETE_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7a5fc97f-a6c5-498d-b77b-ae4340c35159
          stepCounter: 1ad8b3da-1fe4-4ddf-a7cd-6c9ae89bbe49
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Records time when record was set to Delete by the Load process
        name: DSS_DELETE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7568ff5d-1481-4f42-9a83-a8fcdbad9e17
          stepCounter: 1ad8b3da-1fe4-4ddf-a7cd-6c9ae89bbe49
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Datetime a business key was started.
        isSystemStartDate: true
        name: DSS_START_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 94f3f509-5549-4bba-aff7-5c47a30d0411
          stepCounter: 1ad8b3da-1fe4-4ddf-a7cd-6c9ae89bbe49
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Datetime a business key was retired.
        isSystemEndDate: true
        name: DSS_END_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a6839f0d-36de-405a-a99e-283640b3ae30
          stepCounter: 1ad8b3da-1fe4-4ddf-a7cd-6c9ae89bbe49
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: Flag to indicate the current (latest) version of a business key.
        isSystemCurrentFlag: true
        name: DSS_CURRENT_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 47f0cdc1-9e7a-456d-9e17-4d6708901e5f
          stepCounter: 1ad8b3da-1fe4-4ddf-a7cd-6c9ae89bbe49
        config: {}
        dataType: INTEGER
        defaultValue: ""
        description: Version number of a business key.
        isSystemVersion: true
        name: DSS_VERSION
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: add85c88-65be-4642-921d-9dcb0fd7c7ff
          stepCounter: 1ad8b3da-1fe4-4ddf-a7cd-6c9ae89bbe49
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was created in the data warehouse.
        isSystemCreateDate: true
        name: DSS_CREATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 46e65c76-6c2c-403f-af37-cfd2027f48e2
          stepCounter: 1ad8b3da-1fe4-4ddf-a7cd-6c9ae89bbe49
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was updated in the data warehouse.
        isSystemUpdateDate: true
        name: DSS_UPDATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          LOAD_XSPOC_TBLFAILUREAPPLICATIONSCAUSES: 18089a79-9e38-400a-9ce5-c2c39d521a98
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: TARGET
            nodeName: LOAD_XSPOC_TBLFAILUREAPPLICATIONSCAUSES
        join:
          joinCondition: FROM {{ ref('TARGET','LOAD_XSPOC_TBLFAILUREAPPLICATIONSCAUSES') }} LOAD_XSPOC_TBLFAILUREAPPLICATIONSCAUSES
        name: ODS_XSPOC_TBLFAILUREAPPLICATIONSCAUSES
        noLinkRefs: []
  name: ODS_XSPOC_TBLFAILUREAPPLICATIONSCAUSES
  overrideSQL: false
  schema: ""
  sqlType: '38'
  type: sql
  version: 1
type: Node
