fileVersion: 1
id: 57b46c18-7fee-45b3-90a8-c39225f6e49e
name: LOAD_XSPOC_TBLALARMCONFIGBYPOCTYPE
operation:
  database: ""
  deployEnabled: true
  description: ""
  locationName: TARGET
  metadata:
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f5b6303d-e6b8-4d81-ac78-39fd16c55929
          stepCounter: 57b46c18-7fee-45b3-90a8-c39225f6e49e
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: POCTYPE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3e803fa7-e782-43f4-9b1c-25763e4b478a
          stepCounter: 57b46c18-7fee-45b3-90a8-c39225f6e49e
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: REGISTER
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7cdeb566-6b4a-476c-b7f0-c3d55caad38c
          stepCounter: 57b46c18-7fee-45b3-90a8-c39225f6e49e
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: BIT
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 63564d3b-4001-43e7-83c8-1ad6f7c76f07
          stepCounter: 57b46c18-7fee-45b3-90a8-c39225f6e49e
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        name: DESCRIPTION
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d848d58c-1858-4243-abdc-8761d97e9bb7
          stepCounter: 57b46c18-7fee-45b3-90a8-c39225f6e49e
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: PHRASEID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: da54258c-8709-4842-b037-d3ac4ae1b57c
          stepCounter: 57b46c18-7fee-45b3-90a8-c39225f6e49e
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: PRIORITY
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f11a4f87-2080-4ede-98a2-9bb801b7b817
          stepCounter: 57b46c18-7fee-45b3-90a8-c39225f6e49e
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: CALLOUTENABLED
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8d40099e-2a1a-4f01-98d3-4bae9fbb90b3
          stepCounter: 57b46c18-7fee-45b3-90a8-c39225f6e49e
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: ENABLED
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5985a2bb-0a78-4401-b958-03dc62b1e3c5
          stepCounter: 57b46c18-7fee-45b3-90a8-c39225f6e49e
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: NORMALSTATE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 2128cd30-a0fd-4b18-8136-9bd17e3fbf4b
          stepCounter: 57b46c18-7fee-45b3-90a8-c39225f6e49e
        config: {}
        dataType: FLOAT
        defaultValue: ""
        description: ""
        name: LOLIMIT
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b479ee1c-02a4-469a-b996-3b39b954dbb5
          stepCounter: 57b46c18-7fee-45b3-90a8-c39225f6e49e
        config: {}
        dataType: FLOAT
        defaultValue: ""
        description: ""
        name: HILIMIT
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: dbcf9dc6-4af3-4921-8b35-5f5eb767ca45
          stepCounter: 57b46c18-7fee-45b3-90a8-c39225f6e49e
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: LOCKED
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 85b2e6e9-3cbc-4e00-8084-2db80b800d2a
          stepCounter: 57b46c18-7fee-45b3-90a8-c39225f6e49e
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: ALARMACTION
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 97d8b4d2-4fc1-4a57-9bf3-d3cbd61ac46a
          stepCounter: 57b46c18-7fee-45b3-90a8-c39225f6e49e
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e0dab011-1f7a-49ca-93d5-5abe408835ce
          stepCounter: 57b46c18-7fee-45b3-90a8-c39225f6e49e
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
  name: LOAD_XSPOC_TBLALARMCONFIGBYPOCTYPE
  schema: ""
  sqlType: Source
  type: sourceInput
  version: 1
type: Node
