fileVersion: 1
id: a81ba1f1-3139-4dad-a9e4-65448f1a7cb7
name: LOAD_MOSAIC_CDM_APPLICATION_FUNCTION
operation:
  database: ""
  deployEnabled: true
  description: ""
  locationName: TARGET
  metadata:
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e7a29c7e-7462-4aa6-9068-e87b8115cab3
          stepCounter: a81ba1f1-3139-4dad-a9e4-65448f1a7cb7
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: APPLICATION_FUNCTION_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5cbba447-c578-45f9-b305-6fac12bd9a47
          stepCounter: a81ba1f1-3139-4dad-a9e4-65448f1a7cb7
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: FUNCTION_TYPE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 2f215e58-e0b2-4007-8c1e-990e76d41bb1
          stepCounter: a81ba1f1-3139-4dad-a9e4-65448f1a7cb7
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_BY_USER
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 54016f25-d4a7-492b-b314-323e713e852b
          stepCounter: a81ba1f1-3139-4dad-a9e4-65448f1a7cb7
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_DATE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: aff1b115-c011-4249-a4ee-1523e4a7db0a
          stepCounter: a81ba1f1-3139-4dad-a9e4-65448f1a7cb7
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: USER_GROUP_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ac79741e-e770-4a12-9acf-9247a28206b0
          stepCounter: a81ba1f1-3139-4dad-a9e4-65448f1a7cb7
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0df82fc9-7e76-4b92-8aa7-0f7239652f29
          stepCounter: a81ba1f1-3139-4dad-a9e4-65448f1a7cb7
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
  name: LOAD_MOSAIC_CDM_APPLICATION_FUNCTION
  schema: ""
  sqlType: Source
  type: sourceInput
  version: 1
type: Node
