fileVersion: 1
id: c931f28a-83f4-4795-9345-a6091c1c3583
name: LOAD_XSPOC_TBLIPRWELLCONFIG
operation:
  config:
    archive_enabled: true
    archive_path: archive
    extlocation: false
    fieldDelim: ~|~
    fieldEnclosed: '"'
    fileFormatType: File Format Values
    filePattern: ''
    fileType: CSV
    inferschema: false
    insertStrategy: INSERT
    intextstage: true
    postSQL: ''
    preSQL: ''
    recDelim: ''
    replaceinvalidcharacters: false
    skipBlankLines: false
    skipHeader: '1'
    stageName: s3_LOAD_XSPOC_TBLIPRWELLCONFIG
    stageStorageLocationName: DV2_STG
    stripouterarray: false
    subfolder: ''
    testsEnabled: true
    trimSpace: false
    truncateBefore: true
    usevectscan: false
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6a6ea0ea-7db7-4ec4-b79a-fccccaaaa331
          stepCounter: c931f28a-83f4-4795-9345-a6091c1c3583
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        name: NODEID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a3ef7ed0-1346-43da-b8eb-914f8261167b
          stepCounter: c931f28a-83f4-4795-9345-a6091c1c3583
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        name: TESTDATE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 61bdc560-dbbf-4a23-8761-4309e70523e4
          stepCounter: c931f28a-83f4-4795-9345-a6091c1c3583
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: ANALYSISCORRELATIONID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 41ca9938-2e81-4068-b229-6f0b463298b9
          stepCounter: c931f28a-83f4-4795-9345-a6091c1c3583
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: FBHPANALYSISSOURCEID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d460e688-8959-4840-8817-a63e669a0905
          stepCounter: c931f28a-83f4-4795-9345-a6091c1c3583
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: GROSSRATEANALYSISSOURCEID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c4af7440-61c6-493d-b4f4-fa7a02aea86d
          stepCounter: c931f28a-83f4-4795-9345-a6091c1c3583
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: WATERCUTANALYSISSOURCEID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ab6521a2-4b1c-49d3-a6bf-30f9ff28c85d
          stepCounter: c931f28a-83f4-4795-9345-a6091c1c3583
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1f487f5d-d8d5-4021-81ef-eae9851c7f05
          stepCounter: c931f28a-83f4-4795-9345-a6091c1c3583
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences: []
    enabledColumnTestIDs: []
    sourceMapping: []
  name: LOAD_XSPOC_TBLIPRWELLCONFIG
  overrideSQL: false
  schema: ""
  sqlType: External:::324
  type: sql
  version: 1
type: Node
