fileVersion: 1
id: 9e3e53ac-c761-42b1-a925-a957322d1e32
name: ODS_MOSAIC_CDM_APPLICATION_FUNCTION
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7027d10f-7b96-4513-96bd-851e8a781739
          stepCounter: 9e3e53ac-c761-42b1-a925-a957322d1e32
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: APPLICATION_FUNCTION_ID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: e7a29c7e-7462-4aa6-9068-e87b8115cab3
                stepCounter: a81ba1f1-3139-4dad-a9e4-65448f1a7cb7
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 72ffd312-fe2b-44d4-8735-989dcaa5ebee
          stepCounter: 9e3e53ac-c761-42b1-a925-a957322d1e32
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: FUNCTION_TYPE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 5cbba447-c578-45f9-b305-6fac12bd9a47
                stepCounter: a81ba1f1-3139-4dad-a9e4-65448f1a7cb7
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: bb41e5c8-c987-4d0a-937e-85c2433c84b8
          stepCounter: 9e3e53ac-c761-42b1-a925-a957322d1e32
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: LAST_MODIFIED_BY_USER
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 2f215e58-e0b2-4007-8c1e-990e76d41bb1
                stepCounter: a81ba1f1-3139-4dad-a9e4-65448f1a7cb7
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3e5737d1-dcb9-4310-88e3-4bed8fc7eba5
          stepCounter: 9e3e53ac-c761-42b1-a925-a957322d1e32
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: LAST_MODIFIED_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 54016f25-d4a7-492b-b314-323e713e852b
                stepCounter: a81ba1f1-3139-4dad-a9e4-65448f1a7cb7
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ec72bf1c-c237-49c9-ac82-b8b4e20961ab
          stepCounter: 9e3e53ac-c761-42b1-a925-a957322d1e32
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: USER_GROUP_ID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: aff1b115-c011-4249-a4ee-1523e4a7db0a
                stepCounter: a81ba1f1-3139-4dad-a9e4-65448f1a7cb7
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 41c4ae29-ea39-419f-839a-d2aa9c986d69
          stepCounter: 9e3e53ac-c761-42b1-a925-a957322d1e32
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: ac79741e-e770-4a12-9acf-9247a28206b0
                stepCounter: a81ba1f1-3139-4dad-a9e4-65448f1a7cb7
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: eed071f1-77c8-4ea6-96f8-f3af8023fbb4
          stepCounter: 9e3e53ac-c761-42b1-a925-a957322d1e32
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 0df82fc9-7e76-4b92-8aa7-0f7239652f29
                stepCounter: a81ba1f1-3139-4dad-a9e4-65448f1a7cb7
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 2ad9e1a8-8840-463d-907d-17105cb8e35c
          stepCounter: 9e3e53ac-c761-42b1-a925-a957322d1e32
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: Flag field to identify Deleted record
        name: DSS_DELETE_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 04059b99-31f8-476d-b2a1-70d69824a956
          stepCounter: 9e3e53ac-c761-42b1-a925-a957322d1e32
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Records time when record was set to Delete by the Load process
        name: DSS_DELETE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 925779bf-fd66-4fb2-b586-e647ef3fd016
          stepCounter: 9e3e53ac-c761-42b1-a925-a957322d1e32
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Datetime a business key was started.
        isSystemStartDate: true
        name: DSS_START_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e0cc66b1-1d64-4b15-a9ad-e6499164dd1e
          stepCounter: 9e3e53ac-c761-42b1-a925-a957322d1e32
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Datetime a business key was retired.
        isSystemEndDate: true
        name: DSS_END_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7e0bd47a-0214-4ddb-aa98-d042912a4f51
          stepCounter: 9e3e53ac-c761-42b1-a925-a957322d1e32
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: Flag to indicate the current (latest) version of a business key.
        isSystemCurrentFlag: true
        name: DSS_CURRENT_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 011d9585-60ed-43d1-9611-c363b69de9a9
          stepCounter: 9e3e53ac-c761-42b1-a925-a957322d1e32
        config: {}
        dataType: INTEGER
        defaultValue: ""
        description: Version number of a business key.
        isSystemVersion: true
        name: DSS_VERSION
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 50f98129-f3f4-47cf-884f-41a8b27466cd
          stepCounter: 9e3e53ac-c761-42b1-a925-a957322d1e32
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was created in the data warehouse.
        isSystemCreateDate: true
        name: DSS_CREATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a8c767b3-02bc-4386-abc2-2ad777535080
          stepCounter: 9e3e53ac-c761-42b1-a925-a957322d1e32
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was updated in the data warehouse.
        isSystemUpdateDate: true
        name: DSS_UPDATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          LOAD_MOSAIC_CDM_APPLICATION_FUNCTION: a81ba1f1-3139-4dad-a9e4-65448f1a7cb7
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: TARGET
            nodeName: LOAD_MOSAIC_CDM_APPLICATION_FUNCTION
        join:
          joinCondition: FROM {{ ref('TARGET','LOAD_MOSAIC_CDM_APPLICATION_FUNCTION') }}
        name: ODS_MOSAIC_CDM_APPLICATION_FUNCTION
        noLinkRefs: []
  name: ODS_MOSAIC_CDM_APPLICATION_FUNCTION
  overrideSQL: false
  schema: ""
  sqlType: persistentStage
  type: sql
  version: 1
type: Node
