fileVersion: 1
id: 589951ff-b48d-4d40-a4bf-03e7f92081c9
name: LOAD_QBYTE_SS_CLIENT_CONFIGURATION
operation:
  config:
    archive_enabled: true
    archive_path: archive
    extlocation: false
    fieldDelim: ~|~
    fieldEnclosed: '"'
    fileFormatType: File Format Values
    filePattern: ''
    fileType: CSV
    inferschema: false
    insertStrategy: INSERT
    intextstage: true
    postSQL: ''
    preSQL: ''
    recDelim: ''
    replaceinvalidcharacters: false
    skipBlankLines: false
    skipHeader: '1'
    stageName: s3_LOAD_QBYTE_SS_CLIENT_CONFIGURATION
    stageStorageLocationName: DV2_STG
    stripouterarray: false
    subfolder: ''
    testsEnabled: true
    trimSpace: false
    truncateBefore: true
    usevectscan: false
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b7b0d72d-71c1-4e2e-accd-3ae13ab868ef
          stepCounter: 589951ff-b48d-4d40-a4bf-03e7f92081c9
        config: {}
        dataType: NUMBER(3)
        defaultValue: ""
        description: ""
        name: CLIENT_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f3438d54-7a84-4965-93a6-a74e7340706d
          stepCounter: 589951ff-b48d-4d40-a4bf-03e7f92081c9
        config: {}
        dataType: VARCHAR(30)
        defaultValue: ""
        description: Identifier to determine the client.
        name: SECTION_NM
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5917113d-a82f-4fcc-9e8b-debd184ea0f5
          stepCounter: 589951ff-b48d-4d40-a4bf-03e7f92081c9
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: The configuration setting name.
        name: SETTING_NM
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: aac64b5b-ce18-4928-85ef-c1bc69725fdb
          stepCounter: 589951ff-b48d-4d40-a4bf-03e7f92081c9
        config: {}
        dataType: VARCHAR(300)
        defaultValue: ""
        description: The configuration setting value.
        name: SETTING_VLU
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 52eade2c-17ea-4910-a44c-b0a5842b8e29
          stepCounter: 589951ff-b48d-4d40-a4bf-03e7f92081c9
        config: {}
        dataType: VARCHAR(1000)
        defaultValue: ""
        description: The description of the configuration setting.
        name: SETTING_DESC
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a081a683-71f7-4715-954a-9fb633102f00
          stepCounter: 589951ff-b48d-4d40-a4bf-03e7f92081c9
        config: {}
        dataType: VARCHAR(30)
        defaultValue: ""
        description: The user who created the record.
        name: CREATE_USER
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: bbc1695b-8989-499c-874c-8cde20b288e8
          stepCounter: 589951ff-b48d-4d40-a4bf-03e7f92081c9
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: The date the record was created.
        name: CREATE_DATE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 610c2ba4-b233-4a61-bb7f-5d4f8b6a49b7
          stepCounter: 589951ff-b48d-4d40-a4bf-03e7f92081c9
        config: {}
        dataType: VARCHAR(30)
        defaultValue: ""
        description: The user who last updated the record.
        name: LAST_UPDATE_USER
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7e825179-7ce1-456e-97c5-f7c0f8bc7c54
          stepCounter: 589951ff-b48d-4d40-a4bf-03e7f92081c9
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: The date the record was last updated.
        name: LAST_UPDATE_DATE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: fb0511ca-af2a-4bd1-a105-d8510e6ac76c
          stepCounter: 589951ff-b48d-4d40-a4bf-03e7f92081c9
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 387f6cd9-eafd-4b3f-9f90-ac6d59323d58
          stepCounter: 589951ff-b48d-4d40-a4bf-03e7f92081c9
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences: []
    enabledColumnTestIDs: []
    sourceMapping: []
  name: LOAD_QBYTE_SS_CLIENT_CONFIGURATION
  overrideSQL: false
  schema: ""
  sqlType: External:::324
  type: sql
  version: 1
type: Node
