fileVersion: 1
id: fcaffcd4-6126-4161-921d-fc63a6573eac
name: ODS_XSPOC_TBLIPRWELLCONFIG
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: be3083a3-2591-4479-9ec8-fea188927e16
          stepCounter: fcaffcd4-6126-4161-921d-fc63a6573eac
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: NODEID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 6a6ea0ea-7db7-4ec4-b79a-fccccaaaa331
                stepCounter: c931f28a-83f4-4795-9345-a6091c1c3583
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c394826b-4f34-4cb3-94b2-9b1a2e3a9a2a
          stepCounter: fcaffcd4-6126-4161-921d-fc63a6573eac
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: TESTDATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: a3ef7ed0-1346-43da-b8eb-914f8261167b
                stepCounter: c931f28a-83f4-4795-9345-a6091c1c3583
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b9b214b9-8f7f-42f9-a900-982b4b258ee6
          stepCounter: fcaffcd4-6126-4161-921d-fc63a6573eac
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: ANALYSISCORRELATIONID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 61bdc560-dbbf-4a23-8761-4309e70523e4
                stepCounter: c931f28a-83f4-4795-9345-a6091c1c3583
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a0e54105-a3bc-474e-998a-7759db5e5251
          stepCounter: fcaffcd4-6126-4161-921d-fc63a6573eac
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: FBHPANALYSISSOURCEID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 41ca9938-2e81-4068-b229-6f0b463298b9
                stepCounter: c931f28a-83f4-4795-9345-a6091c1c3583
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 2a981718-cc0e-4556-b119-809ae295986b
          stepCounter: fcaffcd4-6126-4161-921d-fc63a6573eac
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: GROSSRATEANALYSISSOURCEID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: d460e688-8959-4840-8817-a63e669a0905
                stepCounter: c931f28a-83f4-4795-9345-a6091c1c3583
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0fdd0b59-a72b-42e3-8b6f-5124da6f14c9
          stepCounter: fcaffcd4-6126-4161-921d-fc63a6573eac
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: WATERCUTANALYSISSOURCEID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: c4af7440-61c6-493d-b4f4-fa7a02aea86d
                stepCounter: c931f28a-83f4-4795-9345-a6091c1c3583
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 47fcc308-fe66-4f27-9d83-26624953ca95
          stepCounter: fcaffcd4-6126-4161-921d-fc63a6573eac
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: ab6521a2-4b1c-49d3-a6bf-30f9ff28c85d
                stepCounter: c931f28a-83f4-4795-9345-a6091c1c3583
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: fe42e6b1-6718-47dd-a6d9-da481aadc7b4
          stepCounter: fcaffcd4-6126-4161-921d-fc63a6573eac
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 1f487f5d-d8d5-4021-81ef-eae9851c7f05
                stepCounter: c931f28a-83f4-4795-9345-a6091c1c3583
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c46ed8c3-de76-4df6-aee3-56c36ae91dca
          stepCounter: fcaffcd4-6126-4161-921d-fc63a6573eac
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: Flag field to identify Deleted record
        name: DSS_DELETE_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 290f9499-bc84-488e-8db7-322ff528d41b
          stepCounter: fcaffcd4-6126-4161-921d-fc63a6573eac
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Records time when record was set to Delete by the Load process
        name: DSS_DELETE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0737bd0b-8c9a-437e-be44-4eabead00d9f
          stepCounter: fcaffcd4-6126-4161-921d-fc63a6573eac
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Datetime a business key was started.
        isSystemStartDate: true
        name: DSS_START_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 28209778-805c-452f-99d0-0d7ffd4b75b2
          stepCounter: fcaffcd4-6126-4161-921d-fc63a6573eac
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Datetime a business key was retired.
        isSystemEndDate: true
        name: DSS_END_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 2701655f-98b9-464c-a47a-5b571390884a
          stepCounter: fcaffcd4-6126-4161-921d-fc63a6573eac
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: Flag to indicate the current (latest) version of a business key.
        isSystemCurrentFlag: true
        name: DSS_CURRENT_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1b5a7142-e627-493c-9849-c63781236097
          stepCounter: fcaffcd4-6126-4161-921d-fc63a6573eac
        config: {}
        dataType: INTEGER
        defaultValue: ""
        description: Version number of a business key.
        isSystemVersion: true
        name: DSS_VERSION
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 677b0edc-5f9d-4c7c-ab88-f4c85a7a5eeb
          stepCounter: fcaffcd4-6126-4161-921d-fc63a6573eac
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was created in the data warehouse.
        isSystemCreateDate: true
        name: DSS_CREATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6c1907b2-dc32-45cf-b00f-cf48bb8e0768
          stepCounter: fcaffcd4-6126-4161-921d-fc63a6573eac
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was updated in the data warehouse.
        isSystemUpdateDate: true
        name: DSS_UPDATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          LOAD_XSPOC_TBLIPRWELLCONFIG: c931f28a-83f4-4795-9345-a6091c1c3583
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: TARGET
            nodeName: LOAD_XSPOC_TBLIPRWELLCONFIG
        join:
          joinCondition: FROM {{ ref('TARGET','LOAD_XSPOC_TBLIPRWELLCONFIG') }} LOAD_XSPOC_TBLIPRWELLCONFIG
        name: ODS_XSPOC_TBLIPRWELLCONFIG
        noLinkRefs: []
  name: ODS_XSPOC_TBLIPRWELLCONFIG
  overrideSQL: false
  schema: ""
  sqlType: '38'
  type: sql
  version: 1
type: Node
