fileVersion: 1
id: 9a5f720c-8897-4439-95ca-3e8824911bad
name: ODS_XSPOC_TBLALARMCONFIGBYPOCTYPE
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 72f347ef-1951-40dd-a290-4736e8a1b0f4
          stepCounter: 9a5f720c-8897-4439-95ca-3e8824911bad
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: POCTYPE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: c337f774-94dd-4f5d-84b9-4f044e6a6b68
                stepCounter: a65d44f6-5064-4770-845e-903e6b24356f
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b817047f-d917-413b-b3e2-1fe14ccfbde7
          stepCounter: 9a5f720c-8897-4439-95ca-3e8824911bad
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: REGISTER
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 41feccec-d8ad-4ca7-af6a-6ff11d808fe5
                stepCounter: a65d44f6-5064-4770-845e-903e6b24356f
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 4bb8aa5f-0669-4305-8e7a-ec13616445aa
          stepCounter: 9a5f720c-8897-4439-95ca-3e8824911bad
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: BIT
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: b66cce14-3c64-49e2-bd47-d5ab35f47339
                stepCounter: a65d44f6-5064-4770-845e-903e6b24356f
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e69fe89c-106b-4eb7-828c-d63874d9a31c
          stepCounter: 9a5f720c-8897-4439-95ca-3e8824911bad
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: DESCRIPTION
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 85fb0f45-c8a5-4bb0-9b73-938a6e7e5adc
                stepCounter: a65d44f6-5064-4770-845e-903e6b24356f
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: aca7004a-e530-4267-9c51-65e779253ba3
          stepCounter: 9a5f720c-8897-4439-95ca-3e8824911bad
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: PHRASEID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: dae58b46-fadd-4743-8aa8-40c1f6550521
                stepCounter: a65d44f6-5064-4770-845e-903e6b24356f
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f8d4832b-3d43-49c2-aa93-da890ea0533a
          stepCounter: 9a5f720c-8897-4439-95ca-3e8824911bad
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: PRIORITY
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 3afaebc1-5a1e-4fa0-a3a4-b55371e43c97
                stepCounter: a65d44f6-5064-4770-845e-903e6b24356f
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 313a62b1-c864-47a5-8182-5614be2b7db6
          stepCounter: 9a5f720c-8897-4439-95ca-3e8824911bad
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: CALLOUTENABLED
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 2ca7b6cd-6f34-4723-b560-d9bd8b9a6346
                stepCounter: a65d44f6-5064-4770-845e-903e6b24356f
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3efa8db4-616d-431a-9865-1a5565267215
          stepCounter: 9a5f720c-8897-4439-95ca-3e8824911bad
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: ENABLED
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 02f39abe-c832-4c00-8233-224e52a63473
                stepCounter: a65d44f6-5064-4770-845e-903e6b24356f
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 490bf4e5-ac21-49dc-af6d-374363baaacd
          stepCounter: 9a5f720c-8897-4439-95ca-3e8824911bad
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: NORMALSTATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 7131e34b-1cb7-4552-9069-4b6b9cc4469c
                stepCounter: a65d44f6-5064-4770-845e-903e6b24356f
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ce2baa90-371d-4b58-9b73-3513bfc5deaa
          stepCounter: 9a5f720c-8897-4439-95ca-3e8824911bad
        config: {}
        dataType: FLOAT
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: LOLIMIT
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 03104a3b-5ec3-4ef2-b3e7-4b533474af32
                stepCounter: a65d44f6-5064-4770-845e-903e6b24356f
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: fb456c5b-a822-409d-a296-d1156d2354cc
          stepCounter: 9a5f720c-8897-4439-95ca-3e8824911bad
        config: {}
        dataType: FLOAT
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: HILIMIT
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 5c679bfd-82c3-4761-8a68-0301dacbc9fa
                stepCounter: a65d44f6-5064-4770-845e-903e6b24356f
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b1d92ab5-50e7-4b91-8f5d-0909380f9ceb
          stepCounter: 9a5f720c-8897-4439-95ca-3e8824911bad
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: LOCKED
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 82344492-3a9f-45ec-9ac9-9613ef16faeb
                stepCounter: a65d44f6-5064-4770-845e-903e6b24356f
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f39af683-f3aa-4414-bc29-2e3a1d2ad48a
          stepCounter: 9a5f720c-8897-4439-95ca-3e8824911bad
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: ALARMACTION
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: c2444b72-7107-43f6-80b1-56fdbde9805e
                stepCounter: a65d44f6-5064-4770-845e-903e6b24356f
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 461b2017-ada2-4ffd-add2-049c3c84c077
          stepCounter: 9a5f720c-8897-4439-95ca-3e8824911bad
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 3c5a9993-2f86-468c-9b59-1b6517e0532c
                stepCounter: a65d44f6-5064-4770-845e-903e6b24356f
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 211f55e1-8604-4b48-8d8c-a146dfef85b2
          stepCounter: 9a5f720c-8897-4439-95ca-3e8824911bad
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: cb013f3e-1884-448d-8bc0-57cb8d57162e
                stepCounter: a65d44f6-5064-4770-845e-903e6b24356f
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: abb02441-1825-445a-bd25-048fb5cef4fe
          stepCounter: 9a5f720c-8897-4439-95ca-3e8824911bad
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: Flag field to identify Deleted record
        name: DSS_DELETE_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d6743793-1f4d-44ea-affd-c0877080c126
          stepCounter: 9a5f720c-8897-4439-95ca-3e8824911bad
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Records time when record was set to Delete by the Load process
        name: DSS_DELETE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b14dbc1f-4062-4ecc-8c8e-414fcbe1739b
          stepCounter: 9a5f720c-8897-4439-95ca-3e8824911bad
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Datetime a business key was started.
        isSystemStartDate: true
        name: DSS_START_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c45eea34-6ec2-4c92-84fb-9e2a3ec2a5f0
          stepCounter: 9a5f720c-8897-4439-95ca-3e8824911bad
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Datetime a business key was retired.
        isSystemEndDate: true
        name: DSS_END_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 02cfaa9a-fdb4-45d4-a909-051f4b599391
          stepCounter: 9a5f720c-8897-4439-95ca-3e8824911bad
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: Flag to indicate the current (latest) version of a business key.
        isSystemCurrentFlag: true
        name: DSS_CURRENT_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 501b903a-b27a-4c95-b49a-9ee52b9d7d59
          stepCounter: 9a5f720c-8897-4439-95ca-3e8824911bad
        config: {}
        dataType: INTEGER
        defaultValue: ""
        description: Version number of a business key.
        isSystemVersion: true
        name: DSS_VERSION
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 2040fd33-951c-4949-b41c-b1842d22c90a
          stepCounter: 9a5f720c-8897-4439-95ca-3e8824911bad
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was created in the data warehouse.
        isSystemCreateDate: true
        name: DSS_CREATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e05452d4-b469-457e-9750-56da3b59e59b
          stepCounter: 9a5f720c-8897-4439-95ca-3e8824911bad
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was updated in the data warehouse.
        isSystemUpdateDate: true
        name: DSS_UPDATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          LOAD_XSPOC_TBLALARMCONFIGBYPOCTYPE: a65d44f6-5064-4770-845e-903e6b24356f
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: TARGET
            nodeName: LOAD_XSPOC_TBLALARMCONFIGBYPOCTYPE
        join:
          joinCondition: FROM {{ ref('TARGET','LOAD_XSPOC_TBLALARMCONFIGBYPOCTYPE') }} LOAD_XSPOC_TBLALARMCONFIGBYPOCTYPE
        name: ODS_XSPOC_TBLALARMCONFIGBYPOCTYPE
        noLinkRefs: []
  name: ODS_XSPOC_TBLALARMCONFIGBYPOCTYPE
  overrideSQL: false
  schema: ""
  sqlType: '38'
  type: sql
  version: 1
type: Node
