fileVersion: 1
id: d7545f41-2e9c-4ec7-bb95-ebba7b4c1801
name: LOAD_XSPOC_TBLMOTORSETTINGS
operation:
  config:
    archive_enabled: true
    archive_path: archive
    extlocation: false
    fieldDelim: ~|~
    fieldEnclosed: '"'
    fileFormatType: File Format Values
    filePattern: ''
    fileType: CSV
    inferschema: false
    insertStrategy: INSERT
    intextstage: true
    postSQL: ''
    preSQL: ''
    recDelim: ''
    replaceinvalidcharacters: false
    skipBlankLines: false
    skipHeader: '1'
    stageName: s3_LOAD_XSPOC_TBLMOTORSETTINGS
    stageStorageLocationName: DV2_STG
    stripouterarray: false
    subfolder: ''
    testsEnabled: true
    trimSpace: false
    truncateBefore: true
    usevectscan: false
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a6ba25f8-7153-4f5d-b5cc-3e51ddface48
          stepCounter: d7545f41-2e9c-4ec7-bb95-ebba7b4c1801
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: MOTORSETTINGID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c0b15013-800b-401f-ad34-ca70ed73dcbe
          stepCounter: d7545f41-2e9c-4ec7-bb95-ebba7b4c1801
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: ""
        name: NAME
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 86529f4c-9fc9-4459-8370-acee36d55165
          stepCounter: d7545f41-2e9c-4ec7-bb95-ebba7b4c1801
        config: {}
        dataType: FLOAT
        defaultValue: ""
        description: ""
        name: FULLLOADRPM
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ad3b483e-b37a-474f-8326-658b0e12a232
          stepCounter: d7545f41-2e9c-4ec7-bb95-ebba7b4c1801
        config: {}
        dataType: FLOAT
        defaultValue: ""
        description: ""
        name: MAXLOAD
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 810b2ac7-9518-41a0-9fc8-a2a33c8fef92
          stepCounter: d7545f41-2e9c-4ec7-bb95-ebba7b4c1801
        config: {}
        dataType: FLOAT
        defaultValue: ""
        description: ""
        name: MAXSPV
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 30a131a2-c40d-408e-8b86-71efcc91bf03
          stepCounter: d7545f41-2e9c-4ec7-bb95-ebba7b4c1801
        config: {}
        dataType: FLOAT
        defaultValue: ""
        description: ""
        name: RATEDHP
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0c0380e7-1a89-4c92-9d28-1b3b74988f1f
          stepCounter: d7545f41-2e9c-4ec7-bb95-ebba7b4c1801
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: MOTORSIZEID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 11079f13-9feb-40b6-9e8f-d1007a330412
          stepCounter: d7545f41-2e9c-4ec7-bb95-ebba7b4c1801
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e3b60bd0-39d0-4a52-987b-cc41c0e2fd86
          stepCounter: d7545f41-2e9c-4ec7-bb95-ebba7b4c1801
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences: []
    enabledColumnTestIDs: []
    sourceMapping: []
  name: LOAD_XSPOC_TBLMOTORSETTINGS
  overrideSQL: false
  schema: ""
  sqlType: External:::324
  type: sql
  version: 1
type: Node
