fileVersion: 1
id: 2e90fce6-f8f0-4cb9-ba06-db66d1c7942c
name: LOAD_QBYTE_SMCONFIGURATION
operation:
  config:
    archive_enabled: true
    archive_path: archive
    extlocation: false
    fieldDelim: ~|~
    fieldEnclosed: '"'
    fileFormatType: File Format Values
    filePattern: ''
    fileType: CSV
    inferschema: false
    insertStrategy: INSERT
    intextstage: true
    postSQL: ''
    preSQL: ''
    recDelim: ''
    replaceinvalidcharacters: false
    skipBlankLines: false
    skipHeader: '1'
    stageName: s3_LOAD_QBYTE_SMCONFIGURATION
    stageStorageLocationName: DV2_STG
    stripouterarray: false
    subfolder: ''
    testsEnabled: true
    trimSpace: false
    truncateBefore: true
    usevectscan: false
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0391b6df-69ab-47ed-9c4a-811ec9032e2a
          stepCounter: 2e90fce6-f8f0-4cb9-ba06-db66d1c7942c
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: ATTRIBUTE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d0ffb106-5cd9-4239-a0ad-1f1f9490957d
          stepCounter: 2e90fce6-f8f0-4cb9-ba06-db66d1c7942c
        config: {}
        dataType: VARCHAR(512)
        defaultValue: ""
        description: ""
        name: VALUE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 685d20cd-4cf9-49d6-9ad4-4b30f61af99f
          stepCounter: 2e90fce6-f8f0-4cb9-ba06-db66d1c7942c
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: cdd82bd8-7a22-4527-bd3b-bd6c92c11b82
          stepCounter: 2e90fce6-f8f0-4cb9-ba06-db66d1c7942c
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences: []
    enabledColumnTestIDs: []
    sourceMapping: []
  name: LOAD_QBYTE_SMCONFIGURATION
  overrideSQL: false
  schema: ""
  sqlType: External:::324
  type: sql
  version: 1
type: Node
