fileVersion: 1
id: aa12bafd-c812-4daf-9bd2-3760c87cc65f
name: LOAD_CSLAND_CS_SECURITY
operation:
  config:
    archive_enabled: true
    archive_path: archive
    extlocation: false
    fieldDelim: ~|~
    fieldEnclosed: '"'
    fileFormatType: File Format Values
    filePattern: ''
    fileType: CSV
    inferschema: false
    insertStrategy: INSERT
    intextstage: true
    postSQL: ''
    preSQL: ''
    recDelim: ''
    replaceinvalidcharacters: false
    skipBlankLines: false
    skipHeader: '1'
    stageName: s3_LOAD_CSLAND_CS_SECURITY
    stageStorageLocationName: DV2_STG
    stripouterarray: false
    subfolder: ''
    testsEnabled: true
    trimSpace: false
    truncateBefore: true
    usevectscan: false
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: cc1f6428-5947-4db9-b989-2af659848dce
          stepCounter: aa12bafd-c812-4daf-9bd2-3760c87cc65f
        config: {}
        dataType: VARCHAR(30)
        defaultValue: ""
        description: Process Id
        name: PROCESS_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ab7c3f7f-fda5-42fa-ae97-2355587de54c
          stepCounter: aa12bafd-c812-4daf-9bd2-3760c87cc65f
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 02dbfa9c-b31d-400d-adf5-93fa3451d7a8
          stepCounter: aa12bafd-c812-4daf-9bd2-3760c87cc65f
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences: []
    enabledColumnTestIDs: []
    sourceMapping: []
  name: LOAD_CSLAND_CS_SECURITY
  overrideSQL: false
  schema: ""
  sqlType: External:::324
  type: sql
  version: 1
type: Node
