fileVersion: 1
id: 613ae738-9958-433b-9935-cfb2e27b7ff4
name: LOAD_MOSAIC_RES_USER_SETTINGS
operation:
  database: ""
  deployEnabled: true
  description: ""
  locationName: TARGET
  metadata:
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b6722e14-fbe3-4f34-b728-9967d7ab4ef7
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: VARCHAR(150)
        defaultValue: ""
        description: ""
        name: ADDITIONAL_REPORT_TEXT
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 97ca1058-bbd8-4d91-a964-bb8f1cdb0f28
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: ALTERNATE_LINE_SHADING
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b9794c64-bc54-4e82-91ac-73fea1f8135b
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: BUDGET_MONTH_RANGE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 4f4df858-f63a-47aa-b438-650d266f6312
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: BUDGET_YEAR
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 680d01c2-89f5-4bd8-ab85-e3cedabfe7f1
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: ""
        name: CASH_FLOW_SHORT
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 26d8bdd1-cf2d-4e14-a028-cea91b8e5fb0
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: VARCHAR(100)
        defaultValue: ""
        description: ""
        name: CORPORATION_NAME
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: fbfdb27c-8087-4b8a-8657-131f0350c1cb
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_1
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c0716ca3-23f7-4ad2-913c-eb823b7a4ed9
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_2
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 15a2e7d3-0fc5-44e0-b77f-44486933a177
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_3
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e2262ad6-4a00-4f33-8cf0-a869c081b382
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_4
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e70ad7f2-b228-4bfe-a690-afeac7976380
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: NUMBER(24)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_5
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e38be3aa-b2fa-439e-908a-66be3c0e1d4f
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: ECONOMIC_INDICATOR_FLAG
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7446ffa3-c2a0-42fd-92ba-1a8186b93536
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: EXPECTED_VALUES_FLAG
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b573d93e-c1ac-4b8e-badb-2b66f1391647
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: RESERVE_BOE_EQUIV_FLAG
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: aaa4e235-352a-406f-a57e-d5d47a65840b
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: USER_SETTINGS_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a8ba1ceb-75d1-4179-9bdc-75a77923c17c
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: YEARS_REPORTED
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: bd4b631f-e6d9-43d4-a0f7-a9f00bc21d45
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: YEARS_REPORTED_BY_MONTH
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: fa7faaf7-b5a8-4721-8a1c-3c475696c88d
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_1A
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: afa05eb4-e8e8-4eca-8443-7289241211ce
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_2A
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 80562232-ebf8-49ca-8a92-022ff068ea08
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_3A
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 059dd0e9-e7ad-49e5-9371-77361a070e4a
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_4A
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3b79e7bb-c12d-408b-975f-ac7a21e47e25
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_1B
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6c2a5fd5-3363-41dd-9831-6fb8d7e71021
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_2B
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 277c04ca-8ab9-4e4d-b7c9-6398f7308c89
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_3B
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d0dba0cd-b771-421d-9e8c-532575d25eb8
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: ""
        name: VOL_AND_REVENUE_DETAIL_FLAG
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: eecd5e9b-a72b-4d1e-b83a-a551d78b8122
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: ""
        name: ATAX_PKG_FLAG
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 525de1c5-f9fe-4dac-8888-7d0c17c7b7aa
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: ""
        name: CAPITAL_UNDISCOUNTED_FLAG
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 9bd6cea0-bcf6-444b-8f39-660e66f4cc47
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: ""
        name: FIRST_YR_ANNUAL_PRFRMNC_FLAG
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 258fe737-d79c-4f97-9d56-6b2c3356945d
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: ""
        name: INCLUDE_COVER_PAGE_FLAG
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: bedc3d9e-c830-4125-9671-6dc59a5a53c1
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: ""
        name: REPORT_PAGE_NUMBERS
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a8295308-e2c5-411b-9f67-5bdaa6894eaa
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: VARCHAR(150)
        defaultValue: ""
        description: ""
        name: ADDITIONAL_REPORT_TEXT_2
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b4bad508-f423-43b5-a09e-1890a7362f0d
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: ""
        name: OVERWRITE_PROD_DATA
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: fa4d8e86-83f1-467f-99f7-da81295252ba
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_DATE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 188fb0ef-f558-4542-b5a1-301c9b4ff170
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: VARCHAR(100)
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_BY_USER
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e73be8f1-0478-4ce6-b194-ea6f260962e5
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0544cd8f-3475-45cf-9bd7-0d39f88df710
          stepCounter: 613ae738-9958-433b-9935-cfb2e27b7ff4
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
  name: LOAD_MOSAIC_RES_USER_SETTINGS
  schema: ""
  sqlType: Source
  type: sourceInput
  version: 1
type: Node
