fileVersion: 1
id: 9cbe9149-4c36-4994-910c-79408f5a068b
name: LOAD_MOSAIC_CDM_WORKSPACE_SETTINGS
operation:
  database: ""
  deployEnabled: true
  description: ""
  locationName: TARGET
  metadata:
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d49dd9ec-4642-4ff5-8320-7e811bb2c610
          stepCounter: 9cbe9149-4c36-4994-910c-79408f5a068b
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: CURRENT_CASE_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 12e6d154-876b-48c8-b63a-42f3f7cb2f5d
          stepCounter: 9cbe9149-4c36-4994-910c-79408f5a068b
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: DEFAULT_COMPANY_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ab833c4e-c73e-4fb8-a819-6ff06414a538
          stepCounter: 9cbe9149-4c36-4994-910c-79408f5a068b
        config: {}
        dataType: VARCHAR(250)
        defaultValue: ""
        description: ""
        name: DESCRIPTION
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e13c2bcd-7ff0-4e45-8b69-612fccfa44f5
          stepCounter: 9cbe9149-4c36-4994-910c-79408f5a068b
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_BY_USER
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 22f13cf6-325c-4b46-8e12-8981ebcc1329
          stepCounter: 9cbe9149-4c36-4994-910c-79408f5a068b
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_DATE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0857c847-2417-4fe7-9758-485ee4bcf1cc
          stepCounter: 9cbe9149-4c36-4994-910c-79408f5a068b
        config: {}
        dataType: VARCHAR(100)
        defaultValue: ""
        description: ""
        name: NAME
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8ca452af-2dd3-4d21-878f-939bb59ad445
          stepCounter: 9cbe9149-4c36-4994-910c-79408f5a068b
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: PREVIOUS_CASE_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c04d62f2-b140-4d40-9076-852aa5279aff
          stepCounter: 9cbe9149-4c36-4994-910c-79408f5a068b
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: PRIVATE_FLAG
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f7b1fe91-36df-415a-b675-093b3a01a63d
          stepCounter: 9cbe9149-4c36-4994-910c-79408f5a068b
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: RESERVE_CAT_GROUP_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 25dd0d6b-0dbe-40cd-9f4b-d082f24cc43e
          stepCounter: 9cbe9149-4c36-4994-910c-79408f5a068b
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: SEARCH_FILTER_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 587894e2-3774-4a4e-a14f-9a443bba2946
          stepCounter: 9cbe9149-4c36-4994-910c-79408f5a068b
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: USER_PROFILE_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a7754436-eb1d-4071-8b9e-41a51149c1ca
          stepCounter: 9cbe9149-4c36-4994-910c-79408f5a068b
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        name: UUID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6e49ba18-887e-460f-9b67-b9dd5724c983
          stepCounter: 9cbe9149-4c36-4994-910c-79408f5a068b
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: WORKBENCH_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 2549e2b1-0a46-45ba-b99a-eefde988f84d
          stepCounter: 9cbe9149-4c36-4994-910c-79408f5a068b
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: WORKSPACE_SETTINGS_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: eeaaf195-a879-4489-9ed7-29a68ef145f0
          stepCounter: 9cbe9149-4c36-4994-910c-79408f5a068b
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        name: DEFAULT_STATIC_HIERARCHY_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f8d2893a-5d09-45b9-a2d7-8217bb23df2f
          stepCounter: 9cbe9149-4c36-4994-910c-79408f5a068b
        config: {}
        dataType: VARCHAR(250)
        defaultValue: ""
        description: ""
        name: HIERARCHY_FILTER_NAME
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 9409d354-71c9-44c3-be54-0ace2ff8affa
          stepCounter: 9cbe9149-4c36-4994-910c-79408f5a068b
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        name: ENTITY_STATE_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 39d253aa-e462-4cc2-a7b2-5cfd542d9705
          stepCounter: 9cbe9149-4c36-4994-910c-79408f5a068b
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        name: WORKSPACE_VIEW_TYPE_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 2e3ac744-da4f-4763-9968-54a0a9de97b7
          stepCounter: 9cbe9149-4c36-4994-910c-79408f5a068b
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        name: PANEL_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: bf0fb74c-29c1-449b-8962-e1ae1ab45e24
          stepCounter: 9cbe9149-4c36-4994-910c-79408f5a068b
        config: {}
        dataType: VARCHAR(200)
        defaultValue: ""
        description: ""
        name: TABLE_COLUMN_SET
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ae06f936-42ef-4e45-8669-d8ded710c578
          stepCounter: 9cbe9149-4c36-4994-910c-79408f5a068b
        config: {}
        dataType: VARCHAR(200)
        defaultValue: ""
        description: ""
        name: ECONOMIC_COLUMN_SET
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: cc0c576a-3904-4f2f-93c0-5c151783373f
          stepCounter: 9cbe9149-4c36-4994-910c-79408f5a068b
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        name: ICON_CODE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 121afd2e-587a-4612-878e-f04350dcb9ea
          stepCounter: 9cbe9149-4c36-4994-910c-79408f5a068b
        config: {}
        dataType: VARCHAR(250)
        defaultValue: ""
        description: ""
        name: ENTITY_NAME
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: fe40fa01-1404-4131-a7c0-79cae2fa9219
          stepCounter: 9cbe9149-4c36-4994-910c-79408f5a068b
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: RESERVE_CATEGORY_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f626d789-2d14-49cd-92d1-4c06606b3bfd
          stepCounter: 9cbe9149-4c36-4994-910c-79408f5a068b
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: RECON_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 54b79722-97dc-4cc5-b4a8-a1a87d37faa6
          stepCounter: 9cbe9149-4c36-4994-910c-79408f5a068b
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 261cf514-2958-4026-90a3-8dce53768e12
          stepCounter: 9cbe9149-4c36-4994-910c-79408f5a068b
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
  name: LOAD_MOSAIC_CDM_WORKSPACE_SETTINGS
  schema: ""
  sqlType: Source
  type: sourceInput
  version: 1
type: Node
