fileVersion: 1
id: ac378b49-9ef1-4f23-b33c-2b8d35003734
name: LOAD_CSLAND_T_RUACONFIG
operation:
  config:
    archive_enabled: true
    archive_path: archive
    extlocation: false
    fieldDelim: ~|~
    fieldEnclosed: '"'
    fileFormatType: File Format Values
    filePattern: ''
    fileType: CSV
    inferschema: false
    insertStrategy: INSERT
    intextstage: true
    postSQL: ''
    preSQL: ''
    recDelim: ''
    replaceinvalidcharacters: false
    skipBlankLines: false
    skipHeader: '1'
    stageName: s3_LOAD_CSLAND_T_RUACONFIG
    stageStorageLocationName: DV2_STG
    stripouterarray: false
    subfolder: ''
    testsEnabled: true
    trimSpace: false
    truncateBefore: true
    usevectscan: false
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 024a71b0-cc82-494c-b1e8-2d789668aa7a
          stepCounter: ac378b49-9ef1-4f23-b33c-2b8d35003734
        config: {}
        dataType: VARCHAR(6)
        defaultValue: ""
        description: Owner Code
        name: OWNER_CODE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e3f97586-ceef-4e5d-ac6a-dc63c18f03a4
          stepCounter: ac378b49-9ef1-4f23-b33c-2b8d35003734
        config: {}
        dataType: VARCHAR(10)
        defaultValue: ""
        description: Code
        name: CODE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1a81cdfd-536a-4104-a66c-f8e46412a216
          stepCounter: ac378b49-9ef1-4f23-b33c-2b8d35003734
        config: {}
        dataType: VARCHAR(40)
        defaultValue: ""
        description: Description
        name: DESCRIPTION
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: bff0ab94-f503-4e59-9256-3449dd1858b1
          stepCounter: ac378b49-9ef1-4f23-b33c-2b8d35003734
        config: {}
        dataType: VARCHAR(40)
        defaultValue: ""
        description: Value
        name: VALUE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0e6dbeec-2445-4f20-b97e-57fdace217c6
          stepCounter: ac378b49-9ef1-4f23-b33c-2b8d35003734
        config: {}
        dataType: VARCHAR(1)
        defaultValue: ""
        description: AI Status
        name: AI_STATUS
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f85ef776-9c8d-43a6-b59e-4b803f8a847d
          stepCounter: ac378b49-9ef1-4f23-b33c-2b8d35003734
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: Last Update User
        name: LAST_UPDATE_USER
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 24e26ad2-6148-4b27-90b6-02af6443bdac
          stepCounter: ac378b49-9ef1-4f23-b33c-2b8d35003734
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Last Update Date
        name: LAST_UPDATE_DATE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: bb4a5d8e-14d9-4a49-9d5d-724450ca744e
          stepCounter: ac378b49-9ef1-4f23-b33c-2b8d35003734
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: Code In Use
        name: CODE_IN_USE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a6a7f02b-b1ca-4b09-ba45-625542c8d165
          stepCounter: ac378b49-9ef1-4f23-b33c-2b8d35003734
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: Reserved
        name: RESERVED
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5eb108dc-24c5-4489-bbf6-21639f07c5a0
          stepCounter: ac378b49-9ef1-4f23-b33c-2b8d35003734
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6e0b1512-c600-4f99-896c-e3ad00445a5e
          stepCounter: ac378b49-9ef1-4f23-b33c-2b8d35003734
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences: []
    enabledColumnTestIDs: []
    sourceMapping: []
  name: LOAD_CSLAND_T_RUACONFIG
  overrideSQL: false
  schema: ""
  sqlType: External:::324
  type: sql
  version: 1
type: Node
