fileVersion: 1
id: 69402dea-b041-4563-8884-6d760c73c63d
name: LOAD_MOSAIC_RES_APPLICATION_FUNCTION
operation:
  database: ""
  deployEnabled: true
  description: ""
  locationName: TARGET
  metadata:
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d24d865f-f5c9-495c-9b69-7bef481ab592
          stepCounter: 69402dea-b041-4563-8884-6d760c73c63d
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: APPLICATION_FUNCTION_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1f0b1d20-fe3d-4961-a2dc-9b8aea035678
          stepCounter: 69402dea-b041-4563-8884-6d760c73c63d
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: FUNCTION_TYPE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a54dabde-6042-4dec-b14e-8b2802ce1747
          stepCounter: 69402dea-b041-4563-8884-6d760c73c63d
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_BY_USER
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 791f9f38-a895-48b1-96f5-7052f07b5148
          stepCounter: 69402dea-b041-4563-8884-6d760c73c63d
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_DATE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 984b8221-a60a-4e89-b515-f03cc0b6ff02
          stepCounter: 69402dea-b041-4563-8884-6d760c73c63d
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: USER_GROUP_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ce95c61c-6d52-4e44-aa45-737add6662d0
          stepCounter: 69402dea-b041-4563-8884-6d760c73c63d
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: fb2c687e-8a85-425b-a2fc-ae6b94fb40ab
          stepCounter: 69402dea-b041-4563-8884-6d760c73c63d
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
  name: LOAD_MOSAIC_RES_APPLICATION_FUNCTION
  schema: ""
  sqlType: Source
  type: sourceInput
  version: 1
type: Node
