fileVersion: 1
id: 1b5007b0-3a6d-499b-9542-3166a3b536a5
name: LOAD_XSPOC_TBLCAMERACONFIGURATIONS
operation:
  config:
    archive_enabled: true
    archive_path: archive
    extlocation: false
    fieldDelim: ~|~
    fieldEnclosed: '"'
    fileFormatType: File Format Values
    filePattern: ''
    fileType: CSV
    inferschema: false
    insertStrategy: INSERT
    intextstage: true
    postSQL: ''
    preSQL: ''
    recDelim: ''
    replaceinvalidcharacters: false
    skipBlankLines: false
    skipHeader: '1'
    stageName: s3_LOAD_XSPOC_TBLCAMERACONFIGURATIONS
    stageStorageLocationName: DV2_STG
    stripouterarray: false
    subfolder: ''
    testsEnabled: true
    trimSpace: false
    truncateBefore: true
    usevectscan: false
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c6e6ac8f-d11b-4244-aef6-8e4b1c5e72bb
          stepCounter: 1b5007b0-3a6d-499b-9542-3166a3b536a5
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 37366d72-5bc0-43cb-9a09-2adbfd5bb15c
          stepCounter: 1b5007b0-3a6d-499b-9542-3166a3b536a5
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        name: DESCRIPTION
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f66df2da-d84f-4bfa-ab3c-983d27f1da9c
          stepCounter: 1b5007b0-3a6d-499b-9542-3166a3b536a5
        config: {}
        dataType: VARCHAR(200)
        defaultValue: ""
        description: ""
        name: FORMATSTRINGVIDEO
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0fcbdc75-61df-432d-aef1-b5ea290010c3
          stepCounter: 1b5007b0-3a6d-499b-9542-3166a3b536a5
        config: {}
        dataType: VARCHAR(200)
        defaultValue: ""
        description: ""
        name: FORMATSTRINGSNAPSHOT
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 822dd22b-f465-4874-82e2-5f52d8ad5a23
          stepCounter: 1b5007b0-3a6d-499b-9542-3166a3b536a5
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: SNAPSHOTURIHTTPAUTHENTICATION
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: dc8ab898-2275-44d9-9b02-464863aada01
          stepCounter: 1b5007b0-3a6d-499b-9542-3166a3b536a5
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5e326146-1148-432d-a82c-1c3fd1f5c45f
          stepCounter: 1b5007b0-3a6d-499b-9542-3166a3b536a5
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences: []
    enabledColumnTestIDs: []
    sourceMapping: []
  name: LOAD_XSPOC_TBLCAMERACONFIGURATIONS
  overrideSQL: false
  schema: ""
  sqlType: External:::324
  type: sql
  version: 1
type: Node
