fileVersion: 1
id: 0868ebe1-cdeb-4aeb-83db-0519e112a981
name: LOAD_XSPOC_TBLCAMERACONFIGURATIONS
operation:
  database: ""
  deployEnabled: true
  description: ""
  locationName: TARGET
  metadata:
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 4267d30e-86c3-4e97-ac1c-5323dd722dfa
          stepCounter: 0868ebe1-cdeb-4aeb-83db-0519e112a981
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e1cb23a0-2516-4db1-8ee5-f34832efc44d
          stepCounter: 0868ebe1-cdeb-4aeb-83db-0519e112a981
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        name: DESCRIPTION
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f3778afd-ac1b-45aa-85ec-bec148382555
          stepCounter: 0868ebe1-cdeb-4aeb-83db-0519e112a981
        config: {}
        dataType: VARCHAR(200)
        defaultValue: ""
        description: ""
        name: FORMATSTRINGVIDEO
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: db398b4c-7d44-4c88-b7c1-7fe9220dc41f
          stepCounter: 0868ebe1-cdeb-4aeb-83db-0519e112a981
        config: {}
        dataType: VARCHAR(200)
        defaultValue: ""
        description: ""
        name: FORMATSTRINGSNAPSHOT
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7dd84e94-b4e6-4706-8a4c-555236d6875f
          stepCounter: 0868ebe1-cdeb-4aeb-83db-0519e112a981
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: SNAPSHOTURIHTTPAUTHENTICATION
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: abd01514-c3fc-4c88-821a-b716141d0005
          stepCounter: 0868ebe1-cdeb-4aeb-83db-0519e112a981
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b110acc4-e55d-46e7-b39b-f9063c5e245d
          stepCounter: 0868ebe1-cdeb-4aeb-83db-0519e112a981
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
  name: LOAD_XSPOC_TBLCAMERACONFIGURATIONS
  schema: ""
  sqlType: Source
  type: sourceInput
  version: 1
type: Node
