fileVersion: 1
id: 5ce20cda-94d7-4715-9bfd-b8d0a8516a0c
name: LOAD_CSLAND_T_RUACONFIG
operation:
  database: ""
  deployEnabled: true
  description: ""
  locationName: TARGET
  metadata:
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7fc375b1-b74c-4dc1-8d87-ec72a186e491
          stepCounter: 5ce20cda-94d7-4715-9bfd-b8d0a8516a0c
        config: {}
        dataType: VARCHAR(6)
        defaultValue: ""
        description: Owner Code
        name: OWNER_CODE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 729ae7d9-68c3-4402-8638-7f725de4972d
          stepCounter: 5ce20cda-94d7-4715-9bfd-b8d0a8516a0c
        config: {}
        dataType: VARCHAR(10)
        defaultValue: ""
        description: Code
        name: CODE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 414e3128-e9ba-42da-b61d-3b81667cd11d
          stepCounter: 5ce20cda-94d7-4715-9bfd-b8d0a8516a0c
        config: {}
        dataType: VARCHAR(40)
        defaultValue: ""
        description: Description
        name: DESCRIPTION
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ea542a1f-b64c-40a9-9f3b-d5eac4f84e7e
          stepCounter: 5ce20cda-94d7-4715-9bfd-b8d0a8516a0c
        config: {}
        dataType: VARCHAR(40)
        defaultValue: ""
        description: Value
        name: VALUE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: bbc149f8-4280-4424-8210-1e72a9f0ae93
          stepCounter: 5ce20cda-94d7-4715-9bfd-b8d0a8516a0c
        config: {}
        dataType: VARCHAR(1)
        defaultValue: ""
        description: AI Status
        name: AI_STATUS
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 714694ab-e56c-4418-87c5-ca0b558ec154
          stepCounter: 5ce20cda-94d7-4715-9bfd-b8d0a8516a0c
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: Last Update User
        name: LAST_UPDATE_USER
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 366aa58e-287b-4167-aa8b-fdfdabe9d14d
          stepCounter: 5ce20cda-94d7-4715-9bfd-b8d0a8516a0c
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Last Update Date
        name: LAST_UPDATE_DATE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: bb90007c-5a69-4c53-9c92-34b50d50a6b5
          stepCounter: 5ce20cda-94d7-4715-9bfd-b8d0a8516a0c
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: Code In Use
        name: CODE_IN_USE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 973b4fa9-c585-4bff-9c5e-ce0c91d27808
          stepCounter: 5ce20cda-94d7-4715-9bfd-b8d0a8516a0c
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: Reserved
        name: RESERVED
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 9dff5906-d6a7-4c90-a20b-10c06dc1a394
          stepCounter: 5ce20cda-94d7-4715-9bfd-b8d0a8516a0c
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 64faccd3-9f38-4982-8ebf-f312fb069b5b
          stepCounter: 5ce20cda-94d7-4715-9bfd-b8d0a8516a0c
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
  name: LOAD_CSLAND_T_RUACONFIG
  schema: ""
  sqlType: Source
  type: sourceInput
  version: 1
type: Node
