fileVersion: 1
id: 22fc3ed3-dc59-4010-8606-e0cfe462fb9b
name: LOAD_MOSAIC_RES_WORKSPACE_SETTINGS
operation:
  config:
    archive_enabled: true
    archive_path: archive
    extlocation: false
    fieldDelim: ~|~
    fieldEnclosed: '"'
    fileFormatType: File Format Values
    filePattern: ''
    fileType: CSV
    inferschema: false
    insertStrategy: INSERT
    intextstage: true
    postSQL: ''
    preSQL: ''
    recDelim: ''
    replaceinvalidcharacters: false
    skipBlankLines: false
    skipHeader: '1'
    stageName: s3_LOAD_MOSAIC_RES_WORKSPACE_SETTINGS
    stageStorageLocationName: DV2_STG
    stripouterarray: false
    subfolder: ''
    testsEnabled: true
    trimSpace: false
    truncateBefore: true
    usevectscan: false
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a8ec1065-ed95-4ca9-8e02-be3701f534df
          stepCounter: 22fc3ed3-dc59-4010-8606-e0cfe462fb9b
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: CURRENT_CASE_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 445a2bbe-8b86-4bdd-a3e2-851f7e25c463
          stepCounter: 22fc3ed3-dc59-4010-8606-e0cfe462fb9b
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: DEFAULT_COMPANY_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0d42612d-0f31-417b-8a41-72737131fc6f
          stepCounter: 22fc3ed3-dc59-4010-8606-e0cfe462fb9b
        config: {}
        dataType: VARCHAR(250)
        defaultValue: ""
        description: ""
        name: DESCRIPTION
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 330caec1-f765-43e3-b1f9-8a4765244bca
          stepCounter: 22fc3ed3-dc59-4010-8606-e0cfe462fb9b
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_BY_USER
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d8da5607-b00b-4532-ad3f-7e623e8ea1b9
          stepCounter: 22fc3ed3-dc59-4010-8606-e0cfe462fb9b
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_DATE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: fa10239b-f7dc-4548-bbf8-142ba8e6eea8
          stepCounter: 22fc3ed3-dc59-4010-8606-e0cfe462fb9b
        config: {}
        dataType: VARCHAR(100)
        defaultValue: ""
        description: ""
        name: NAME
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1acdc3b1-0bd2-4fdd-9fe5-d6be44ebd9fe
          stepCounter: 22fc3ed3-dc59-4010-8606-e0cfe462fb9b
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: PREVIOUS_CASE_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e5e573ce-8705-4c51-b62a-790149f374d8
          stepCounter: 22fc3ed3-dc59-4010-8606-e0cfe462fb9b
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: PRIVATE_FLAG
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 4be11593-55d5-48fb-b7c6-47c50d11a8ca
          stepCounter: 22fc3ed3-dc59-4010-8606-e0cfe462fb9b
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: RESERVE_CAT_GROUP_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b77674fb-68db-434b-a5b2-2c83d292f86b
          stepCounter: 22fc3ed3-dc59-4010-8606-e0cfe462fb9b
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: SEARCH_FILTER_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ce25a85b-8274-43b1-aaa8-0161b1e1eed0
          stepCounter: 22fc3ed3-dc59-4010-8606-e0cfe462fb9b
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: USER_PROFILE_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b25926ab-26b0-47ca-8755-925237d82e50
          stepCounter: 22fc3ed3-dc59-4010-8606-e0cfe462fb9b
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        name: UUID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b64fec01-1eeb-4e48-81a6-d39dfe2056da
          stepCounter: 22fc3ed3-dc59-4010-8606-e0cfe462fb9b
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: WORKBENCH_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 231cf24f-a6bd-4819-9c74-bab2949270fb
          stepCounter: 22fc3ed3-dc59-4010-8606-e0cfe462fb9b
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: WORKSPACE_SETTINGS_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f5ea31e5-7d0a-4de4-a629-482edc2f5792
          stepCounter: 22fc3ed3-dc59-4010-8606-e0cfe462fb9b
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        name: DEFAULT_STATIC_HIERARCHY_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 70a8fbe8-e4be-4205-a6e6-200062b84ce5
          stepCounter: 22fc3ed3-dc59-4010-8606-e0cfe462fb9b
        config: {}
        dataType: VARCHAR(250)
        defaultValue: ""
        description: ""
        name: HIERARCHY_FILTER_NAME
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 73ecd7c6-a69a-4a49-ba72-aa46c3c2d3ee
          stepCounter: 22fc3ed3-dc59-4010-8606-e0cfe462fb9b
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        name: ENTITY_STATE_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ad36e963-5826-4d9d-8967-28f8823fd8cf
          stepCounter: 22fc3ed3-dc59-4010-8606-e0cfe462fb9b
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        name: WORKSPACE_VIEW_TYPE_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7c2ec8d3-1e0c-494d-a44e-221dfc54bbf4
          stepCounter: 22fc3ed3-dc59-4010-8606-e0cfe462fb9b
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        name: PANEL_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f8c7ea56-d604-4790-8e5a-45e7a4e7f497
          stepCounter: 22fc3ed3-dc59-4010-8606-e0cfe462fb9b
        config: {}
        dataType: VARCHAR(200)
        defaultValue: ""
        description: ""
        name: TABLE_COLUMN_SET
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e9b71ee6-4f5b-4ed0-9011-2e1eb443bb31
          stepCounter: 22fc3ed3-dc59-4010-8606-e0cfe462fb9b
        config: {}
        dataType: VARCHAR(200)
        defaultValue: ""
        description: ""
        name: ECONOMIC_COLUMN_SET
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f874cc1b-b9f5-447e-9db3-7045856054d3
          stepCounter: 22fc3ed3-dc59-4010-8606-e0cfe462fb9b
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        name: ICON_CODE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8ffce7ba-9224-4072-8695-56c787ae5302
          stepCounter: 22fc3ed3-dc59-4010-8606-e0cfe462fb9b
        config: {}
        dataType: VARCHAR(250)
        defaultValue: ""
        description: ""
        name: ENTITY_NAME
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f065f9c6-e5cc-48f5-9fed-83a01379e02a
          stepCounter: 22fc3ed3-dc59-4010-8606-e0cfe462fb9b
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: RESERVE_CATEGORY_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1e952538-1d20-4413-a3ee-d13b32dcd877
          stepCounter: 22fc3ed3-dc59-4010-8606-e0cfe462fb9b
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: RECON_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0b1e1a38-d369-474b-91e8-f80321f1e444
          stepCounter: 22fc3ed3-dc59-4010-8606-e0cfe462fb9b
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 964265cc-a1d3-45e6-a856-626fba86eaf1
          stepCounter: 22fc3ed3-dc59-4010-8606-e0cfe462fb9b
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences: []
    enabledColumnTestIDs: []
    sourceMapping: []
  name: LOAD_MOSAIC_RES_WORKSPACE_SETTINGS
  overrideSQL: false
  schema: ""
  sqlType: External:::324
  type: sql
  version: 1
type: Node
