fileVersion: 1
id: b3c7c2e1-fd14-4f16-9a6b-f3b6b36e061c
name: ODS_CSLAND_CS_SECURITY
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1a203121-1e2e-4b00-b662-622619a9f531
          stepCounter: b3c7c2e1-fd14-4f16-9a6b-f3b6b36e061c
        config: {}
        dataType: VARCHAR(30)
        defaultValue: ""
        description: Process Id
        isBusinessKey: true
        name: PROCESS_ID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: cc1f6428-5947-4db9-b989-2af659848dce
                stepCounter: aa12bafd-c812-4daf-9bd2-3760c87cc65f
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 16b99477-f6ae-4948-b000-5169561cb993
          stepCounter: b3c7c2e1-fd14-4f16-9a6b-f3b6b36e061c
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: ab7c3f7f-fda5-42fa-ae97-2355587de54c
                stepCounter: aa12bafd-c812-4daf-9bd2-3760c87cc65f
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8c8bca01-8d75-4ab9-bcb7-407037ee6200
          stepCounter: b3c7c2e1-fd14-4f16-9a6b-f3b6b36e061c
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 02dbfa9c-b31d-400d-adf5-93fa3451d7a8
                stepCounter: aa12bafd-c812-4daf-9bd2-3760c87cc65f
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 38b6b064-9899-4f0b-8bcb-e660488b9eb6
          stepCounter: b3c7c2e1-fd14-4f16-9a6b-f3b6b36e061c
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: Flag field to identify Deleted record
        name: DSS_DELETE_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1cc68c33-705d-405d-92d4-be53e5a45cd6
          stepCounter: b3c7c2e1-fd14-4f16-9a6b-f3b6b36e061c
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Records time when record was set to Delete by the Load process
        name: DSS_DELETE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: aa6f7305-45c2-4c93-8abe-c2fd59ec0fc0
          stepCounter: b3c7c2e1-fd14-4f16-9a6b-f3b6b36e061c
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was created in the data warehouse.
        isSystemCreateDate: true
        name: DSS_CREATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7c9a4c33-1d75-4b57-8e92-602467d9c6bb
          stepCounter: b3c7c2e1-fd14-4f16-9a6b-f3b6b36e061c
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was updated in the data warehouse.
        isSystemUpdateDate: true
        name: DSS_UPDATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          LOAD_CSLAND_CS_SECURITY: aa12bafd-c812-4daf-9bd2-3760c87cc65f
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: TARGET
            nodeName: LOAD_CSLAND_CS_SECURITY
        join:
          joinCondition: FROM {{ ref('TARGET','LOAD_CSLAND_CS_SECURITY') }} LOAD_CSLAND_CS_SECURITY
        name: ODS_CSLAND_CS_SECURITY
        noLinkRefs: []
  name: ODS_CSLAND_CS_SECURITY
  overrideSQL: false
  schema: ""
  sqlType: '38'
  type: sql
  version: 1
type: Node
