fileVersion: 1
id: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
name: LOAD_MOSAIC_CDM_USER_SETTINGS
operation:
  database: ""
  deployEnabled: true
  description: ""
  locationName: TARGET
  metadata:
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b9355faa-4b0e-46db-8a1c-39a36f945e38
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: VARCHAR(150)
        defaultValue: ""
        description: ""
        name: ADDITIONAL_REPORT_TEXT
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 93993115-bbe1-4f3a-afe9-dcf912cd01e5
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: ALTERNATE_LINE_SHADING
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7b3413ac-9f11-46d8-9196-6c744af5ddda
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: BUDGET_MONTH_RANGE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d120830c-c08e-4e67-b768-c463fc31f053
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: BUDGET_YEAR
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 45231bc8-226e-46b6-8be2-f8087f9e7e6c
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: ""
        name: CASH_FLOW_SHORT
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 69bc2629-d898-44ad-bc60-dcbde03778e0
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: VARCHAR(100)
        defaultValue: ""
        description: ""
        name: CORPORATION_NAME
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 40b8a7f0-a437-4c72-b12f-7eca57651d66
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_1
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 4c1090f0-c71f-4b1b-ae43-ef198d06dd53
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_2
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ada69269-a471-48e7-ac4b-8148ec5b2f08
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_3
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 08590338-0506-4c0f-b597-6c3bebb5c0b1
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_4
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6016cba1-b673-4123-8fe9-2f9c120b6b88
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: NUMBER(24)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_5
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 459863e0-4473-475d-afb8-6aeb91d6bca4
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: ECONOMIC_INDICATOR_FLAG
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 922b0446-f019-4700-9685-faa7a9028e7a
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: EXPECTED_VALUES_FLAG
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0369bc5a-6ca6-42a4-9c59-b1d1b863270e
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: RESERVE_BOE_EQUIV_FLAG
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1cb3b641-62ea-4d70-91d9-aabeb5955221
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: USER_SETTINGS_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 2544d3fd-bdc3-49e2-bde4-585f23c50aa8
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: YEARS_REPORTED
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f7b4d52f-3be8-4b4e-9cfe-e92fa832eddc
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: YEARS_REPORTED_BY_MONTH
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: de5d669d-74e2-4bee-af23-915008b96e0b
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_1A
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 47df5608-2ec6-4117-9498-4d497dbffe31
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_2A
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a822e0d3-6aa9-49bc-a177-e4ebd16673d2
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_3A
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 62af1456-f61f-4fea-9c9d-4e05f932a0f1
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_4A
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c65645f7-3e51-4119-adc5-33425365840b
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_1B
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d27d517d-2722-4f22-8547-76d2ef823ac7
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_2B
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f008e2fb-4bfd-484f-b9aa-b862249d8a4f
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_3B
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: dea933cc-2f38-41e6-8cc6-d178b332cc0e
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: ""
        name: VOL_AND_REVENUE_DETAIL_FLAG
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 543a7bb2-36a6-4f45-ad03-7efcf6ef08e4
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: ""
        name: ATAX_PKG_FLAG
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c2677f2a-7d6b-48fd-a722-f50b08068b2c
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: ""
        name: CAPITAL_UNDISCOUNTED_FLAG
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 715364ef-8ad5-46b6-afc2-ad46ac7d5c46
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: ""
        name: FIRST_YR_ANNUAL_PRFRMNC_FLAG
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a6c45729-253a-4fff-8a4c-639f1ae452aa
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: ""
        name: INCLUDE_COVER_PAGE_FLAG
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a6c8f007-e566-41e6-b47e-12af46bcf1ae
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: ""
        name: REPORT_PAGE_NUMBERS
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ccb57bf3-cece-48ed-818d-203f502aa1fe
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: VARCHAR(150)
        defaultValue: ""
        description: ""
        name: ADDITIONAL_REPORT_TEXT_2
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: bd00cf07-99cd-425a-a0c6-1f6910f38dff
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: ""
        name: OVERWRITE_PROD_DATA
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f7b3d19e-d045-49fd-8027-a9df7597a969
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_DATE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: faca1cff-da8f-4e01-afb1-534b97c4d9df
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: VARCHAR(100)
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_BY_USER
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: dda6fcc3-191e-469b-bd32-8429ffd27b9a
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: dc5f38e4-4abf-4428-a61c-f619980d10f0
          stepCounter: 01d76b99-2af7-4e4e-bcbe-d319d71aa704
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
  name: LOAD_MOSAIC_CDM_USER_SETTINGS
  schema: ""
  sqlType: Source
  type: sourceInput
  version: 1
type: Node
