fileVersion: 1
id: 9398afab-340a-4b09-b737-edb0a999b1c5
name: LOAD_QBYTE_SMCONFIGURATION
operation:
  database: ""
  deployEnabled: true
  description: ""
  locationName: TARGET
  metadata:
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: cfac1424-3d7b-42e3-8e4c-060fa753310f
          stepCounter: 9398afab-340a-4b09-b737-edb0a999b1c5
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: ATTRIBUTE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6be9d8a6-ba19-490c-ac61-a70096fe0a56
          stepCounter: 9398afab-340a-4b09-b737-edb0a999b1c5
        config: {}
        dataType: VARCHAR(512)
        defaultValue: ""
        description: ""
        name: VALUE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8920b1b6-47b7-41a7-9d68-b7b9cc60c573
          stepCounter: 9398afab-340a-4b09-b737-edb0a999b1c5
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: fa555704-437d-465b-81a0-c4ddc4a5ac8d
          stepCounter: 9398afab-340a-4b09-b737-edb0a999b1c5
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
  name: LOAD_QBYTE_SMCONFIGURATION
  schema: ""
  sqlType: Source
  type: sourceInput
  version: 1
type: Node
