fileVersion: 1
id: 833c6ae3-5277-47a7-9ee1-443cb11c0201
name: LOAD_CSLAND_CS_SECURITY
operation:
  database: ""
  deployEnabled: true
  description: ""
  locationName: TARGET
  metadata:
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 35cb9cf7-3e3d-4df7-beb4-bca555bf5cbe
          stepCounter: 833c6ae3-5277-47a7-9ee1-443cb11c0201
        config: {}
        dataType: VARCHAR(30)
        defaultValue: ""
        description: Process Id
        name: PROCESS_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5209e34d-8bfe-47ba-8ad3-64faeee0a321
          stepCounter: 833c6ae3-5277-47a7-9ee1-443cb11c0201
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e298a461-022b-4575-ac57-5ef76ea4c26a
          stepCounter: 833c6ae3-5277-47a7-9ee1-443cb11c0201
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
  name: LOAD_CSLAND_CS_SECURITY
  schema: ""
  sqlType: Source
  type: sourceInput
  version: 1
type: Node
