fileVersion: 1
id: e501e470-41fa-4d4a-a81f-6724c3ccb29a
name: LOAD_XSPOC_TBLPOCTYPEAPPLICATIONS
operation:
  config:
    archive_enabled: true
    archive_path: archive
    extlocation: false
    fieldDelim: ~|~
    fieldEnclosed: '"'
    fileFormatType: File Format Values
    filePattern: ''
    fileType: CSV
    inferschema: false
    insertStrategy: INSERT
    intextstage: true
    postSQL: ''
    preSQL: ''
    recDelim: ''
    replaceinvalidcharacters: false
    skipBlankLines: false
    skipHeader: '1'
    stageName: s3_LOAD_XSPOC_TBLPOCTYPEAPPLICATIONS
    stageStorageLocationName: DV2_STG
    stripouterarray: false
    subfolder: ''
    testsEnabled: true
    trimSpace: false
    truncateBefore: true
    usevectscan: false
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0b2af5eb-ffc0-4f8f-aac7-e61886657622
          stepCounter: e501e470-41fa-4d4a-a81f-6724c3ccb29a
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: POCTYPE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6556ad7c-d5ea-45a0-a050-1f57397d15a2
          stepCounter: e501e470-41fa-4d4a-a81f-6724c3ccb29a
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: APPLICATIONID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 81732ed9-f8bf-483d-bfd4-5b7827cb8f07
          stepCounter: e501e470-41fa-4d4a-a81f-6724c3ccb29a
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: ISDEFAULT
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d854f9e0-397c-4b42-970d-f03812e56374
          stepCounter: e501e470-41fa-4d4a-a81f-6724c3ccb29a
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e430ac4c-381e-430f-ac36-740061088eb7
          stepCounter: e501e470-41fa-4d4a-a81f-6724c3ccb29a
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences: []
    enabledColumnTestIDs: []
    sourceMapping: []
  name: LOAD_XSPOC_TBLPOCTYPEAPPLICATIONS
  overrideSQL: false
  schema: ""
  sqlType: External:::324
  type: sql
  version: 1
type: Node
