fileVersion: 1
id: 3c2435bb-fc9b-4a9f-9c88-31ae19aaa617
name: LOAD_QBYTE_OUTGOING_XREF_VALUES
operation:
  config:
    archive_enabled: true
    archive_path: archive
    extlocation: false
    fieldDelim: ~|~
    fieldEnclosed: '"'
    fileFormatType: File Format Values
    filePattern: ''
    fileType: CSV
    inferschema: false
    insertStrategy: INSERT
    intextstage: true
    postSQL: ''
    preSQL: ''
    recDelim: ''
    replaceinvalidcharacters: false
    skipBlankLines: false
    skipHeader: '1'
    stageName: s3_LOAD_QBYTE_OUTGOING_XREF_VALUES
    stageStorageLocationName: DV2_STG
    stripouterarray: false
    subfolder: ''
    testsEnabled: true
    trimSpace: false
    truncateBefore: true
    usevectscan: false
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d8952311-4900-41de-9616-f518797d3f83
          stepCounter: 3c2435bb-fc9b-4a9f-9c88-31ae19aaa617
        config: {}
        dataType: VARCHAR(10)
        defaultValue: ""
        description: A code to indicate the type of value being cross-referenced. e.g. account, cost centre, AFE, associate, etc.
        name: XREF_VALUE_TYPE_CODE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8c0a8642-c40d-439f-95a0-c2fd00f00f73
          stepCounter: 3c2435bb-fc9b-4a9f-9c88-31ae19aaa617
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: The first element of the PW*Sequel code value.
        name: PWSQL_VALUE_1
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 45a38f24-8bfa-4b96-90f1-97d9d1515537
          stepCounter: 3c2435bb-fc9b-4a9f-9c88-31ae19aaa617
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: The second element of the PW*Sequel code value.
        name: PWSQL_VALUE_2
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3224c3dc-d163-44ed-ae21-7c09db859fac
          stepCounter: 3c2435bb-fc9b-4a9f-9c88-31ae19aaa617
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: The third element of the PW*Sequel code value.
        name: PWSQL_VALUE_3
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: dbe46be1-e1b3-4bf9-851a-5c0bc62310d6
          stepCounter: 3c2435bb-fc9b-4a9f-9c88-31ae19aaa617
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: The fourth element of the PW*Sequel code value.
        name: PWSQL_VALUE_4
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 244762ef-90a8-4f18-8aab-0ef73b1b0a8b
          stepCounter: 3c2435bb-fc9b-4a9f-9c88-31ae19aaa617
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: The first element of the destination system code value.
        name: DEST_VALUE_1
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 48319b31-1127-485d-b8ad-5df934c75a86
          stepCounter: 3c2435bb-fc9b-4a9f-9c88-31ae19aaa617
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: The second element of the destination system code value.
        name: DEST_VALUE_2
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6b864aef-b92a-49cd-8fbc-bdd3dd0c0934
          stepCounter: 3c2435bb-fc9b-4a9f-9c88-31ae19aaa617
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: The third element of the destination system code value.
        name: DEST_VALUE_3
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 9d4dbd58-3273-4784-b094-d4a07745e11e
          stepCounter: 3c2435bb-fc9b-4a9f-9c88-31ae19aaa617
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: The fourth element of the destination system code value.
        name: DEST_VALUE_4
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 82db1f32-d22e-459f-a708-25263a6aa3b0
          stepCounter: 3c2435bb-fc9b-4a9f-9c88-31ae19aaa617
        config: {}
        dataType: VARCHAR(30)
        defaultValue: ""
        description: The user who created the record.
        name: CREATE_USER
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 74dc280e-1340-4543-bab0-1cdb5b4625e5
          stepCounter: 3c2435bb-fc9b-4a9f-9c88-31ae19aaa617
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: The date the record was created.
        name: CREATE_DATE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 231cb365-ab83-4360-81d5-66ca817e7c34
          stepCounter: 3c2435bb-fc9b-4a9f-9c88-31ae19aaa617
        config: {}
        dataType: VARCHAR(30)
        defaultValue: ""
        description: The user who last updated the record.
        name: LAST_UPDATE_USER
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f952fab9-ca3d-46a0-8ebb-7626e0c123bf
          stepCounter: 3c2435bb-fc9b-4a9f-9c88-31ae19aaa617
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: The date the record was last updated.
        name: LAST_UPDATE_DATE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 72f86fa9-449f-4c85-a973-3c54360e69ff
          stepCounter: 3c2435bb-fc9b-4a9f-9c88-31ae19aaa617
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 973d4e8f-1e07-4f61-9ab2-64aa527c2394
          stepCounter: 3c2435bb-fc9b-4a9f-9c88-31ae19aaa617
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences: []
    enabledColumnTestIDs: []
    sourceMapping: []
  name: LOAD_QBYTE_OUTGOING_XREF_VALUES
  overrideSQL: false
  schema: ""
  sqlType: External:::324
  type: sql
  version: 1
type: Node
