fileVersion: 1
id: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
name: LOAD_MOSAIC_CDM_USER_SETTINGS
operation:
  config:
    archive_enabled: true
    archive_path: archive
    extlocation: false
    fieldDelim: ~|~
    fieldEnclosed: '"'
    fileFormatType: File Format Values
    filePattern: ''
    fileType: CSV
    inferschema: false
    insertStrategy: INSERT
    intextstage: true
    postSQL: ''
    preSQL: ''
    recDelim: ''
    replaceinvalidcharacters: false
    skipBlankLines: false
    skipHeader: '1'
    stageName: s3_LOAD_MOSAIC_CDM_USER_SETTINGS
    stageStorageLocationName: DV2_STG
    stripouterarray: false
    subfolder: ''
    testsEnabled: true
    trimSpace: false
    truncateBefore: true
    usevectscan: false
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 502a6b1e-3a98-48a2-8a0b-1a8b3c1a4c00
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: VARCHAR(150)
        defaultValue: ""
        description: ""
        name: ADDITIONAL_REPORT_TEXT
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 4b3ab0cf-71c6-4f5a-a38e-38cb27cfd69d
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: ALTERNATE_LINE_SHADING
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 44ad5011-46d3-41b8-8ff4-1c67ac2b7600
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: BUDGET_MONTH_RANGE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3a0b0664-04d2-4b27-9c8b-4f959a21595e
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: BUDGET_YEAR
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c4787b5b-c94c-426a-b411-9cc36c2e2d3d
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: ""
        name: CASH_FLOW_SHORT
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 2ec48645-774d-4af9-91db-3a389539bb58
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: VARCHAR(100)
        defaultValue: ""
        description: ""
        name: CORPORATION_NAME
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f0360331-f844-46d0-9a62-fb363f7e419b
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_1
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 9d54105e-43b5-401e-85be-0f6179242c70
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_2
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 60252324-84d8-472e-821f-9920e67f05df
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_3
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7e88236d-6906-4b1c-ae1b-d784acca5c61
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_4
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 817308a0-e2ff-4de4-807b-5baf81934b11
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: NUMBER(24)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_5
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: da454e03-9006-49e7-9034-4ec985f1b2e1
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: ECONOMIC_INDICATOR_FLAG
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1b170ff5-89cf-481e-82a0-087d686cdad1
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: EXPECTED_VALUES_FLAG
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 9c1e899c-951b-4a5a-a5c6-6352fab913fb
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: RESERVE_BOE_EQUIV_FLAG
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 381210f7-d505-40f9-9879-452331019942
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: USER_SETTINGS_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b1fa204c-f607-46a1-b46b-7648645ae70d
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: YEARS_REPORTED
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 90d031ea-6acd-4d2b-8cf7-b4fa408a7bdf
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: YEARS_REPORTED_BY_MONTH
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: cf268d23-cde4-4f38-8dc8-ddfa8c1032f1
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_1A
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 427a9f62-a680-43c3-bbe7-72b1a94c299f
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_2A
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1de29b01-442c-4016-bd37-7ff7b84efbe5
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_3A
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b85ffb99-c8ad-4bc6-bf44-2ed93149aa76
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_4A
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ef12dc9a-0df2-4f99-99f3-ce61e317d202
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_1B
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3db482c6-e8ab-4acf-a1db-4fca52963961
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_2B
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 27b5f790-5f1e-4273-aa8b-1b7c96fcb93c
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: NUMBER(24,8)
        defaultValue: ""
        description: ""
        name: DISCOUNT_RATE_3B
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: eca971fe-8d89-45e8-a56d-4ea71d0c018a
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: ""
        name: VOL_AND_REVENUE_DETAIL_FLAG
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: cc1f1d0d-066c-4b2a-b253-2d93bdcc2564
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: ""
        name: ATAX_PKG_FLAG
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 15fee720-633f-459d-86f8-858a3bf62850
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: ""
        name: CAPITAL_UNDISCOUNTED_FLAG
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e1fac04c-208b-425c-82f5-117145a43c24
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: ""
        name: FIRST_YR_ANNUAL_PRFRMNC_FLAG
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f456f70b-fca1-4ee8-9da3-214c468e2b9a
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: ""
        name: INCLUDE_COVER_PAGE_FLAG
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1e7a3a2d-d4e8-4027-9d6c-b43dd245c0df
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: ""
        name: REPORT_PAGE_NUMBERS
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a2cf7395-5d15-4422-944f-9d6fafc1d8a0
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: VARCHAR(150)
        defaultValue: ""
        description: ""
        name: ADDITIONAL_REPORT_TEXT_2
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0f2100da-db65-4698-a368-e69e00731b70
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: NUMBER(1)
        defaultValue: ""
        description: ""
        name: OVERWRITE_PROD_DATA
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6061cfa6-bf57-4a18-bc36-2b8af6dcce41
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_DATE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 044c0e08-4f18-4498-bbda-6a0fa4f8e714
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: VARCHAR(100)
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_BY_USER
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b2809c4d-dd48-4e81-b7ba-20d2c3b91ba1
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a2b8d17f-c9d3-427e-b713-6db2a6645ee1
          stepCounter: 04b6dfcd-e63c-4ad9-b81a-a89d9292c58a
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences: []
    enabledColumnTestIDs: []
    sourceMapping: []
  name: LOAD_MOSAIC_CDM_USER_SETTINGS
  overrideSQL: false
  schema: ""
  sqlType: External:::324
  type: sql
  version: 1
type: Node
