fileVersion: 1
id: 748221b5-bfc5-4899-9473-2e98369697ae
name: ODS_XSPOC_TBLUSERSECURITY
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 9c2f132d-b20b-42bd-b0bc-d6e545b78731
          stepCounter: 748221b5-bfc5-4899-9473-2e98369697ae
        config: {}
        dataType: VARCHAR(100)
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: USERNAME
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: ff0c8c88-73a1-48c7-9b40-b675f79b9c95
                stepCounter: da992862-35a1-4c3a-900c-5dc53d3bb22f
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: efce662c-dd0d-4d01-887f-faeb2ef41450
          stepCounter: 748221b5-bfc5-4899-9473-2e98369697ae
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: WELLCONTROL
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 1b1db2eb-4dff-4da6-995a-822a5b8d0262
                stepCounter: da992862-35a1-4c3a-900c-5dc53d3bb22f
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 23decf78-1763-43a2-974e-a4e02578010a
          stepCounter: 748221b5-bfc5-4899-9473-2e98369697ae
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: WELLCONFIG
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 84c9eef1-9b79-4d88-b1c7-12cb6bdc4d04
                stepCounter: da992862-35a1-4c3a-900c-5dc53d3bb22f
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a6d7e5a1-9664-4671-bcaf-8e2738bf152d
          stepCounter: 748221b5-bfc5-4899-9473-2e98369697ae
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: ADMIN
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 0ab78be9-9f7a-4f7a-a384-a08c323c6b03
                stepCounter: da992862-35a1-4c3a-900c-5dc53d3bb22f
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ea77e99d-fe3e-419c-9eba-e9864fd72400
          stepCounter: 748221b5-bfc5-4899-9473-2e98369697ae
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: ADMINLITE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: d682a47c-2768-464d-bdee-83f490b6c969
                stepCounter: da992862-35a1-4c3a-900c-5dc53d3bb22f
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b38f909b-5e43-4c6c-a60c-b62b20a3c8c0
          stepCounter: 748221b5-bfc5-4899-9473-2e98369697ae
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: WELLADMIN
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: c22b5a66-deb1-41aa-835a-1d5b51a65bfa
                stepCounter: da992862-35a1-4c3a-900c-5dc53d3bb22f
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 086f58aa-b673-4c46-a80a-5d6b6e6d8f94
          stepCounter: 748221b5-bfc5-4899-9473-2e98369697ae
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: WELLCONFIGLITE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 6c46f201-ddd9-4635-8859-890e34eb878a
                stepCounter: da992862-35a1-4c3a-900c-5dc53d3bb22f
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 2ab6208b-2ac8-490a-b955-1dca0a85093e
          stepCounter: 748221b5-bfc5-4899-9473-2e98369697ae
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: PASSWORD
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: e3c85fe4-ed84-4f69-9dd0-de29ef3a7879
                stepCounter: da992862-35a1-4c3a-900c-5dc53d3bb22f
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 11165a37-71a7-4517-ae74-90dec37509a5
          stepCounter: 748221b5-bfc5-4899-9473-2e98369697ae
        config: {}
        dataType: VARCHAR(100)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: EMAIL
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 4146161b-8846-4e42-b7e2-532dd129e1eb
                stepCounter: da992862-35a1-4c3a-900c-5dc53d3bb22f
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e252e5c4-dfec-4e22-8eaf-d6d2daa4795d
          stepCounter: 748221b5-bfc5-4899-9473-2e98369697ae
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: LASTACCESSDATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 5e46c5b3-762f-4ad2-b90e-c2c7df0b7bb2
                stepCounter: da992862-35a1-4c3a-900c-5dc53d3bb22f
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1dfd0496-5eb7-44a5-8d10-9d41110dfbfe
          stepCounter: 748221b5-bfc5-4899-9473-2e98369697ae
        config: {}
        dataType: VARCHAR(36)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: WEBTOKEN
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: cf37e2ae-5769-484d-ad59-d3a35e1c9b86
                stepCounter: da992862-35a1-4c3a-900c-5dc53d3bb22f
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5b16ff61-63a9-473f-b5e3-5201c0292e44
          stepCounter: 748221b5-bfc5-4899-9473-2e98369697ae
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: WEBTOKENEXPIRE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: f4448523-6c6f-48fa-923e-bffcb80fe982
                stepCounter: da992862-35a1-4c3a-900c-5dc53d3bb22f
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f122aac0-5448-4e98-932f-914a4967af47
          stepCounter: 748221b5-bfc5-4899-9473-2e98369697ae
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: MUSTCHANGEPASSWORD
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 72c9963b-bd4c-4614-96b4-3dc4167a3233
                stepCounter: da992862-35a1-4c3a-900c-5dc53d3bb22f
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ac52ab02-d8e3-47f7-b543-e0d60d8dd63f
          stepCounter: 748221b5-bfc5-4899-9473-2e98369697ae
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 5ca56b87-92c8-4d0a-981a-6faa24a462c9
                stepCounter: da992862-35a1-4c3a-900c-5dc53d3bb22f
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e404ab3b-5dc2-444d-8bd8-eff5baf9b924
          stepCounter: 748221b5-bfc5-4899-9473-2e98369697ae
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: f370be1d-db84-4308-97a6-b1ce000e51fc
                stepCounter: da992862-35a1-4c3a-900c-5dc53d3bb22f
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 18f8a3e6-37fd-4362-a30d-bec013aeeba8
          stepCounter: 748221b5-bfc5-4899-9473-2e98369697ae
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: Flag field to identify Deleted record
        name: DSS_DELETE_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 94d33cde-a9c3-4a8d-9bcf-57a1ab033948
          stepCounter: 748221b5-bfc5-4899-9473-2e98369697ae
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Records time when record was set to Delete by the Load process
        name: DSS_DELETE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3e295547-2298-482a-b0e2-deda3141f6b0
          stepCounter: 748221b5-bfc5-4899-9473-2e98369697ae
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Datetime a business key was started.
        isSystemStartDate: true
        name: DSS_START_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7d252514-189a-4c1f-af4a-9f7bcf6720fc
          stepCounter: 748221b5-bfc5-4899-9473-2e98369697ae
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Datetime a business key was retired.
        isSystemEndDate: true
        name: DSS_END_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 220a4627-81f8-47af-8c4b-cbda2078d68c
          stepCounter: 748221b5-bfc5-4899-9473-2e98369697ae
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: Flag to indicate the current (latest) version of a business key.
        isSystemCurrentFlag: true
        name: DSS_CURRENT_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8931c2ed-ff16-4a7f-88c5-7a5d3afb7d54
          stepCounter: 748221b5-bfc5-4899-9473-2e98369697ae
        config: {}
        dataType: INTEGER
        defaultValue: ""
        description: Version number of a business key.
        isSystemVersion: true
        name: DSS_VERSION
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 07b3e360-838e-49a2-99db-b2bb469b10ea
          stepCounter: 748221b5-bfc5-4899-9473-2e98369697ae
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was created in the data warehouse.
        isSystemCreateDate: true
        name: DSS_CREATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 9f41f032-3427-48af-bd7c-c745a3e5db18
          stepCounter: 748221b5-bfc5-4899-9473-2e98369697ae
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was updated in the data warehouse.
        isSystemUpdateDate: true
        name: DSS_UPDATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          LOAD_XSPOC_TBLUSERSECURITY: da992862-35a1-4c3a-900c-5dc53d3bb22f
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: TARGET
            nodeName: LOAD_XSPOC_TBLUSERSECURITY
        join:
          joinCondition: FROM {{ ref('TARGET','LOAD_XSPOC_TBLUSERSECURITY') }} LOAD_XSPOC_TBLUSERSECURITY
        name: ODS_XSPOC_TBLUSERSECURITY
        noLinkRefs: []
  name: ODS_XSPOC_TBLUSERSECURITY
  overrideSQL: false
  schema: ""
  sqlType: '38'
  type: sql
  version: 1
type: Node
