fileVersion: 1
id: b366fa41-2e0e-4565-b1b7-b613b4adf2b1
name: ODS_XSPOC_TBLCAMERACONFIGURATIONS
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0737516a-d639-4327-aa87-117504f099b2
          stepCounter: b366fa41-2e0e-4565-b1b7-b613b4adf2b1
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: ID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: c6e6ac8f-d11b-4244-aef6-8e4b1c5e72bb
                stepCounter: 1b5007b0-3a6d-499b-9542-3166a3b536a5
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6f170fe1-d67c-4430-90dd-3819ce706470
          stepCounter: b366fa41-2e0e-4565-b1b7-b613b4adf2b1
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: DESCRIPTION
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 37366d72-5bc0-43cb-9a09-2adbfd5bb15c
                stepCounter: 1b5007b0-3a6d-499b-9542-3166a3b536a5
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: dae52352-bce6-4fea-8f8f-684a790f24b1
          stepCounter: b366fa41-2e0e-4565-b1b7-b613b4adf2b1
        config: {}
        dataType: VARCHAR(200)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: FORMATSTRINGVIDEO
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: f66df2da-d84f-4bfa-ab3c-983d27f1da9c
                stepCounter: 1b5007b0-3a6d-499b-9542-3166a3b536a5
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5fa76c94-0f01-4d56-8a1c-cec63d66dd4b
          stepCounter: b366fa41-2e0e-4565-b1b7-b613b4adf2b1
        config: {}
        dataType: VARCHAR(200)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: FORMATSTRINGSNAPSHOT
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 0fcbdc75-61df-432d-aef1-b5ea290010c3
                stepCounter: 1b5007b0-3a6d-499b-9542-3166a3b536a5
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: fd76b361-325d-4a59-8e6b-4dc8f2708562
          stepCounter: b366fa41-2e0e-4565-b1b7-b613b4adf2b1
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: SNAPSHOTURIHTTPAUTHENTICATION
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 822dd22b-f465-4874-82e2-5f52d8ad5a23
                stepCounter: 1b5007b0-3a6d-499b-9542-3166a3b536a5
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 473fa3a9-cf89-492c-80e7-b6abad1a4363
          stepCounter: b366fa41-2e0e-4565-b1b7-b613b4adf2b1
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: dc8ab898-2275-44d9-9b02-464863aada01
                stepCounter: 1b5007b0-3a6d-499b-9542-3166a3b536a5
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 651b4942-0ccb-4949-adb6-7cafad75ab8c
          stepCounter: b366fa41-2e0e-4565-b1b7-b613b4adf2b1
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 5e326146-1148-432d-a82c-1c3fd1f5c45f
                stepCounter: 1b5007b0-3a6d-499b-9542-3166a3b536a5
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6ec2e9b4-cb0e-4883-ae58-425b93a5fbce
          stepCounter: b366fa41-2e0e-4565-b1b7-b613b4adf2b1
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: Flag field to identify Deleted record
        name: DSS_DELETE_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 616015aa-0426-4216-afca-6b2ef335c9a1
          stepCounter: b366fa41-2e0e-4565-b1b7-b613b4adf2b1
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Records time when record was set to Delete by the Load process
        name: DSS_DELETE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7d41f4a5-e04d-4041-aa7c-ec8096e74cd5
          stepCounter: b366fa41-2e0e-4565-b1b7-b613b4adf2b1
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Datetime a business key was started.
        isSystemStartDate: true
        name: DSS_START_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 985ddc3d-089d-4aaf-acfa-b864d5d529af
          stepCounter: b366fa41-2e0e-4565-b1b7-b613b4adf2b1
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Datetime a business key was retired.
        isSystemEndDate: true
        name: DSS_END_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: facb975b-1188-4ef5-aad8-5e0b2d40fa7e
          stepCounter: b366fa41-2e0e-4565-b1b7-b613b4adf2b1
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: Flag to indicate the current (latest) version of a business key.
        isSystemCurrentFlag: true
        name: DSS_CURRENT_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b9a02a38-0710-4c72-88b4-65efcf72d1e4
          stepCounter: b366fa41-2e0e-4565-b1b7-b613b4adf2b1
        config: {}
        dataType: INTEGER
        defaultValue: ""
        description: Version number of a business key.
        isSystemVersion: true
        name: DSS_VERSION
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 9daa2192-2ac2-4469-89c6-3a13802c8bcf
          stepCounter: b366fa41-2e0e-4565-b1b7-b613b4adf2b1
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was created in the data warehouse.
        isSystemCreateDate: true
        name: DSS_CREATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ec26d59e-63ad-43f8-86a5-397b28b6cd73
          stepCounter: b366fa41-2e0e-4565-b1b7-b613b4adf2b1
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was updated in the data warehouse.
        isSystemUpdateDate: true
        name: DSS_UPDATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          LOAD_XSPOC_TBLCAMERACONFIGURATIONS: 1b5007b0-3a6d-499b-9542-3166a3b536a5
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: TARGET
            nodeName: LOAD_XSPOC_TBLCAMERACONFIGURATIONS
        join:
          joinCondition: FROM {{ ref('TARGET','LOAD_XSPOC_TBLCAMERACONFIGURATIONS') }} LOAD_XSPOC_TBLCAMERACONFIGURATIONS
        name: ODS_XSPOC_TBLCAMERACONFIGURATIONS
        noLinkRefs: []
  name: ODS_XSPOC_TBLCAMERACONFIGURATIONS
  overrideSQL: false
  schema: ""
  sqlType: '38'
  type: sql
  version: 1
type: Node
