fileVersion: 1
id: a65d44f6-5064-4770-845e-903e6b24356f
name: LOAD_XSPOC_TBLALARMCONFIGBYPOCTYPE
operation:
  config:
    archive_enabled: true
    archive_path: archive
    extlocation: false
    fieldDelim: ~|~
    fieldEnclosed: '"'
    fileFormatType: File Format Values
    filePattern: ''
    fileType: CSV
    inferschema: false
    insertStrategy: INSERT
    intextstage: true
    postSQL: ''
    preSQL: ''
    recDelim: ''
    replaceinvalidcharacters: false
    skipBlankLines: false
    skipHeader: '1'
    stageName: s3_LOAD_XSPOC_TBLALARMCONFIGBYPOCTYPE
    stageStorageLocationName: DV2_STG
    stripouterarray: false
    subfolder: ''
    testsEnabled: true
    trimSpace: false
    truncateBefore: true
    usevectscan: false
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c337f774-94dd-4f5d-84b9-4f044e6a6b68
          stepCounter: a65d44f6-5064-4770-845e-903e6b24356f
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: POCTYPE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 41feccec-d8ad-4ca7-af6a-6ff11d808fe5
          stepCounter: a65d44f6-5064-4770-845e-903e6b24356f
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: REGISTER
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b66cce14-3c64-49e2-bd47-d5ab35f47339
          stepCounter: a65d44f6-5064-4770-845e-903e6b24356f
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: BIT
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 85fb0f45-c8a5-4bb0-9b73-938a6e7e5adc
          stepCounter: a65d44f6-5064-4770-845e-903e6b24356f
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        name: DESCRIPTION
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: dae58b46-fadd-4743-8aa8-40c1f6550521
          stepCounter: a65d44f6-5064-4770-845e-903e6b24356f
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: PHRASEID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3afaebc1-5a1e-4fa0-a3a4-b55371e43c97
          stepCounter: a65d44f6-5064-4770-845e-903e6b24356f
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: PRIORITY
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 2ca7b6cd-6f34-4723-b560-d9bd8b9a6346
          stepCounter: a65d44f6-5064-4770-845e-903e6b24356f
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: CALLOUTENABLED
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 02f39abe-c832-4c00-8233-224e52a63473
          stepCounter: a65d44f6-5064-4770-845e-903e6b24356f
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: ENABLED
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7131e34b-1cb7-4552-9069-4b6b9cc4469c
          stepCounter: a65d44f6-5064-4770-845e-903e6b24356f
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: NORMALSTATE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 03104a3b-5ec3-4ef2-b3e7-4b533474af32
          stepCounter: a65d44f6-5064-4770-845e-903e6b24356f
        config: {}
        dataType: FLOAT
        defaultValue: ""
        description: ""
        name: LOLIMIT
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5c679bfd-82c3-4761-8a68-0301dacbc9fa
          stepCounter: a65d44f6-5064-4770-845e-903e6b24356f
        config: {}
        dataType: FLOAT
        defaultValue: ""
        description: ""
        name: HILIMIT
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 82344492-3a9f-45ec-9ac9-9613ef16faeb
          stepCounter: a65d44f6-5064-4770-845e-903e6b24356f
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: LOCKED
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c2444b72-7107-43f6-80b1-56fdbde9805e
          stepCounter: a65d44f6-5064-4770-845e-903e6b24356f
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: ALARMACTION
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3c5a9993-2f86-468c-9b59-1b6517e0532c
          stepCounter: a65d44f6-5064-4770-845e-903e6b24356f
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: cb013f3e-1884-448d-8bc0-57cb8d57162e
          stepCounter: a65d44f6-5064-4770-845e-903e6b24356f
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences: []
    enabledColumnTestIDs: []
    sourceMapping: []
  name: LOAD_XSPOC_TBLALARMCONFIGBYPOCTYPE
  overrideSQL: false
  schema: ""
  sqlType: External:::324
  type: sql
  version: 1
type: Node
