fileVersion: 1
id: 41d26381-6e2a-402f-a488-eee4b97f3886
name: LOAD_XSPOC_TBLIPRWELLCONFIG
operation:
  database: ""
  deployEnabled: true
  description: ""
  locationName: TARGET
  metadata:
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8276db68-fd87-4cb3-8ce2-c97f4668ad6d
          stepCounter: 41d26381-6e2a-402f-a488-eee4b97f3886
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        name: NODEID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5fddde9d-86c5-462d-b07a-dcb9659e364a
          stepCounter: 41d26381-6e2a-402f-a488-eee4b97f3886
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        name: TESTDATE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 4ff5ef0e-84bb-4767-bf3e-98708cbfa42a
          stepCounter: 41d26381-6e2a-402f-a488-eee4b97f3886
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: ANALYSISCORRELATIONID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5ccbe43d-71cf-4f26-ade4-69d6a1461896
          stepCounter: 41d26381-6e2a-402f-a488-eee4b97f3886
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: FBHPANALYSISSOURCEID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 60c5aea2-31da-4fa6-8288-63cf01f75725
          stepCounter: 41d26381-6e2a-402f-a488-eee4b97f3886
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: GROSSRATEANALYSISSOURCEID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d43cb732-e135-4fcb-a6f0-1687c6c73944
          stepCounter: 41d26381-6e2a-402f-a488-eee4b97f3886
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: WATERCUTANALYSISSOURCEID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d062e709-f523-4bfe-b001-b3962624512a
          stepCounter: 41d26381-6e2a-402f-a488-eee4b97f3886
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e41947f0-b4dc-408f-bc02-509ae3d39e63
          stepCounter: 41d26381-6e2a-402f-a488-eee4b97f3886
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
  name: LOAD_XSPOC_TBLIPRWELLCONFIG
  schema: ""
  sqlType: Source
  type: sourceInput
  version: 1
type: Node
