fileVersion: 1
id: e59b307c-9b8c-4317-8df2-0173eb6afe00
name: ODS_QBYTE_INCOMING_XREF_VALUES
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
    truncateBefore: true
  database: ""
  deployEnabled: true
  description: "This is a table without unique tracking keys. It is set to truncate before every load (Full load)"
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f9d2b28d-7559-4f58-9267-1f0a2a37a01b
          stepCounter: e59b307c-9b8c-4317-8df2-0173eb6afe00
        config: {}
        dataType: VARCHAR(10)
        defaultValue: ""
        description: A code to indicate the type of value being cross-referenced.  e.g. account, cost centre, AFE, associate, etc.
        isBusinessKey: true
        name: XREF_VALUE_TYPE_CODE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 563cf69d-b7c4-49f5-ae89-45c7d4149fbd
                stepCounter: d2c1231e-7f31-4587-9f63-3076f4ad660c
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 955597ff-d634-4c8c-b4ea-da46bdb8705d
          stepCounter: e59b307c-9b8c-4317-8df2-0173eb6afe00
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: The first element of the incoming code value.
        isBusinessKey: true
        name: SOURCE_VALUE_1
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 649483f4-b3f8-4e22-b715-51de44aff278
                stepCounter: d2c1231e-7f31-4587-9f63-3076f4ad660c
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e11a571e-e6d2-4c39-8159-3e57a83b57b7
          stepCounter: e59b307c-9b8c-4317-8df2-0173eb6afe00
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: The second element of the incoming code value.
        isChangeTracking: true
        name: SOURCE_VALUE_2
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 270cd99c-3132-4746-bbcb-f6abcf820fab
                stepCounter: d2c1231e-7f31-4587-9f63-3076f4ad660c
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f03f28ee-1a6d-4c43-9174-11fb7df14882
          stepCounter: e59b307c-9b8c-4317-8df2-0173eb6afe00
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: The third element of the incoming code value.
        isChangeTracking: true
        name: SOURCE_VALUE_3
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: c27d64f9-97ab-44ca-916f-6c4edd8cbe3f
                stepCounter: d2c1231e-7f31-4587-9f63-3076f4ad660c
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e363d379-be29-45ac-833a-5e61fb2d08af
          stepCounter: e59b307c-9b8c-4317-8df2-0173eb6afe00
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: The fourth element of the incoming code value.
        isChangeTracking: true
        name: SOURCE_VALUE_4
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 4b958651-8e0e-48fd-934d-07159e599dca
                stepCounter: d2c1231e-7f31-4587-9f63-3076f4ad660c
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: bdd67668-d510-450a-b985-7c53f71aee1d
          stepCounter: e59b307c-9b8c-4317-8df2-0173eb6afe00
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: The first element of the PW*Sequel code value.
        isBusinessKey: true
        name: PWSQL_VALUE_1
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 2a02f2db-dc9b-41e1-bd99-9710b6e3413c
                stepCounter: d2c1231e-7f31-4587-9f63-3076f4ad660c
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 67092ba6-641a-4aa6-8534-3ba54e0eed80
          stepCounter: e59b307c-9b8c-4317-8df2-0173eb6afe00
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: The second element of the PW*Sequel code value.
        isChangeTracking: true
        name: PWSQL_VALUE_2
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: c33016ef-5aee-4a44-a13f-655f26af4c30
                stepCounter: d2c1231e-7f31-4587-9f63-3076f4ad660c
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 785db3c8-99ea-45d3-b7f0-af6d49ec8313
          stepCounter: e59b307c-9b8c-4317-8df2-0173eb6afe00
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: The third element of the PW*Sequel code value.
        isChangeTracking: true
        name: PWSQL_VALUE_3
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: eebf8023-4d3b-44e1-8eaf-fbcd47aa6f09
                stepCounter: d2c1231e-7f31-4587-9f63-3076f4ad660c
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 15b38be5-bc56-4f65-b375-ae56ce3b4f61
          stepCounter: e59b307c-9b8c-4317-8df2-0173eb6afe00
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: The fourth element of the PW*Sequel code value.
        isChangeTracking: true
        name: PWSQL_VALUE_4
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 3fc5da4d-cc74-4304-a022-557d288855f6
                stepCounter: d2c1231e-7f31-4587-9f63-3076f4ad660c
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: dc95a4ae-cae7-4650-bf79-8b577b32fad4
          stepCounter: e59b307c-9b8c-4317-8df2-0173eb6afe00
        config: {}
        dataType: VARCHAR(30)
        defaultValue: ""
        description: The user who created the record.
        isBusinessKey: true
        name: CREATE_USER
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: aba437d4-8229-47b0-a12f-f555f71c06c9
                stepCounter: d2c1231e-7f31-4587-9f63-3076f4ad660c
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 464fe345-4f1e-4c7d-9653-3162eb576218
          stepCounter: e59b307c-9b8c-4317-8df2-0173eb6afe00
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: The date the record was created.
        isBusinessKey: true
        name: CREATE_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: ab216108-3a66-43a8-9fcf-d345e8e7521b
                stepCounter: d2c1231e-7f31-4587-9f63-3076f4ad660c
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 4cc0a9d4-c234-48b4-8119-4afde9a63a0a
          stepCounter: e59b307c-9b8c-4317-8df2-0173eb6afe00
        config: {}
        dataType: VARCHAR(30)
        defaultValue: ""
        description: The user who last updated the record.
        isBusinessKey: true
        name: LAST_UPDATE_USER
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: d5f342f3-c2b1-4c4e-a734-5605e35d3732
                stepCounter: d2c1231e-7f31-4587-9f63-3076f4ad660c
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: bb8fa25d-2b4d-4b4b-b441-586456153b77
          stepCounter: e59b307c-9b8c-4317-8df2-0173eb6afe00
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: The date the record was last updated.
        isBusinessKey: true
        name: LAST_UPDATE_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 3b02c395-c6dd-429c-bc70-c139a0ff3db1
                stepCounter: d2c1231e-7f31-4587-9f63-3076f4ad660c
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e3ae42c1-3015-462d-9e64-74519b0a9513
          stepCounter: e59b307c-9b8c-4317-8df2-0173eb6afe00
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: de21839c-8a7d-44b2-b721-390a59b847fb
                stepCounter: d2c1231e-7f31-4587-9f63-3076f4ad660c
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0ed06f8e-8fa5-4e37-8b0b-dbb4f5759f2b
          stepCounter: e59b307c-9b8c-4317-8df2-0173eb6afe00
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 4999e1b0-3b39-493f-b801-7a295aac3e54
                stepCounter: d2c1231e-7f31-4587-9f63-3076f4ad660c
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 78dd3ec4-ded3-4e45-8e35-64fa6bd98a0e
          stepCounter: e59b307c-9b8c-4317-8df2-0173eb6afe00
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: Flag field to identify Deleted record
        name: DSS_DELETE_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: dabe4e53-a7fb-42fb-b159-6eea452602f8
          stepCounter: e59b307c-9b8c-4317-8df2-0173eb6afe00
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Records time when record was set to Delete by the Load process
        name: DSS_DELETE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6b622de6-32f3-47cf-b41d-b3d86546a120
          stepCounter: e59b307c-9b8c-4317-8df2-0173eb6afe00
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Datetime a business key was started.
        isSystemStartDate: true
        name: DSS_START_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 401bdc23-c1f0-4db9-a2af-ca3d36ce9406
          stepCounter: e59b307c-9b8c-4317-8df2-0173eb6afe00
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Datetime a business key was retired.
        isSystemEndDate: true
        name: DSS_END_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ba8102bc-a0a9-4ac4-8f33-ae9de16c9cea
          stepCounter: e59b307c-9b8c-4317-8df2-0173eb6afe00
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: Flag to indicate the current (latest) version of a business key.
        isSystemCurrentFlag: true
        name: DSS_CURRENT_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e8cbee12-d5be-4ae2-a20f-d5b5cbbe8eeb
          stepCounter: e59b307c-9b8c-4317-8df2-0173eb6afe00
        config: {}
        dataType: INTEGER
        defaultValue: ""
        description: Version number of a business key.
        isSystemVersion: true
        name: DSS_VERSION
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 83845b98-3a9e-4273-8a0f-9668b443872e
          stepCounter: e59b307c-9b8c-4317-8df2-0173eb6afe00
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was created in the data warehouse.
        isSystemCreateDate: true
        name: DSS_CREATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 723bfa5a-5890-41c4-88d5-d81bf7042253
          stepCounter: e59b307c-9b8c-4317-8df2-0173eb6afe00
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was updated in the data warehouse.
        isSystemUpdateDate: true
        name: DSS_UPDATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          LOAD_QBYTE_INCOMING_XREF_VALUES: d2c1231e-7f31-4587-9f63-3076f4ad660c
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: TARGET
            nodeName: LOAD_QBYTE_INCOMING_XREF_VALUES
        join:
          joinCondition: FROM {{ ref('TARGET','LOAD_QBYTE_INCOMING_XREF_VALUES') }} LOAD_QBYTE_INCOMING_XREF_VALUES
        name: ODS_QBYTE_INCOMING_XREF_VALUES
        noLinkRefs: []
  name: ODS_QBYTE_INCOMING_XREF_VALUES
  overrideSQL: false
  schema: ""
  sqlType: '38'
  type: sql
  version: 1
type: Node
