fileVersion: 1
id: d2c1231e-7f31-4587-9f63-3076f4ad660c
name: LOAD_QBYTE_INCOMING_XREF_VALUES
operation:
  database: ""
  deployEnabled: true
  description: ""
  locationName: TARGET
  metadata:
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 563cf69d-b7c4-49f5-ae89-45c7d4149fbd
          stepCounter: d2c1231e-7f31-4587-9f63-3076f4ad660c
        config: {}
        dataType: VARCHAR(10)
        defaultValue: ""
        description: A code to indicate the type of value being cross-referenced.  e.g. account, cost centre, AFE, associate, etc.
        name: XREF_VALUE_TYPE_CODE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 649483f4-b3f8-4e22-b715-51de44aff278
          stepCounter: d2c1231e-7f31-4587-9f63-3076f4ad660c
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: The first element of the incoming code value.
        name: SOURCE_VALUE_1
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 270cd99c-3132-4746-bbcb-f6abcf820fab
          stepCounter: d2c1231e-7f31-4587-9f63-3076f4ad660c
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: The second element of the incoming code value.
        name: SOURCE_VALUE_2
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c27d64f9-97ab-44ca-916f-6c4edd8cbe3f
          stepCounter: d2c1231e-7f31-4587-9f63-3076f4ad660c
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: The third element of the incoming code value.
        name: SOURCE_VALUE_3
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 4b958651-8e0e-48fd-934d-07159e599dca
          stepCounter: d2c1231e-7f31-4587-9f63-3076f4ad660c
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: The fourth element of the incoming code value.
        name: SOURCE_VALUE_4
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 2a02f2db-dc9b-41e1-bd99-9710b6e3413c
          stepCounter: d2c1231e-7f31-4587-9f63-3076f4ad660c
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: The first element of the PW*Sequel code value.
        name: PWSQL_VALUE_1
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c33016ef-5aee-4a44-a13f-655f26af4c30
          stepCounter: d2c1231e-7f31-4587-9f63-3076f4ad660c
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: The second element of the PW*Sequel code value.
        name: PWSQL_VALUE_2
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: eebf8023-4d3b-44e1-8eaf-fbcd47aa6f09
          stepCounter: d2c1231e-7f31-4587-9f63-3076f4ad660c
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: The third element of the PW*Sequel code value.
        name: PWSQL_VALUE_3
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3fc5da4d-cc74-4304-a022-557d288855f6
          stepCounter: d2c1231e-7f31-4587-9f63-3076f4ad660c
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: The fourth element of the PW*Sequel code value.
        name: PWSQL_VALUE_4
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: aba437d4-8229-47b0-a12f-f555f71c06c9
          stepCounter: d2c1231e-7f31-4587-9f63-3076f4ad660c
        config: {}
        dataType: VARCHAR(30)
        defaultValue: ""
        description: The user who created the record.
        name: CREATE_USER
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ab216108-3a66-43a8-9fcf-d345e8e7521b
          stepCounter: d2c1231e-7f31-4587-9f63-3076f4ad660c
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: The date the record was created.
        name: CREATE_DATE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d5f342f3-c2b1-4c4e-a734-5605e35d3732
          stepCounter: d2c1231e-7f31-4587-9f63-3076f4ad660c
        config: {}
        dataType: VARCHAR(30)
        defaultValue: ""
        description: The user who last updated the record.
        name: LAST_UPDATE_USER
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3b02c395-c6dd-429c-bc70-c139a0ff3db1
          stepCounter: d2c1231e-7f31-4587-9f63-3076f4ad660c
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: The date the record was last updated.
        name: LAST_UPDATE_DATE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: de21839c-8a7d-44b2-b721-390a59b847fb
          stepCounter: d2c1231e-7f31-4587-9f63-3076f4ad660c
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 4999e1b0-3b39-493f-b801-7a295aac3e54
          stepCounter: d2c1231e-7f31-4587-9f63-3076f4ad660c
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
  name: LOAD_QBYTE_INCOMING_XREF_VALUES
  schema: ""
  sqlType: Source
  type: sourceInput
  version: 1
type: Node
