fileVersion: 1
id: ec5e1c77-fb19-480b-85a5-d01f814e47de
name: LOAD_XSPOC_TBLMOTORSETTINGS
operation:
  database: ""
  deployEnabled: true
  description: ""
  locationName: TARGET
  metadata:
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6a0454ac-5bfa-4b97-a793-c31173513fb3
          stepCounter: ec5e1c77-fb19-480b-85a5-d01f814e47de
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: MOTORSETTINGID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a65381d9-6d04-45e2-a14e-ceaf4d9ad3b0
          stepCounter: ec5e1c77-fb19-480b-85a5-d01f814e47de
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: ""
        name: NAME
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e2a189c8-164b-4846-850d-ab3ca5204dc1
          stepCounter: ec5e1c77-fb19-480b-85a5-d01f814e47de
        config: {}
        dataType: FLOAT
        defaultValue: ""
        description: ""
        name: FULLLOADRPM
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 4ba26968-ae48-4a9e-a57a-8a172a32dd2a
          stepCounter: ec5e1c77-fb19-480b-85a5-d01f814e47de
        config: {}
        dataType: FLOAT
        defaultValue: ""
        description: ""
        name: MAXLOAD
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: bb074460-d52f-41e1-8eda-f8133d2414e4
          stepCounter: ec5e1c77-fb19-480b-85a5-d01f814e47de
        config: {}
        dataType: FLOAT
        defaultValue: ""
        description: ""
        name: MAXSPV
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a8b8c03d-08e0-4f5a-b94e-729af7fec591
          stepCounter: ec5e1c77-fb19-480b-85a5-d01f814e47de
        config: {}
        dataType: FLOAT
        defaultValue: ""
        description: ""
        name: RATEDHP
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ccc78154-c849-492b-af87-6584ac3da8af
          stepCounter: ec5e1c77-fb19-480b-85a5-d01f814e47de
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: MOTORSIZEID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 56322741-888d-4d12-87ba-8a7e1de30ce5
          stepCounter: ec5e1c77-fb19-480b-85a5-d01f814e47de
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 015c0f6e-3689-43c3-89d1-9d120e854ca4
          stepCounter: ec5e1c77-fb19-480b-85a5-d01f814e47de
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
  name: LOAD_XSPOC_TBLMOTORSETTINGS
  schema: ""
  sqlType: Source
  type: sourceInput
  version: 1
type: Node
