fileVersion: 1
id: 500555a7-7b80-4640-b8f9-273276d90361
name: ODS_XSPOC_TBLPOCTYPEAPPLICATIONS
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ad8d0a46-0a62-4de9-ab52-ca3d407e4b9a
          stepCounter: 500555a7-7b80-4640-b8f9-273276d90361
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: POCTYPE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 0b2af5eb-ffc0-4f8f-aac7-e61886657622
                stepCounter: e501e470-41fa-4d4a-a81f-6724c3ccb29a
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3ea53f54-1bdd-414a-b8ef-45bc9260917b
          stepCounter: 500555a7-7b80-4640-b8f9-273276d90361
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: APPLICATIONID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 6556ad7c-d5ea-45a0-a050-1f57397d15a2
                stepCounter: e501e470-41fa-4d4a-a81f-6724c3ccb29a
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: cf3f0d8e-aec6-4a58-aac5-9bce05f90681
          stepCounter: 500555a7-7b80-4640-b8f9-273276d90361
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: ISDEFAULT
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 81732ed9-f8bf-483d-bfd4-5b7827cb8f07
                stepCounter: e501e470-41fa-4d4a-a81f-6724c3ccb29a
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e332fef2-bd80-47d7-815a-92c3a157be4e
          stepCounter: 500555a7-7b80-4640-b8f9-273276d90361
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: d854f9e0-397c-4b42-970d-f03812e56374
                stepCounter: e501e470-41fa-4d4a-a81f-6724c3ccb29a
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f33ee277-f961-4c49-8973-e79b4381ff87
          stepCounter: 500555a7-7b80-4640-b8f9-273276d90361
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: e430ac4c-381e-430f-ac36-740061088eb7
                stepCounter: e501e470-41fa-4d4a-a81f-6724c3ccb29a
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d0b1a063-fd7c-4ff9-b8d8-faca53a03688
          stepCounter: 500555a7-7b80-4640-b8f9-273276d90361
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: Flag field to identify Deleted record
        name: DSS_DELETE_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6a0fc1b8-a3f4-412c-9be9-f03acbd7bf70
          stepCounter: 500555a7-7b80-4640-b8f9-273276d90361
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Records time when record was set to Delete by the Load process
        name: DSS_DELETE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 50cf17a0-1517-4edd-9f67-6f58e7cc83c8
          stepCounter: 500555a7-7b80-4640-b8f9-273276d90361
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Datetime a business key was started.
        isSystemStartDate: true
        name: DSS_START_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 67edec69-da3d-475c-b99d-6cc143893920
          stepCounter: 500555a7-7b80-4640-b8f9-273276d90361
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Datetime a business key was retired.
        isSystemEndDate: true
        name: DSS_END_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 522605ba-afb8-4cc3-84e6-8d844fa03358
          stepCounter: 500555a7-7b80-4640-b8f9-273276d90361
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: Flag to indicate the current (latest) version of a business key.
        isSystemCurrentFlag: true
        name: DSS_CURRENT_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: de6aad7c-943e-4649-a1cf-307e13463aae
          stepCounter: 500555a7-7b80-4640-b8f9-273276d90361
        config: {}
        dataType: INTEGER
        defaultValue: ""
        description: Version number of a business key.
        isSystemVersion: true
        name: DSS_VERSION
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f08fe51d-1858-42b8-ac89-493ccf469763
          stepCounter: 500555a7-7b80-4640-b8f9-273276d90361
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was created in the data warehouse.
        isSystemCreateDate: true
        name: DSS_CREATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8066fbc4-a72f-4aa1-860f-60b7326c1cbb
          stepCounter: 500555a7-7b80-4640-b8f9-273276d90361
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was updated in the data warehouse.
        isSystemUpdateDate: true
        name: DSS_UPDATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          LOAD_XSPOC_TBLPOCTYPEAPPLICATIONS: e501e470-41fa-4d4a-a81f-6724c3ccb29a
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: TARGET
            nodeName: LOAD_XSPOC_TBLPOCTYPEAPPLICATIONS
        join:
          joinCondition: FROM {{ ref('TARGET','LOAD_XSPOC_TBLPOCTYPEAPPLICATIONS') }} LOAD_XSPOC_TBLPOCTYPEAPPLICATIONS
        name: ODS_XSPOC_TBLPOCTYPEAPPLICATIONS
        noLinkRefs: []
  name: ODS_XSPOC_TBLPOCTYPEAPPLICATIONS
  overrideSQL: false
  schema: ""
  sqlType: '38'
  type: sql
  version: 1
type: Node
