fileVersion: 1
id: da992862-35a1-4c3a-900c-5dc53d3bb22f
name: LOAD_XSPOC_TBLUSERSECURITY
operation:
  config:
    archive_enabled: true
    archive_path: archive
    extlocation: false
    fieldDelim: ~|~
    fieldEnclosed: '"'
    fileFormatType: File Format Values
    filePattern: ''
    fileType: CSV
    inferschema: false
    insertStrategy: INSERT
    intextstage: true
    postSQL: ''
    preSQL: ''
    recDelim: ''
    replaceinvalidcharacters: false
    skipBlankLines: false
    skipHeader: '1'
    stageName: s3_LOAD_XSPOC_TBLUSERSECURITY
    stageStorageLocationName: DV2_STG
    stripouterarray: false
    subfolder: ''
    testsEnabled: true
    trimSpace: false
    truncateBefore: true
    usevectscan: false
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ff0c8c88-73a1-48c7-9b40-b675f79b9c95
          stepCounter: da992862-35a1-4c3a-900c-5dc53d3bb22f
        config: {}
        dataType: VARCHAR(100)
        defaultValue: ""
        description: ""
        name: USERNAME
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1b1db2eb-4dff-4da6-995a-822a5b8d0262
          stepCounter: da992862-35a1-4c3a-900c-5dc53d3bb22f
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: WELLCONTROL
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 84c9eef1-9b79-4d88-b1c7-12cb6bdc4d04
          stepCounter: da992862-35a1-4c3a-900c-5dc53d3bb22f
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: WELLCONFIG
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0ab78be9-9f7a-4f7a-a384-a08c323c6b03
          stepCounter: da992862-35a1-4c3a-900c-5dc53d3bb22f
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: ADMIN
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d682a47c-2768-464d-bdee-83f490b6c969
          stepCounter: da992862-35a1-4c3a-900c-5dc53d3bb22f
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: ADMINLITE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c22b5a66-deb1-41aa-835a-1d5b51a65bfa
          stepCounter: da992862-35a1-4c3a-900c-5dc53d3bb22f
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: WELLADMIN
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6c46f201-ddd9-4635-8859-890e34eb878a
          stepCounter: da992862-35a1-4c3a-900c-5dc53d3bb22f
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: WELLCONFIGLITE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e3c85fe4-ed84-4f69-9dd0-de29ef3a7879
          stepCounter: da992862-35a1-4c3a-900c-5dc53d3bb22f
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        name: PASSWORD
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 4146161b-8846-4e42-b7e2-532dd129e1eb
          stepCounter: da992862-35a1-4c3a-900c-5dc53d3bb22f
        config: {}
        dataType: VARCHAR(100)
        defaultValue: ""
        description: ""
        name: EMAIL
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5e46c5b3-762f-4ad2-b90e-c2c7df0b7bb2
          stepCounter: da992862-35a1-4c3a-900c-5dc53d3bb22f
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        name: LASTACCESSDATE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: cf37e2ae-5769-484d-ad59-d3a35e1c9b86
          stepCounter: da992862-35a1-4c3a-900c-5dc53d3bb22f
        config: {}
        dataType: VARCHAR(36)
        defaultValue: ""
        description: ""
        name: WEBTOKEN
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f4448523-6c6f-48fa-923e-bffcb80fe982
          stepCounter: da992862-35a1-4c3a-900c-5dc53d3bb22f
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        name: WEBTOKENEXPIRE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 72c9963b-bd4c-4614-96b4-3dc4167a3233
          stepCounter: da992862-35a1-4c3a-900c-5dc53d3bb22f
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: MUSTCHANGEPASSWORD
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5ca56b87-92c8-4d0a-981a-6faa24a462c9
          stepCounter: da992862-35a1-4c3a-900c-5dc53d3bb22f
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f370be1d-db84-4308-97a6-b1ce000e51fc
          stepCounter: da992862-35a1-4c3a-900c-5dc53d3bb22f
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences: []
    enabledColumnTestIDs: []
    sourceMapping: []
  name: LOAD_XSPOC_TBLUSERSECURITY
  overrideSQL: false
  schema: ""
  sqlType: External:::324
  type: sql
  version: 1
type: Node
