fileVersion: 1
id: 710e7d0b-0184-47ab-a677-3d1850dfd1c5
name: LOAD_XSPOC_TBLGRAPHVIEWSETTINGS
operation:
  database: ""
  deployEnabled: true
  description: ""
  locationName: TARGET
  metadata:
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3207cafc-ac10-449a-97f0-67c95a9d7e25
          stepCounter: 710e7d0b-0184-47ab-a677-3d1850dfd1c5
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: VIEWID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b59aee18-753a-4356-947f-8304cb7a40c6
          stepCounter: 710e7d0b-0184-47ab-a677-3d1850dfd1c5
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        name: PROPERTY
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 11a7e40c-32fd-4373-b76d-4f943d247888
          stepCounter: 710e7d0b-0184-47ab-a677-3d1850dfd1c5
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        name: VALUE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a7c16113-bd82-43fd-bcbd-1198ab442c5b
          stepCounter: 710e7d0b-0184-47ab-a677-3d1850dfd1c5
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: fb6911fc-db10-4e28-8824-0778745238f2
          stepCounter: 710e7d0b-0184-47ab-a677-3d1850dfd1c5
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
  name: LOAD_XSPOC_TBLGRAPHVIEWSETTINGS
  schema: ""
  sqlType: Source
  type: sourceInput
  version: 1
type: Node
