fileVersion: 1
id: 47eaee0d-7028-4751-acec-ad5dfe5006f8
name: LOAD_XSPOC_TBLPOCTYPEAPPLICATIONS
operation:
  database: ""
  deployEnabled: true
  description: ""
  locationName: TARGET
  metadata:
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 23421dbb-44ce-4cb3-9f54-e98e4ae5b0fe
          stepCounter: 47eaee0d-7028-4751-acec-ad5dfe5006f8
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: POCTYPE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5edca678-dc07-4f30-9e73-b3f12796f4bb
          stepCounter: 47eaee0d-7028-4751-acec-ad5dfe5006f8
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: APPLICATIONID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 524c97f6-d7a6-41f9-946a-cfe10a126f63
          stepCounter: 47eaee0d-7028-4751-acec-ad5dfe5006f8
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: ISDEFAULT
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c82402d0-d948-48c3-8808-a522f37c2f0c
          stepCounter: 47eaee0d-7028-4751-acec-ad5dfe5006f8
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f0e202b9-6a93-4b8c-b04e-d52e963c780d
          stepCounter: 47eaee0d-7028-4751-acec-ad5dfe5006f8
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
  name: LOAD_XSPOC_TBLPOCTYPEAPPLICATIONS
  schema: ""
  sqlType: Source
  type: sourceInput
  version: 1
type: Node
