fileVersion: 1
id: b404919b-21c4-4b4d-be1c-50503eca6330
name: LOAD_MOSAIC_CDM_WORKSPACE_SETTINGS
operation:
  config:
    archive_enabled: true
    archive_path: archive
    extlocation: false
    fieldDelim: ~|~
    fieldEnclosed: '"'
    fileFormatType: File Format Values
    filePattern: ''
    fileType: CSV
    inferschema: false
    insertStrategy: INSERT
    intextstage: true
    postSQL: ''
    preSQL: ''
    recDelim: ''
    replaceinvalidcharacters: false
    skipBlankLines: false
    skipHeader: '1'
    stageName: s3_LOAD_MOSAIC_CDM_WORKSPACE_SETTINGS
    stageStorageLocationName: DV2_STG
    stripouterarray: false
    subfolder: ''
    testsEnabled: true
    trimSpace: false
    truncateBefore: true
    usevectscan: false
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TARGET
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e8c82db5-ada9-4945-b6fb-99ce4fb43148
          stepCounter: b404919b-21c4-4b4d-be1c-50503eca6330
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: CURRENT_CASE_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b9f91688-13ee-4006-9a98-e760c5941311
          stepCounter: b404919b-21c4-4b4d-be1c-50503eca6330
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: DEFAULT_COMPANY_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f2b93f95-26c0-41df-9b0f-e356d858d6cf
          stepCounter: b404919b-21c4-4b4d-be1c-50503eca6330
        config: {}
        dataType: VARCHAR(250)
        defaultValue: ""
        description: ""
        name: DESCRIPTION
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0b5fa431-5431-47db-ab56-a68b22836efb
          stepCounter: b404919b-21c4-4b4d-be1c-50503eca6330
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_BY_USER
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: fead2c25-56b1-40f8-a40a-f786ca867e80
          stepCounter: b404919b-21c4-4b4d-be1c-50503eca6330
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_DATE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8a321588-fd7d-4901-8b59-43c771aec34c
          stepCounter: b404919b-21c4-4b4d-be1c-50503eca6330
        config: {}
        dataType: VARCHAR(100)
        defaultValue: ""
        description: ""
        name: NAME
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: be605dba-8492-489f-913a-83e8884ecd45
          stepCounter: b404919b-21c4-4b4d-be1c-50503eca6330
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: PREVIOUS_CASE_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8bec91b0-b507-489b-a991-c50a55129078
          stepCounter: b404919b-21c4-4b4d-be1c-50503eca6330
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: PRIVATE_FLAG
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6f2e0b0b-28cb-4413-8245-780f138d40a7
          stepCounter: b404919b-21c4-4b4d-be1c-50503eca6330
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: RESERVE_CAT_GROUP_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: dcfe6468-479b-4918-baf8-2560dc88b849
          stepCounter: b404919b-21c4-4b4d-be1c-50503eca6330
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: SEARCH_FILTER_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7a02339a-a443-452f-817f-75402603957e
          stepCounter: b404919b-21c4-4b4d-be1c-50503eca6330
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: USER_PROFILE_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 51667d41-9b95-4315-9e7a-9c19350972ff
          stepCounter: b404919b-21c4-4b4d-be1c-50503eca6330
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        name: UUID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 65c49ac7-605b-42bc-b2e9-ca790cc0102b
          stepCounter: b404919b-21c4-4b4d-be1c-50503eca6330
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: WORKBENCH_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 2942b118-2283-4e78-a075-b959d0f46e6b
          stepCounter: b404919b-21c4-4b4d-be1c-50503eca6330
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: WORKSPACE_SETTINGS_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7e924e07-efec-4591-b094-b0c6c10dad3a
          stepCounter: b404919b-21c4-4b4d-be1c-50503eca6330
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        name: DEFAULT_STATIC_HIERARCHY_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 9c7c0db1-8b0e-49dc-a37e-839b653e6958
          stepCounter: b404919b-21c4-4b4d-be1c-50503eca6330
        config: {}
        dataType: VARCHAR(250)
        defaultValue: ""
        description: ""
        name: HIERARCHY_FILTER_NAME
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7abe164e-c798-42fe-8cdd-32eba721156f
          stepCounter: b404919b-21c4-4b4d-be1c-50503eca6330
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        name: ENTITY_STATE_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 241a7db8-5cd1-4409-ab6f-b2425b5f2366
          stepCounter: b404919b-21c4-4b4d-be1c-50503eca6330
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        name: WORKSPACE_VIEW_TYPE_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6ebeb41f-76f2-479c-89e9-42cb463f7182
          stepCounter: b404919b-21c4-4b4d-be1c-50503eca6330
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        name: PANEL_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 41883b9a-e469-433d-b277-49a7aa0900a9
          stepCounter: b404919b-21c4-4b4d-be1c-50503eca6330
        config: {}
        dataType: VARCHAR(200)
        defaultValue: ""
        description: ""
        name: TABLE_COLUMN_SET
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: befc1271-3d5e-4faa-99e6-8c5cc330a049
          stepCounter: b404919b-21c4-4b4d-be1c-50503eca6330
        config: {}
        dataType: VARCHAR(200)
        defaultValue: ""
        description: ""
        name: ECONOMIC_COLUMN_SET
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c5996dca-d037-45aa-b744-d6dc3eda195f
          stepCounter: b404919b-21c4-4b4d-be1c-50503eca6330
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        name: ICON_CODE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6fe4e911-ade3-4f4e-a115-5825fbfaf8b0
          stepCounter: b404919b-21c4-4b4d-be1c-50503eca6330
        config: {}
        dataType: VARCHAR(250)
        defaultValue: ""
        description: ""
        name: ENTITY_NAME
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7790eb5a-a01f-4dbf-849b-1ad22936d322
          stepCounter: b404919b-21c4-4b4d-be1c-50503eca6330
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: RESERVE_CATEGORY_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: dafc405b-d25d-4535-895a-af78b702d047
          stepCounter: b404919b-21c4-4b4d-be1c-50503eca6330
        config: {}
        dataType: NUMBER(9)
        defaultValue: ""
        description: ""
        name: RECON_ID
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: da2b8aa7-58a9-44ea-889b-3793f9a4181b
          stepCounter: b404919b-21c4-4b4d-be1c-50503eca6330
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences: []
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 08638097-248f-4380-8719-8ad85c29f6c9
          stepCounter: b404919b-21c4-4b4d-be1c-50503eca6330
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences: []
    enabledColumnTestIDs: []
    sourceMapping: []
  name: LOAD_MOSAIC_CDM_WORKSPACE_SETTINGS
  overrideSQL: false
  schema: ""
  sqlType: External:::324
  type: sql
  version: 1
type: Node
