fileVersion: 1
id: 6159b3cb-6bd9-4214-af89-1060b1eaa94a
name: LOAD_QBYTE_OUTGOING_XREF_VALUES
operation:
  database: ""
  deployEnabled: true
  description: ""
  locationName: TARGET
  metadata:
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8ac7ab6a-21ac-4396-8486-fb84d875e95c
          stepCounter: 6159b3cb-6bd9-4214-af89-1060b1eaa94a
        config: {}
        dataType: VARCHAR(10)
        defaultValue: ""
        description: A code to indicate the type of value being cross-referenced. e.g. account, cost centre, AFE, associate, etc.
        name: XREF_VALUE_TYPE_CODE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ca5a31a2-d88c-4539-9e7c-8bc572cd75c7
          stepCounter: 6159b3cb-6bd9-4214-af89-1060b1eaa94a
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: The first element of the PW*Sequel code value.
        name: PWSQL_VALUE_1
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 42e969d6-c7d0-473b-8b86-4123e88a417c
          stepCounter: 6159b3cb-6bd9-4214-af89-1060b1eaa94a
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: The second element of the PW*Sequel code value.
        name: PWSQL_VALUE_2
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8682aa49-c451-4127-bebb-55519f7d4b41
          stepCounter: 6159b3cb-6bd9-4214-af89-1060b1eaa94a
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: The third element of the PW*Sequel code value.
        name: PWSQL_VALUE_3
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 38086c2b-7ac6-4f64-bcf0-0953a59b76bb
          stepCounter: 6159b3cb-6bd9-4214-af89-1060b1eaa94a
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: The fourth element of the PW*Sequel code value.
        name: PWSQL_VALUE_4
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 2ec77015-d8c5-4850-bb86-4c7a03887a5b
          stepCounter: 6159b3cb-6bd9-4214-af89-1060b1eaa94a
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: The first element of the destination system code value.
        name: DEST_VALUE_1
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 182c4962-8e8d-4efe-b16b-4280fe97839d
          stepCounter: 6159b3cb-6bd9-4214-af89-1060b1eaa94a
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: The second element of the destination system code value.
        name: DEST_VALUE_2
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e48c7260-a56f-41cf-84bf-583e7f2730ef
          stepCounter: 6159b3cb-6bd9-4214-af89-1060b1eaa94a
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: The third element of the destination system code value.
        name: DEST_VALUE_3
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1c2df49d-2651-430d-a3d3-585d6e1bf744
          stepCounter: 6159b3cb-6bd9-4214-af89-1060b1eaa94a
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: The fourth element of the destination system code value.
        name: DEST_VALUE_4
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 62cf1f93-865d-4977-9fc6-349529feb7dd
          stepCounter: 6159b3cb-6bd9-4214-af89-1060b1eaa94a
        config: {}
        dataType: VARCHAR(30)
        defaultValue: ""
        description: The user who created the record.
        name: CREATE_USER
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ded8d21b-0507-4d14-8387-6327d14d10c0
          stepCounter: 6159b3cb-6bd9-4214-af89-1060b1eaa94a
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: The date the record was created.
        name: CREATE_DATE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 74562b2c-b192-4129-b1d6-9dc73a0f9ec5
          stepCounter: 6159b3cb-6bd9-4214-af89-1060b1eaa94a
        config: {}
        dataType: VARCHAR(30)
        defaultValue: ""
        description: The user who last updated the record.
        name: LAST_UPDATE_USER
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 511baef9-24fb-4f11-b177-db7d99afa547
          stepCounter: 6159b3cb-6bd9-4214-af89-1060b1eaa94a
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: The date the record was last updated.
        name: LAST_UPDATE_DATE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f6eaed81-3c7b-4877-80eb-d557eb787ce9
          stepCounter: 6159b3cb-6bd9-4214-af89-1060b1eaa94a
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b169a4d4-d83d-4931-86f0-e898959d1ec5
          stepCounter: 6159b3cb-6bd9-4214-af89-1060b1eaa94a
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
  name: LOAD_QBYTE_OUTGOING_XREF_VALUES
  schema: ""
  sqlType: Source
  type: sourceInput
  version: 1
type: Node
