fileVersion: 1
id: 7e04fb51-ab55-4b02-bc45-a04c98944112
name: LOAD_XSPOC_TBLUSERSECURITY
operation:
  database: ""
  deployEnabled: true
  description: ""
  locationName: TARGET
  metadata:
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 46a737a9-f03c-4b03-8618-265c3c6195b4
          stepCounter: 7e04fb51-ab55-4b02-bc45-a04c98944112
        config: {}
        dataType: VARCHAR(100)
        defaultValue: ""
        description: ""
        name: USERNAME
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8928fb6d-e223-4377-a7d0-80c895ced23e
          stepCounter: 7e04fb51-ab55-4b02-bc45-a04c98944112
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: WELLCONTROL
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8b3edb3f-9f88-4826-8419-c3cf385eac4c
          stepCounter: 7e04fb51-ab55-4b02-bc45-a04c98944112
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: WELLCONFIG
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 425a8ed6-7ad0-415e-aacd-1266c6c9613c
          stepCounter: 7e04fb51-ab55-4b02-bc45-a04c98944112
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: ADMIN
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 81d0a5ce-dce6-48aa-99dd-5eb2e83cca4e
          stepCounter: 7e04fb51-ab55-4b02-bc45-a04c98944112
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: ADMINLITE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a8014cb0-f9da-4fe1-96e2-3995094b7c7e
          stepCounter: 7e04fb51-ab55-4b02-bc45-a04c98944112
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: WELLADMIN
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 98706c31-bdd1-49cc-b8d6-00a7253e3f4d
          stepCounter: 7e04fb51-ab55-4b02-bc45-a04c98944112
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: WELLCONFIGLITE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: de6b89e1-7bb3-4fa2-bc4e-cd04cf2c3a7b
          stepCounter: 7e04fb51-ab55-4b02-bc45-a04c98944112
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        name: PASSWORD
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1ad77a4a-d9da-4f2b-94bf-99e69b818eaa
          stepCounter: 7e04fb51-ab55-4b02-bc45-a04c98944112
        config: {}
        dataType: VARCHAR(100)
        defaultValue: ""
        description: ""
        name: EMAIL
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ef418df6-f71b-40c3-a05f-79bbf3c72587
          stepCounter: 7e04fb51-ab55-4b02-bc45-a04c98944112
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        name: LASTACCESSDATE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 80365da2-f2ad-429b-9bad-1641d2c35c10
          stepCounter: 7e04fb51-ab55-4b02-bc45-a04c98944112
        config: {}
        dataType: VARCHAR(36)
        defaultValue: ""
        description: ""
        name: WEBTOKEN
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3656958c-6e4e-4d4f-8a38-c71d3fdd3cf9
          stepCounter: 7e04fb51-ab55-4b02-bc45-a04c98944112
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        name: WEBTOKENEXPIRE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8fe91dbf-6695-456d-8bcb-1de8b62a2d7c
          stepCounter: 7e04fb51-ab55-4b02-bc45-a04c98944112
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: MUSTCHANGEPASSWORD
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5fdc51a7-5663-4dd0-8b3b-b141ec178ecb
          stepCounter: 7e04fb51-ab55-4b02-bc45-a04c98944112
        config: {}
        dataType: VARCHAR(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 545da8b3-81e3-4e10-a372-347ade265a55
          stepCounter: 7e04fb51-ab55-4b02-bc45-a04c98944112
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
  name: LOAD_XSPOC_TBLUSERSECURITY
  schema: ""
  sqlType: Source
  type: sourceInput
  version: 1
type: Node
