fileVersion: 1
id: e576884f-f915-4be8-9d8b-527b62d32310
name: S_PIMS_LDD_LOCAL_DATAVALUES_20
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TGT
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6b93db35-5f48-41f9-9a26-822c8a38197f
          stepCounter: e576884f-f915-4be8-9d8b-527b62d32310
        config: {}
        dataType: INTEGER
        defaultValue: ""
        description: ""
        name: CONTACT_SEQUENCE
        nullable: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 33cea034-3dbc-4d22-bebb-e7f89999e877
          stepCounter: e576884f-f915-4be8-9d8b-527b62d32310
        config: {}
        dataType: DECIMAL(10)
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: LCLDA_REFNO
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: a156e9d0-2eaf-48cf-b9bc-5826b02c3502
                stepCounter: b6a8b2d0-6712-44c0-b5cd-288facb15865
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ce0f6315-c116-4918-ab23-2dc9d327b9d4
          stepCounter: e576884f-f915-4be8-9d8b-527b62d32310
        config: {}
        dataType: DECIMAL(10)
        defaultValue: ""
        description: ""
        name: USSCR_REFNO
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 48f4fb04-f4cb-4a92-88bc-6840414b10f7
                stepCounter: b6a8b2d0-6712-44c0-b5cd-288facb15865
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 911edc70-7b22-43b9-b002-7a06d2242fb4
          stepCounter: e576884f-f915-4be8-9d8b-527b62d32310
        config: {}
        dataType: DECIMAL(10)
        defaultValue: ""
        description: ""
        name: PATNT_REFNO
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 403f0aef-ddf7-4312-b799-0ed93ae8ff77
                stepCounter: b6a8b2d0-6712-44c0-b5cd-288facb15865
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 254cc456-5cbb-41e8-a80d-7de634468332
          stepCounter: e576884f-f915-4be8-9d8b-527b62d32310
        config: {}
        dataType: DECIMAL(10)
        defaultValue: ""
        description: ""
        name: PROCA_REFNO
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: d8c816b3-c3e5-4473-a903-099a5aeb9b7b
                stepCounter: b6a8b2d0-6712-44c0-b5cd-288facb15865
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 4a100632-cfef-40dd-b5fd-c25a24ed3751
          stepCounter: e576884f-f915-4be8-9d8b-527b62d32310
        config: {}
        dataType: VARCHAR(5)
        defaultValue: ""
        description: ""
        name: SORCE_CODE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: bff3b0dc-813a-40fe-9888-47c06e28d39d
                stepCounter: b6a8b2d0-6712-44c0-b5cd-288facb15865
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a1e6ed5d-0f2f-4b3a-b209-0a86a23707a9
          stepCounter: e576884f-f915-4be8-9d8b-527b62d32310
        config: {}
        dataType: DECIMAL(10)
        defaultValue: ""
        description: ""
        name: SORCE_REFNO
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 27c0049d-8f6d-43d4-b452-da1dbebc6194
                stepCounter: b6a8b2d0-6712-44c0-b5cd-288facb15865
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3cf79200-e43b-4638-84f9-e36eff93fa52
          stepCounter: e576884f-f915-4be8-9d8b-527b62d32310
        config: {}
        dataType: DECIMAL(10)
        defaultValue: ""
        description: ""
        name: PARNT_REFNO
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: a5490042-0263-480d-86a8-1116f2b24399
                stepCounter: b6a8b2d0-6712-44c0-b5cd-288facb15865
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: cfae599f-172d-44d1-9330-017fb903bf84
          stepCounter: e576884f-f915-4be8-9d8b-527b62d32310
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: COLLECT_DTTM
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: dc0ba096-d1b1-43fd-9aa4-da7bad2efe41
                stepCounter: b6a8b2d0-6712-44c0-b5cd-288facb15865
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e1956943-51cf-4af0-9bb2-c94660db0ed6
          stepCounter: e576884f-f915-4be8-9d8b-527b62d32310
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: ""
        name: VALUE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: a1753a40-ada5-46e8-a00f-1fc794be3674
                stepCounter: b6a8b2d0-6712-44c0-b5cd-288facb15865
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 80d5fe01-dca3-4292-b25d-38794697a49e
          stepCounter: e576884f-f915-4be8-9d8b-527b62d32310
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: DATEVALUE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 02be01e0-1d7d-4fbe-a975-2e1be5817393
                stepCounter: b6a8b2d0-6712-44c0-b5cd-288facb15865
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 99997ef6-a2e9-4ac3-b3e9-3285cf509ad8
          stepCounter: e576884f-f915-4be8-9d8b-527b62d32310
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: ""
        name: MEMOVALUE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 57829cac-1198-49f1-9489-96050b996288
                stepCounter: b6a8b2d0-6712-44c0-b5cd-288facb15865
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 45911bc6-13fc-4540-b0b2-a8c2d8dced34
          stepCounter: e576884f-f915-4be8-9d8b-527b62d32310
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        name: COLUMNNAME
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 403d8ebf-2fe7-4ad8-a825-d8dc48eb469f
                stepCounter: b6a8b2d0-6712-44c0-b5cd-288facb15865
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1c04d601-1058-45dc-a90e-daaae6a0ec8e
          stepCounter: e576884f-f915-4be8-9d8b-527b62d32310
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: CREATE_DTTM
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 8a551d8e-ea23-4aca-a610-573b9b0025a9
                stepCounter: c5429209-b899-4e7f-9548-ca0e9a55f302
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b045184e-f284-488e-89ad-1d765b49e7f3
          stepCounter: e576884f-f915-4be8-9d8b-527b62d32310
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: MODIF_DTTM
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: f2ae9181-e1ea-4bf1-a10b-4282e3eeecea
                stepCounter: c5429209-b899-4e7f-9548-ca0e9a55f302
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c6218df6-a4c7-4b87-b2b2-3c307e799d7c
          stepCounter: e576884f-f915-4be8-9d8b-527b62d32310
        config: {}
        dataType: VARCHAR(30)
        defaultValue: ""
        description: ""
        name: USER_CREATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 710678e8-1221-4af5-9b26-bef426f8d89b
                stepCounter: c5429209-b899-4e7f-9548-ca0e9a55f302
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f7f450aa-2525-4c75-ab7e-1c9f0d7c7f17
          stepCounter: e576884f-f915-4be8-9d8b-527b62d32310
        config: {}
        dataType: VARCHAR(30)
        defaultValue: ""
        description: ""
        name: USER_MODIF
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: aaf0a3ff-e582-4ddb-99ff-76ae7d7d3c74
                stepCounter: c5429209-b899-4e7f-9548-ca0e9a55f302
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 14c69f2b-5dde-4755-be10-526b5e486f7b
          stepCounter: e576884f-f915-4be8-9d8b-527b62d32310
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: Date and time the row was updated in the data warehouse.
        isSystemUpdateDate: true
        name: DSS_UPDATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          S_PIMS_LDD_LOCAL_DATAVALUES_10: b6a8b2d0-6712-44c0-b5cd-288facb15865
          DS_PIMS_LDD_LOCAL_DATAVALUES: c5429209-b899-4e7f-9548-ca0e9a55f302
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: TGT
            nodeName: S_PIMS_LDD_LOCAL_DATAVALUES_10
          - locationName: TGT
            nodeName: DS_PIMS_LDD_LOCAL_DATAVALUES
        join:
          joinCondition: |-
            FROM {{ ref('TGT','S_PIMS_LDD_LOCAL_DATAVALUES_10') }}
              JOIN {{ ref('TGT','DS_PIMS_LDD_LOCAL_DATAVALUES') }}
                ON s_pims_ldd_local_datavalues_10.lclda_refno = ds_pims_ldd_local_datavalues.lclda_refno
        name: S_PIMS_LDD_LOCAL_DATAVALUES_20
        noLinkRefs: []
  name: S_PIMS_LDD_LOCAL_DATAVALUES_20
  overrideSQL: false
  schema: ""
  sqlType: Stage
  type: sql
  version: 1
type: Node
