fileVersion: 1
id: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
name: L_PIMS_REFERENCE_VALUES
operation:
  database: ""
  deployEnabled: true
  description: ""
  locationName: TGT
  metadata:
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a585af7e-5ba1-4b26-8910-981becba5e84
          stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
        config: {}
        dataType: DECIMAL(10)
        defaultValue: ""
        description: ""
        name: RFVAL_REFNO
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b7a5547b-0822-418c-8723-f86f3fdde6d4
          stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
        config: {}
        dataType: VARCHAR(5)
        defaultValue: ""
        description: ""
        name: RFVDM_CODE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 382613a6-0a2f-4c51-8cc1-cc6c35de5f0c
          stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
        config: {}
        dataType: VARCHAR(80)
        defaultValue: ""
        description: ""
        name: DESCRIPTION
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: df7effe6-3058-4d31-8657-1bcae9c8c673
          stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
        config: {}
        dataType: VARCHAR(25)
        defaultValue: ""
        description: ""
        name: MAIN_CODE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 675ddf4e-10dd-461b-9164-13e5472bfec7
          stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
        config: {}
        dataType: DECIMAL(10)
        defaultValue: ""
        description: ""
        name: PARNT_REFNO
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7153772f-9397-471c-8490-b917772c526f
          stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
        config: {}
        dataType: VARCHAR(5)
        defaultValue: ""
        description: ""
        name: SMODE_VALUE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: fad73f0c-b808-4725-8032-085cd35fe33e
          stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: ""
        name: DEFAULT_VALUE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 65dc9507-7994-4128-b72c-4b8824130363
          stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
        config: {}
        dataType: DECIMAL(3)
        defaultValue: ""
        description: ""
        name: SORT_ORDER
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 025181c5-201d-4708-bcb3-6744b32a8677
          stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: ""
        name: SELECT_VALUE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f5f41aba-f7c7-4e75-9298-6d7cab6af08d
          stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: ""
        name: DISPLAY_VALUE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5ebe0772-844b-471a-9c36-dfacb70f12b2
          stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: CREATE_DTTM
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7eb748fa-fdec-43b9-b13d-cbe367194729
          stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: MODIF_DTTM
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ef14817f-b191-49b1-aa13-55b8f50b2e31
          stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
        config: {}
        dataType: VARCHAR(30)
        defaultValue: ""
        description: ""
        name: USER_CREATE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 209d7339-41fd-4371-9b73-a46b93f129eb
          stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
        config: {}
        dataType: VARCHAR(30)
        defaultValue: ""
        description: ""
        name: USER_MODIF
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 88d9d21c-11a4-4790-8f29-6d7fb8023f6c
          stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
        config: {}
        dataType: VARCHAR(5)
        defaultValue: ""
        description: ""
        name: RFTYP_CODE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 47d6f06f-c54f-4b06-b104-6c98b857de07
          stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: ""
        name: ARCHV_FLAG
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 437d7cf1-918b-4045-8fba-3566f0788bf1
          stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
        config: {}
        dataType: DECIMAL(10)
        defaultValue: ""
        description: ""
        name: STRAN_REFNO
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8012a840-954c-47bd-a084-64af7fb7109a
          stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
        config: {}
        dataType: DECIMAL(10)
        defaultValue: ""
        description: ""
        name: PRIOR_POINTER
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d8d8cd83-d83f-48a3-9bc4-63b0b4e04c72
          stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: EXTERNAL_KEY
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8e6d57e1-7fc5-48ea-bc89-dbabe1f7bfc9
          stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: START_DTTM
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 87b7bf4d-6b70-4900-8f59-df2168efece8
          stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: END_DTTM
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 2a2a857f-9c4b-4a0a-a743-7344dd8ab829
          stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
        config: {}
        dataType: VARCHAR(30)
        defaultValue: ""
        description: ""
        name: LOW_VALUE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a2d0b9de-a1b9-444d-be4a-d8551634033e
          stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
        config: {}
        dataType: VARCHAR(30)
        defaultValue: ""
        description: ""
        name: HIGH_VALUE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a8070f45-3596-4f9f-bdcc-652eb411c20c
          stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: PROCESS_MODULE_ID
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8fe267d0-d8e7-4966-ad2a-cf033a9e4dca
          stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
        config: {}
        dataType: DECIMAL(10)
        defaultValue: ""
        description: ""
        name: OWNER_HEORG_REFNO
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ea7d54e4-323a-4079-b782-29bac7bbd890
          stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
        config: {}
        dataType: DECIMAL(10)
        defaultValue: ""
        description: ""
        name: SCLVL_REFNO
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ad5ed0c3-ed2c-4e05-92b7-49979d153ce7
          stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: SYN_CODE
        nullable: true
  name: L_PIMS_REFERENCE_VALUES
  schema: ""
  sqlType: Source
  type: sourceInput
  version: 1
type: Node
