fileVersion: 1
id: b6a8b2d0-6712-44c0-b5cd-288facb15865
name: S_PIMS_LDD_LOCAL_DATAVALUES_10
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
  database: ""
  deployEnabled: true
  description: "No Process procedure Only a custom procedure"
  isMultisource: false
  locationName: TGT
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a156e9d0-2eaf-48cf-b9bc-5826b02c3502
          stepCounter: b6a8b2d0-6712-44c0-b5cd-288facb15865
        config: {}
        dataType: DECIMAL(10)
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: LCLDA_REFNO
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: dbd3ebce-bc67-473e-b3a7-be4052b657c7
                stepCounter: c5429209-b899-4e7f-9548-ca0e9a55f302
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 48f4fb04-f4cb-4a92-88bc-6840414b10f7
          stepCounter: b6a8b2d0-6712-44c0-b5cd-288facb15865
        config: {}
        dataType: DECIMAL(10)
        defaultValue: ""
        description: ""
        name: USSCR_REFNO
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: ff6334c2-115d-41a1-8bc2-013e6215eb8a
                stepCounter: c5429209-b899-4e7f-9548-ca0e9a55f302
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 403f0aef-ddf7-4312-b799-0ed93ae8ff77
          stepCounter: b6a8b2d0-6712-44c0-b5cd-288facb15865
        config: {}
        dataType: DECIMAL(10)
        defaultValue: ""
        description: ""
        name: PATNT_REFNO
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: b076c301-deb4-4824-a7f6-1615c4559777
                stepCounter: c5429209-b899-4e7f-9548-ca0e9a55f302
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d8c816b3-c3e5-4473-a903-099a5aeb9b7b
          stepCounter: b6a8b2d0-6712-44c0-b5cd-288facb15865
        config: {}
        dataType: DECIMAL(10)
        defaultValue: ""
        description: ""
        name: PROCA_REFNO
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 195966fa-4913-4265-89be-ea2d5be14973
                stepCounter: c5429209-b899-4e7f-9548-ca0e9a55f302
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: bff3b0dc-813a-40fe-9888-47c06e28d39d
          stepCounter: b6a8b2d0-6712-44c0-b5cd-288facb15865
        config: {}
        dataType: VARCHAR(5)
        defaultValue: ""
        description: ""
        name: SORCE_CODE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: b2574627-8c28-455b-a4fc-1ecdb5d9829b
                stepCounter: c5429209-b899-4e7f-9548-ca0e9a55f302
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 27c0049d-8f6d-43d4-b452-da1dbebc6194
          stepCounter: b6a8b2d0-6712-44c0-b5cd-288facb15865
        config: {}
        dataType: DECIMAL(10)
        defaultValue: ""
        description: ""
        name: SORCE_REFNO
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 4a398f10-0e5d-4eca-b3cf-6cc0b87b7515
                stepCounter: c5429209-b899-4e7f-9548-ca0e9a55f302
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a5490042-0263-480d-86a8-1116f2b24399
          stepCounter: b6a8b2d0-6712-44c0-b5cd-288facb15865
        config: {}
        dataType: DECIMAL(10)
        defaultValue: ""
        description: ""
        name: PARNT_REFNO
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: aee5258a-9841-4f8c-aa35-04c0a6a73fda
                stepCounter: c5429209-b899-4e7f-9548-ca0e9a55f302
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: dc0ba096-d1b1-43fd-9aa4-da7bad2efe41
          stepCounter: b6a8b2d0-6712-44c0-b5cd-288facb15865
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: COLLECT_DTTM
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: d4950973-ccf6-417e-be02-79e187e42cd5
                stepCounter: c5429209-b899-4e7f-9548-ca0e9a55f302
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a1753a40-ada5-46e8-a00f-1fc794be3674
          stepCounter: b6a8b2d0-6712-44c0-b5cd-288facb15865
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: ""
        name: VALUE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 02be01e0-1d7d-4fbe-a975-2e1be5817393
          stepCounter: b6a8b2d0-6712-44c0-b5cd-288facb15865
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: DATEVALUE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 57829cac-1198-49f1-9489-96050b996288
          stepCounter: b6a8b2d0-6712-44c0-b5cd-288facb15865
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: ""
        name: MEMOVALUE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 403d8ebf-2fe7-4ad8-a825-d8dc48eb469f
          stepCounter: b6a8b2d0-6712-44c0-b5cd-288facb15865
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        name: COLUMNNAME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ff441a92-0a0a-46e4-94f6-56cb31f445ee
          stepCounter: b6a8b2d0-6712-44c0-b5cd-288facb15865
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: Date and time the row was updated in the data warehouse.
        isSystemUpdateDate: true
        name: DSS_UPDATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          DS_PIMS_LDD_LOCAL_DATAVALUES: c5429209-b899-4e7f-9548-ca0e9a55f302
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: TGT
            nodeName: DS_PIMS_LDD_LOCAL_DATAVALUES
        join:
          joinCondition: FROM {{ ref('TGT','DS_PIMS_LDD_LOCAL_DATAVALUES') }}
        name: S_PIMS_LDD_LOCAL_DATAVALUES_10
        noLinkRefs: []
  name: S_PIMS_LDD_LOCAL_DATAVALUES_10
  overrideSQL: false
  schema: ""
  sqlType: Stage
  type: sql
  version: 1
type: Node
