fileVersion: 1
id: ecdf78d6-77ef-4fe0-81e3-39b0c60e9c77
name: S_PATIENTRACK_MULTIPLE_LIST_VALUES
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
  database: ""
  deployEnabled: true
  description: "Do not create an Update Procedure for this table.  The custom procedure builds the table complete."
  isMultisource: false
  locationName: TGT
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e7cc9771-9b43-4de5-b576-db16be5b26d1
          stepCounter: ecdf78d6-77ef-4fe0-81e3-39b0c60e9c77
        config: {}
        dataType: BIGINT
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: ITEM_DEFINITION_ID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: ae0b3ec5-3b7c-4e17-9ecc-5e1a7aa57841
                stepCounter: b40d5001-ac74-45b6-80f8-677b2241f609
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 2f59dcce-4187-4e5f-8d09-c82a424b5d30
          stepCounter: ecdf78d6-77ef-4fe0-81e3-39b0c60e9c77
        config: {}
        dataType: BIGINT
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: FORM_INSTANCE_ID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 56aad173-a59c-4304-a8cd-ef4e5c7a1bba
                stepCounter: b40d5001-ac74-45b6-80f8-677b2241f609
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b57ac064-15e0-4bcb-ac51-093adf505f0e
          stepCounter: ecdf78d6-77ef-4fe0-81e3-39b0c60e9c77
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: ""
        name: MODIF_BY
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 89cdc90e-3f08-4a6f-86df-7631fb0429b7
                stepCounter: 957b70a8-4683-49bc-a6ef-b09fb2bed67d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 4114c0f8-74c8-49cf-ae4d-cad0b9405570
          stepCounter: ecdf78d6-77ef-4fe0-81e3-39b0c60e9c77
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: MODIF_DTTM
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: a6d412bb-6ba4-44ad-8cd2-40365d825872
                stepCounter: 957b70a8-4683-49bc-a6ef-b09fb2bed67d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7880bc52-e4b5-4183-b9de-8325aa5fbd0b
          stepCounter: ecdf78d6-77ef-4fe0-81e3-39b0c60e9c77
        config: {}
        dataType: VARCHAR(512)
        defaultValue: ""
        description: ""
        name: DISPLAY_VALUE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 4b0e1c90-02d7-4f86-ae28-6d9562bafd5d
                stepCounter: b40d5001-ac74-45b6-80f8-677b2241f609
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: eb02e235-9d2d-4e1d-99e0-d0f17efdb110
          stepCounter: ecdf78d6-77ef-4fe0-81e3-39b0c60e9c77
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: Date and time the row was updated in the data warehouse.
        isSystemUpdateDate: true
        name: DSS_UPDATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases: {}
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: TGT
            nodeName: S_PATIENTRACK_MULTIPLE_LIST_VALUES_10
        join:
          joinCondition: FROM
        name: S_PATIENTRACK_MULTIPLE_LIST_VALUES
        noLinkRefs: []
  name: S_PATIENTRACK_MULTIPLE_LIST_VALUES
  overrideSQL: false
  schema: ""
  sqlType: Stage
  type: sql
  version: 1
type: Node
