fileVersion: 1
id: fa2ac20a-a4ea-4529-8d90-52804fd01ebd
name: L_PATIENTRACK_EWS_REGIME_APPLICATION
operation:
  database: ""
  deployEnabled: true
  description: ""
  locationName: TGT
  metadata:
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 511b9104-84a4-419c-bdb7-f3de946de924
          stepCounter: fa2ac20a-a4ea-4529-8d90-52804fd01ebd
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: EWSAP_PK
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 58990ced-b417-4dd0-9cec-03456a2010ac
          stepCounter: fa2ac20a-a4ea-4529-8d90-52804fd01ebd
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: ADMSN_PK
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 88a59740-6e37-4eaa-bdd9-58001b6bb695
          stepCounter: fa2ac20a-a4ea-4529-8d90-52804fd01ebd
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: EWSRG_PK
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ae2e290a-b5ed-42c4-a4e3-189e81ddd74b
          stepCounter: fa2ac20a-a4ea-4529-8d90-52804fd01ebd
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: DTMPR_PK
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 569bae30-acc8-4880-a4ac-0b2a21237eab
          stepCounter: fa2ac20a-a4ea-4529-8d90-52804fd01ebd
        config: {}
        dataType: VARCHAR(5)
        defaultValue: ""
        description: ""
        name: DRIVING_TABLE_CODE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: baebbd24-13f7-48d9-a15e-6b9d795ef436
          stepCounter: fa2ac20a-a4ea-4529-8d90-52804fd01ebd
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: DRIVING_TABLE_PK
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 9085e2f4-b568-4160-a3df-949b4c1e86a9
          stepCounter: fa2ac20a-a4ea-4529-8d90-52804fd01ebd
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: ALTPR_RFVAL
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f3259e39-0775-4ed6-8db8-2789fbd344fc
          stepCounter: fa2ac20a-a4ea-4529-8d90-52804fd01ebd
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: START_DTTM
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6062bb11-faa8-4cb5-845d-c23323cc52e0
          stepCounter: fa2ac20a-a4ea-4529-8d90-52804fd01ebd
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: END_DTTM
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3f9f3a89-0dba-4964-ba78-ba8c7ea0a489
          stepCounter: fa2ac20a-a4ea-4529-8d90-52804fd01ebd
        config: {}
        dataType: BIT
        defaultValue: ""
        description: ""
        name: DELETED_FLAG
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6317329c-3999-493d-b676-ebf6ce037194
          stepCounter: fa2ac20a-a4ea-4529-8d90-52804fd01ebd
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: CREATED_BY_USERR_PK
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ef484b79-10c0-4fc3-b5d2-c3b9272d7231
          stepCounter: fa2ac20a-a4ea-4529-8d90-52804fd01ebd
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: CREATED_DTTM
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6f59ddb1-a369-4269-83c1-5d6b308b8ea5
          stepCounter: fa2ac20a-a4ea-4529-8d90-52804fd01ebd
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_BY_USERR_PK
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 9cc5e583-c74d-4aa1-a4e4-581898ae2f5d
          stepCounter: fa2ac20a-a4ea-4529-8d90-52804fd01ebd
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_DTTM
        nullable: true
  name: L_PATIENTRACK_EWS_REGIME_APPLICATION
  schema: ""
  sqlType: Source
  type: sourceInput
  version: 1
type: Node
