fileVersion: 1
id: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
name: L_PATIENTRACK_OBSERVATION_PROFILE_APPLICATION
operation:
  database: ""
  deployEnabled: true
  description: ""
  locationName: TGT
  metadata:
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 293d9be3-ae94-446f-98da-7513079ad485
          stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: OBPAP_PK
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7a60eb9f-8753-4ff1-ba21-7a959705841d
          stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: ADMSN_PK
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 2b614ce0-984e-4780-838e-1d26b03605af
          stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: OBPRF_PK
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c05ec2d8-d964-4532-b3e3-4d8df14af1b0
          stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: DTMPR_PK
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1104995d-1caf-4601-bc65-7a8361e5f0f5
          stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
        config: {}
        dataType: VARCHAR(5)
        defaultValue: ""
        description: ""
        name: DRIVING_TABLE_CODE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7dd472c9-c8ec-465c-898f-ea766b2da26f
          stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: DRIVING_TABLE_PK
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c0d31701-4ff0-4933-b9ea-ec77da9de820
          stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: OARSN_RFVAL
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 9ef62a08-5b22-4496-a98f-f600b1447935
          stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: STEP_NUMBER
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 90c3ed03-6185-466a-bc31-aafd5bd3e15e
          stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: ITERATION_NUMBER
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a8c56b52-4294-4d65-bb2a-090adedfafb4
          stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: START_DTTM
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e98ea262-b824-4dc3-b23d-2f9d871a3350
          stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: END_DTTM
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5cc607da-5750-4b6b-b8f5-99ea4ebe7169
          stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
        config: {}
        dataType: BIT
        defaultValue: ""
        description: ""
        name: DELETED_FLAG
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c37d9518-9497-48b1-bb2d-7f860e118e39
          stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: CREATED_BY_USERR_PK
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ced5e132-6f6b-4e43-b8ca-81b87b18c60e
          stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: CREATED_DTTM
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 27664bb5-4e79-429b-8e67-eebaa99da10c
          stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_BY_USERR_PK
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: bc01aa69-fc02-462d-9ab1-a6ab7144cf8c
          stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_DTTM
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 4e608117-eb94-47f8-b551-d2b1e7b5c27e
          stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
        config: {}
        dataType: BIT
        defaultValue: ""
        description: ""
        name: ACTIVE_FLAG
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b8fabdd1-9897-436e-aa3f-24481d81f684
          stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6e65034f-6a55-4912-ad25-6856d2c705fc
          stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
  name: L_PATIENTRACK_OBSERVATION_PROFILE_APPLICATION
  schema: ""
  sqlType: Source
  type: sourceInput
  version: 1
type: Node
