fileVersion: 1
id: 2a834be8-167c-469e-8eef-f11e8a3be238
name: FACT_PIMS_LDD_LOCAL_DATAVALUES
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TGT
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7873ca10-9d4f-4da4-9a88-2f329f76a78d
          stepCounter: 2a834be8-167c-469e-8eef-f11e8a3be238
        config: {}
        dataType: DECIMAL(10)
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: LCLDA_REFERENCE_NO
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: d8599b99-94ca-43b2-aaec-f8ac41e5fe06
                stepCounter: ab327c0c-c1f6-447f-9a93-8536f7688389
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3d676455-f766-4be2-8107-e752a236ee5d
          stepCounter: 2a834be8-167c-469e-8eef-f11e8a3be238
        config: {}
        dataType: INTEGER
        defaultValue: ""
        description: ""
        name: CONTACT_SEQUENCE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: e70b457c-76ac-4814-9b77-18a4d68a679d
                stepCounter: ab327c0c-c1f6-447f-9a93-8536f7688389
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ba403e05-5420-42f3-aac4-36479b5d5132
          stepCounter: 2a834be8-167c-469e-8eef-f11e8a3be238
        config: {}
        dataType: INTEGER
        defaultValue: ""
        description: s_pims_ldd_local_datavalues.usscr_refno=dim_lddi_Screen.USSCR_REFNO
        name: DIM_LDDI_SCREEN_KEY
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 8b63aede-3f9f-48f9-9005-02adcc92000a
                stepCounter: 184ea643-dd12-499a-a4bf-7f76f67ea642
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 22966d46-b9c3-4e04-8438-eb53260ae78f
          stepCounter: 2a834be8-167c-469e-8eef-f11e8a3be238
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: 'The NHI is a unique 7-character identification number assigned to a healthcare user by the National Health Index (NHI) database.   There is a verification algorithm which ensures that the NHI number is in the correct format and is valid.     Also known as National Health Index, HCU identifier, NHI, HCU, HCU Number, Healthcare User identifier,   HCU identification number, NMPI number, Hospital Number, Patient Number.     '
        name: PATIENT_NHI
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 29840419-6f50-4804-aca0-14894369d6f0
                stepCounter: ab327c0c-c1f6-447f-9a93-8536f7688389
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 38f50ab3-dd2e-4eb4-acc2-d8ce65461309
          stepCounter: 2a834be8-167c-469e-8eef-f11e8a3be238
        config: {}
        dataType: INTEGER
        defaultValue: ""
        description: s_pims_ldd_local_datavalues.patnt_refno=dim_patient.patient_reference_no
        name: DIM_PATIENT_KEY
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 9962a01b-5f3d-4c1a-b371-997edef38d0f
                stepCounter: d52dd438-7899-4242-9e38-539d2a1447df
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 642a0fb6-513d-43ef-a1cf-2a2e85ffbd89
          stepCounter: 2a834be8-167c-469e-8eef-f11e8a3be238
        config: {}
        dataType: VARCHAR(25)
        defaultValue: ""
        description: ""
        name: EVENT_TYPE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 25402e14-4d31-4324-889c-26238aaee7cd
                stepCounter: ab327c0c-c1f6-447f-9a93-8536f7688389
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 2f92a345-e0e7-45f3-9a20-c1d4db285cfb
          stepCounter: 2a834be8-167c-469e-8eef-f11e8a3be238
        config: {}
        dataType: VARCHAR(12)
        defaultValue: ""
        description: ""
        name: EVENT_ENCOUNTER_ID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 40ab4259-0f03-4128-8235-13513dc21aa5
                stepCounter: ab327c0c-c1f6-447f-9a93-8536f7688389
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6cd47219-cd50-4af3-a347-5781a240214d
          stepCounter: 2a834be8-167c-469e-8eef-f11e8a3be238
        config: {}
        dataType: DECIMAL(10)
        defaultValue: ""
        description: ""
        name: PARENT_REFERENCE_NO
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 7dd08385-3d04-42a1-ab5e-68ca43b150fc
                stepCounter: ab327c0c-c1f6-447f-9a93-8536f7688389
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: aaaafc0e-dc20-4996-9e32-69adfb940e78
          stepCounter: 2a834be8-167c-469e-8eef-f11e8a3be238
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: COLLECT_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 1080053e-4418-427e-aca9-427c415f7494
                stepCounter: ab327c0c-c1f6-447f-9a93-8536f7688389
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 397fbc68-b4a1-4c92-9925-b9805e8ab463
          stepCounter: 2a834be8-167c-469e-8eef-f11e8a3be238
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: ""
        name: VALUE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 72162539-b13a-47b4-9586-68052d719f49
                stepCounter: ab327c0c-c1f6-447f-9a93-8536f7688389
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 594e4018-1632-4b8b-b48d-f49c16593092
          stepCounter: 2a834be8-167c-469e-8eef-f11e8a3be238
        config: {}
        dataType: INTEGER
        defaultValue: ""
        description: s_pims_ldd_local_datavalues.Value=dim_lddi_reference_values.rfval_refno_varchar
        name: DIM_LDDI_REFERENCE_VALUES_KEY
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: b846124e-2857-4e63-86e3-24371284dc9d
                stepCounter: 84f3bf19-950c-45a1-a818-91169f7f2489
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 88fff1db-57b0-4ea8-8593-59f85eb6091c
          stepCounter: 2a834be8-167c-469e-8eef-f11e8a3be238
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: DATE_VALUE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: ff134a37-3c88-4260-80f5-d17e20179449
                stepCounter: ab327c0c-c1f6-447f-9a93-8536f7688389
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c9894052-7721-4e5c-a357-1bdb4f684127
          stepCounter: 2a834be8-167c-469e-8eef-f11e8a3be238
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: ""
        name: MEMO_VALUE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: a9fb4a23-0d1e-4439-a8b2-f39e87b15d78
                stepCounter: ab327c0c-c1f6-447f-9a93-8536f7688389
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6b2a624d-47e7-45e5-9197-7d9e148dcec0
          stepCounter: 2a834be8-167c-469e-8eef-f11e8a3be238
        config: {}
        dataType: INTEGER
        defaultValue: ""
        description: s_pims_ldd_local_datavalues.usscr_refno=dim_lddi_ScreenItems.USSCR_REFNO  s_pims_ldd_local_datavalues.ColumnName=dim_lddi_ScreenItems.MAPPED_COLUMN
        isBusinessKey: true
        name: DIM_LDDI_SCREENITEMS_KEY
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: d73ce6cb-8c05-48db-b6ca-07919e1d9160
                stepCounter: 3726f43a-c1cf-46a0-adf4-ed54f9e33933
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ce837d72-fb0b-4192-9ab4-0911171f1604
          stepCounter: 2a834be8-167c-469e-8eef-f11e8a3be238
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: CREATE_DTTM
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 2809df3b-6685-478b-960f-f0e79660a4c8
                stepCounter: ab327c0c-c1f6-447f-9a93-8536f7688389
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: dc3a8615-da7c-4dae-b856-0d942b791e3f
          stepCounter: 2a834be8-167c-469e-8eef-f11e8a3be238
        config: {}
        dataType: INTEGER
        defaultValue: ""
        description: s_pims_ldd_local_datavalues.user_create=dim_create_user_login.create_user_login_code
        name: DIM_CREATE_USER_LOGIN_KEY
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 2dfe5e14-cc2f-4748-8352-a6d1621289af
                stepCounter: 70bd6ed5-e21b-440f-9079-7fe305bc4f30
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f2a870d3-35c3-4aef-84f5-ced96b663318
          stepCounter: 2a834be8-167c-469e-8eef-f11e8a3be238
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: MODIF_DTTM
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: d7230ed1-6135-4aaa-a6fd-70b302195557
                stepCounter: ab327c0c-c1f6-447f-9a93-8536f7688389
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a0b6a1fa-85c6-4af1-9178-f997230cd31a
          stepCounter: 2a834be8-167c-469e-8eef-f11e8a3be238
        config: {}
        dataType: INTEGER
        defaultValue: ""
        description: s_pims_ldd_local_datavalues.user_modif=dim_modify_user_login.modify_user_login_code
        name: DIM_MODIFY_USER_LOGIN_KEY
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: ceaa34a6-dd0b-40fb-bc61-9df93cc05e7b
                stepCounter: bef0768d-dddb-4d02-af8d-03160de42b62
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 98c69dd9-f8eb-4bd6-81a0-93d63d13c298
          stepCounter: 2a834be8-167c-469e-8eef-f11e8a3be238
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: Date and time the row was updated in the data warehouse.
        isSystemUpdateDate: true
        name: DSS_UPDATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          S_PIMS_LDD_LOCAL_DATAVALUES: ab327c0c-c1f6-447f-9a93-8536f7688389
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: TGT
            nodeName: S_PIMS_LDD_LOCAL_DATAVALUES
        join:
          joinCondition: FROM {{ ref('TGT','S_PIMS_LDD_LOCAL_DATAVALUES') }}
        name: FACT_PIMS_LDD_LOCAL_DATAVALUES
        noLinkRefs: []
  name: FACT_PIMS_LDD_LOCAL_DATAVALUES
  overrideSQL: false
  schema: ""
  sqlType: Fact
  type: sql
  version: 1
type: Node
