fileVersion: 1
id: 06fa4241-360c-43d0-8e4a-8b860f92fc09
name: DS_PIMS_REFERENCE_VALUES
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TGT
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 97aebd53-8994-45f0-9fea-1b3150a90054
          stepCounter: 06fa4241-360c-43d0-8e4a-8b860f92fc09
        config: {}
        dataType: DECIMAL(10)
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: RFVAL_REFNO
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: a585af7e-5ba1-4b26-8910-981becba5e84
                stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: fc52b689-cd00-4eb4-ae6e-f2b338d8975a
          stepCounter: 06fa4241-360c-43d0-8e4a-8b860f92fc09
        config: {}
        dataType: VARCHAR(5)
        defaultValue: ""
        description: ""
        name: RFVDM_CODE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: b7a5547b-0822-418c-8723-f86f3fdde6d4
                stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 551f483d-a948-4558-87f8-d3e65fffac3c
          stepCounter: 06fa4241-360c-43d0-8e4a-8b860f92fc09
        config: {}
        dataType: VARCHAR(80)
        defaultValue: ""
        description: ""
        name: DESCRIPTION
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 382613a6-0a2f-4c51-8cc1-cc6c35de5f0c
                stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: fbb01e3b-4612-47c8-9a4a-5d6abddc60ef
          stepCounter: 06fa4241-360c-43d0-8e4a-8b860f92fc09
        config: {}
        dataType: VARCHAR(25)
        defaultValue: ""
        description: ""
        name: MAIN_CODE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: df7effe6-3058-4d31-8657-1bcae9c8c673
                stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c75c4dbc-8cae-49df-90f2-c316edab302d
          stepCounter: 06fa4241-360c-43d0-8e4a-8b860f92fc09
        config: {}
        dataType: DECIMAL(10)
        defaultValue: ""
        description: ""
        name: PARNT_REFNO
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 675ddf4e-10dd-461b-9164-13e5472bfec7
                stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 61199449-d210-48d9-a7ee-9feadb70de43
          stepCounter: 06fa4241-360c-43d0-8e4a-8b860f92fc09
        config: {}
        dataType: VARCHAR(5)
        defaultValue: ""
        description: ""
        name: SMODE_VALUE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 7153772f-9397-471c-8490-b917772c526f
                stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 88c4876a-0d07-4f59-bd0e-fda3ae00da3c
          stepCounter: 06fa4241-360c-43d0-8e4a-8b860f92fc09
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: ""
        name: DEFAULT_VALUE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: fad73f0c-b808-4725-8032-085cd35fe33e
                stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f88be18b-8d47-4cb9-b4a4-50c78872a5c0
          stepCounter: 06fa4241-360c-43d0-8e4a-8b860f92fc09
        config: {}
        dataType: DECIMAL(3)
        defaultValue: ""
        description: ""
        name: SORT_ORDER
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 65dc9507-7994-4128-b72c-4b8824130363
                stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e94944f9-69d4-4a87-8ee4-472bbeb05982
          stepCounter: 06fa4241-360c-43d0-8e4a-8b860f92fc09
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: ""
        name: SELECT_VALUE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 025181c5-201d-4708-bcb3-6744b32a8677
                stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 11150197-c4ce-4698-a68f-71e8fe07a74d
          stepCounter: 06fa4241-360c-43d0-8e4a-8b860f92fc09
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: ""
        name: DISPLAY_VALUE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: f5f41aba-f7c7-4e75-9298-6d7cab6af08d
                stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f55efe99-02ae-4ba2-ba47-6a1e36a4d2a7
          stepCounter: 06fa4241-360c-43d0-8e4a-8b860f92fc09
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: CREATE_DTTM
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 5ebe0772-844b-471a-9c36-dfacb70f12b2
                stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5ff88a70-5b93-4c5e-8efe-7f85e52504d5
          stepCounter: 06fa4241-360c-43d0-8e4a-8b860f92fc09
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: MODIF_DTTM
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 7eb748fa-fdec-43b9-b13d-cbe367194729
                stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5c93e9c7-91d8-4dc4-bf73-eab729967510
          stepCounter: 06fa4241-360c-43d0-8e4a-8b860f92fc09
        config: {}
        dataType: VARCHAR(30)
        defaultValue: ""
        description: ""
        name: USER_CREATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: ef14817f-b191-49b1-aa13-55b8f50b2e31
                stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: dd1616c2-8328-485d-8210-2e682d792d20
          stepCounter: 06fa4241-360c-43d0-8e4a-8b860f92fc09
        config: {}
        dataType: VARCHAR(30)
        defaultValue: ""
        description: ""
        name: USER_MODIF
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 209d7339-41fd-4371-9b73-a46b93f129eb
                stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 32cf4b62-0326-43ef-aa47-96886bd6d57a
          stepCounter: 06fa4241-360c-43d0-8e4a-8b860f92fc09
        config: {}
        dataType: VARCHAR(5)
        defaultValue: ""
        description: ""
        name: RFTYP_CODE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 88d9d21c-11a4-4790-8f29-6d7fb8023f6c
                stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: bb57381d-ecc3-4e61-ae24-1318ec42fb28
          stepCounter: 06fa4241-360c-43d0-8e4a-8b860f92fc09
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: ""
        name: ARCHV_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 47d6f06f-c54f-4b06-b104-6c98b857de07
                stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 683c4e36-ae75-45f9-833d-3aba434600f5
          stepCounter: 06fa4241-360c-43d0-8e4a-8b860f92fc09
        config: {}
        dataType: DECIMAL(10)
        defaultValue: ""
        description: ""
        name: STRAN_REFNO
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 437d7cf1-918b-4045-8fba-3566f0788bf1
                stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 14d1a027-a7fb-43c7-b027-cdc7293762a3
          stepCounter: 06fa4241-360c-43d0-8e4a-8b860f92fc09
        config: {}
        dataType: DECIMAL(10)
        defaultValue: ""
        description: ""
        name: PRIOR_POINTER
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 8012a840-954c-47bd-a084-64af7fb7109a
                stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: eb305cd0-cf10-44c6-a46c-dfe40caa3a02
          stepCounter: 06fa4241-360c-43d0-8e4a-8b860f92fc09
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: EXTERNAL_KEY
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: d8d8cd83-d83f-48a3-9bc4-63b0b4e04c72
                stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d93e8a96-b2c6-4ecb-bd0a-f2f089d15d02
          stepCounter: 06fa4241-360c-43d0-8e4a-8b860f92fc09
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: START_DTTM
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 8e6d57e1-7fc5-48ea-bc89-dbabe1f7bfc9
                stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b83a3aaf-eb08-4e0f-b5c8-1be21d38ef47
          stepCounter: 06fa4241-360c-43d0-8e4a-8b860f92fc09
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: END_DTTM
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 87b7bf4d-6b70-4900-8f59-df2168efece8
                stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 538f2238-608c-46d5-81dc-4c27bdc6ef73
          stepCounter: 06fa4241-360c-43d0-8e4a-8b860f92fc09
        config: {}
        dataType: VARCHAR(30)
        defaultValue: ""
        description: ""
        name: LOW_VALUE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 2a2a857f-9c4b-4a0a-a743-7344dd8ab829
                stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a9bdbf2e-75cc-4e10-9a01-83ab7dbe009b
          stepCounter: 06fa4241-360c-43d0-8e4a-8b860f92fc09
        config: {}
        dataType: VARCHAR(30)
        defaultValue: ""
        description: ""
        name: HIGH_VALUE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: a2d0b9de-a1b9-444d-be4a-d8551634033e
                stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: bb6560b8-80b2-4ef5-9425-b8873525df34
          stepCounter: 06fa4241-360c-43d0-8e4a-8b860f92fc09
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: PROCESS_MODULE_ID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: a8070f45-3596-4f9f-bdcc-652eb411c20c
                stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a484839c-ea3a-43e9-8295-1fa97e54cd63
          stepCounter: 06fa4241-360c-43d0-8e4a-8b860f92fc09
        config: {}
        dataType: DECIMAL(10)
        defaultValue: ""
        description: ""
        name: OWNER_HEORG_REFNO
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 8fe267d0-d8e7-4966-ad2a-cf033a9e4dca
                stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ecdba042-8389-44e8-94aa-f96d22f41999
          stepCounter: 06fa4241-360c-43d0-8e4a-8b860f92fc09
        config: {}
        dataType: DECIMAL(10)
        defaultValue: ""
        description: ""
        name: SCLVL_REFNO
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: ea7d54e4-323a-4079-b782-29bac7bbd890
                stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 89430020-40da-4d8d-8e94-2384da5dd167
          stepCounter: 06fa4241-360c-43d0-8e4a-8b860f92fc09
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: SYN_CODE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: ad5ed0c3-ed2c-4e05-92b7-49979d153ce7
                stepCounter: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6e887a2d-e99e-40d3-b500-3fc776d21c72
          stepCounter: 06fa4241-360c-43d0-8e4a-8b860f92fc09
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: Date and time the row was updated in the data warehouse.
        isSystemUpdateDate: true
        name: DSS_UPDATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          L_PIMS_REFERENCE_VALUES: cdb854c9-3a5c-4020-a5f4-71b58cb5e589
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: TGT
            nodeName: L_PIMS_REFERENCE_VALUES
        join:
          joinCondition: FROM {{ ref('TGT','L_PIMS_REFERENCE_VALUES') }} l_pims_reference_values
        name: DS_PIMS_REFERENCE_VALUES
        noLinkRefs: []
  name: DS_PIMS_REFERENCE_VALUES
  overrideSQL: false
  schema: ""
  sqlType: '38'
  type: sql
  version: 1
type: Node
