fileVersion: 1
id: 71e6b90e-13e6-4b69-863c-4872fce8d69b
name: DIM_EVITALS_REFERENCE_VALUES
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TGT
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ba95cebe-a8ec-42d2-8b94-cae92b901536
          stepCounter: 71e6b90e-13e6-4b69-863c-4872fce8d69b
        config: {}
        dataType: INTEGER IDENTITY(1,1)
        defaultValue: ""
        description: Generated artificial key
        isSurrogateKey: true
        name: DIM_EVITALS_REFERENCE_VALUES_KEY
        nullable: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 53ae605c-b9d0-44ff-9448-d63744edaf1b
          stepCounter: 71e6b90e-13e6-4b69-863c-4872fce8d69b
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: REFERENCE_VALUE_ID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: c98b4a7f-7a56-40e7-a1f8-238f7d2eb9e8
                stepCounter: f6f252ab-0278-492b-8f5a-bc508fa6a440
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 53107eba-da7b-461c-8042-a17ec11bf240
          stepCounter: 71e6b90e-13e6-4b69-863c-4872fce8d69b
        config: {}
        dataType: CHAR(5)
        defaultValue: ""
        description: ""
        name: REFERENCE_VALUE_DOMAIN_CODE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 22b84e99-73b7-49e8-b467-e51ad072c7b0
                stepCounter: f6f252ab-0278-492b-8f5a-bc508fa6a440
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7f3e318f-b759-4c9b-9bcc-499999f114e1
          stepCounter: 71e6b90e-13e6-4b69-863c-4872fce8d69b
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: MAIN_IDENTIFIER
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 731f06d9-48f9-440a-b739-65c7ba0bb438
                stepCounter: f6f252ab-0278-492b-8f5a-bc508fa6a440
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b5ef1a57-4cec-41cd-abf6-5994332826f6
          stepCounter: 71e6b90e-13e6-4b69-863c-4872fce8d69b
        config: {}
        dataType: BIT
        defaultValue: ""
        description: ""
        name: SYSTEM_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 48d69cca-b0c4-4dd7-aee7-cf782efcef1b
                stepCounter: f6f252ab-0278-492b-8f5a-bc508fa6a440
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: efc3ba72-57be-4d7d-bdde-c28dace2d2c3
          stepCounter: 71e6b90e-13e6-4b69-863c-4872fce8d69b
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: ""
        name: REFERENCE_VALUE_DESCRIPTION
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: a1e6af49-d8c4-43cb-abf0-32e02215f095
                stepCounter: f6f252ab-0278-492b-8f5a-bc508fa6a440
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: eab4a459-e67d-4762-abf8-1d80583763bf
          stepCounter: 71e6b90e-13e6-4b69-863c-4872fce8d69b
        config: {}
        dataType: BIT
        defaultValue: ""
        description: ""
        name: HIDDEN_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 37846e09-896f-45e8-852a-e095ba490f85
                stepCounter: f6f252ab-0278-492b-8f5a-bc508fa6a440
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5fb71d76-2a64-4625-9d84-06dfac67290c
          stepCounter: 71e6b90e-13e6-4b69-863c-4872fce8d69b
        config: {}
        dataType: BIT
        defaultValue: ""
        description: ""
        name: DEFAULT_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: e29e7132-8e6f-4b09-94b1-e31aafe15176
                stepCounter: f6f252ab-0278-492b-8f5a-bc508fa6a440
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 9ff49d67-57a1-4ea1-8b45-b39d2d759e22
          stepCounter: 71e6b90e-13e6-4b69-863c-4872fce8d69b
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: SORT_ORDER
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: a4607684-43e3-4c64-909b-68f9727d1b24
                stepCounter: f6f252ab-0278-492b-8f5a-bc508fa6a440
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: beb5092a-d5fa-422d-a0c7-6fceb6af0fb0
          stepCounter: 71e6b90e-13e6-4b69-863c-4872fce8d69b
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: START_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 2e8a7314-89b2-45f2-bce2-536f7a00da6b
                stepCounter: f6f252ab-0278-492b-8f5a-bc508fa6a440
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: fe064623-2482-4647-81d3-b98c70f7448e
          stepCounter: 71e6b90e-13e6-4b69-863c-4872fce8d69b
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: END_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 411f4128-3a44-4fe2-adaf-9216cc209766
                stepCounter: f6f252ab-0278-492b-8f5a-bc508fa6a440
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 4297a232-d4fc-45ee-82f0-5ef0bcdd3330
          stepCounter: 71e6b90e-13e6-4b69-863c-4872fce8d69b
        config: {}
        dataType: BIT
        defaultValue: ""
        description: ""
        name: DELETED_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: c563a9d4-4d50-4135-81ae-7e23da483d84
                stepCounter: f6f252ab-0278-492b-8f5a-bc508fa6a440
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d69328d6-913e-43d2-9719-56edae45677f
          stepCounter: 71e6b90e-13e6-4b69-863c-4872fce8d69b
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: CREATED_BY_USER_ID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 9168441e-8716-4b7c-8461-1180bed9b211
                stepCounter: f6f252ab-0278-492b-8f5a-bc508fa6a440
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1d52edda-786b-48af-b1f5-bfc11bd76f35
          stepCounter: 71e6b90e-13e6-4b69-863c-4872fce8d69b
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: CREATED_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 016753ee-e843-4356-acdd-b278035b7be3
                stepCounter: f6f252ab-0278-492b-8f5a-bc508fa6a440
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ccd0ac59-2879-4e41-86d1-73a478dcd814
          stepCounter: 71e6b90e-13e6-4b69-863c-4872fce8d69b
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_BY_USER_ID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 8ededf75-bf04-42f9-9ef2-c14c4a3e167e
                stepCounter: f6f252ab-0278-492b-8f5a-bc508fa6a440
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 91f9a38f-3ff1-4134-a898-c429fcd83498
          stepCounter: 71e6b90e-13e6-4b69-863c-4872fce8d69b
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 1645c849-d3fe-4dfb-9b3f-88bb01235093
                stepCounter: f6f252ab-0278-492b-8f5a-bc508fa6a440
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ae035adb-a570-4f5f-bcf5-18340c2c0d7e
          stepCounter: 71e6b90e-13e6-4b69-863c-4872fce8d69b
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: Date and time the row was updated in the data warehouse.
        isSystemUpdateDate: true
        name: DSS_UPDATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          L_PATIENTRACK_REFERENCE_VALUE: f6f252ab-0278-492b-8f5a-bc508fa6a440
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: TGT
            nodeName: L_PATIENTRACK_REFERENCE_VALUE
        join:
          joinCondition: FROM {{ ref('TGT','L_PATIENTRACK_REFERENCE_VALUE') }} l_Patientrack_REFERENCE_VALUE
        name: DIM_EVITALS_REFERENCE_VALUES
        noLinkRefs: []
  name: DIM_EVITALS_REFERENCE_VALUES
  overrideSQL: false
  schema: ""
  sqlType: Dimension
  type: sql
  version: 1
type: Node
