fileVersion: 1
id: 84f3bf19-950c-45a1-a818-91169f7f2489
name: DIM_LDDI_REFERENCE_VALUES
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TGT
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b846124e-2857-4e63-86e3-24371284dc9d
          stepCounter: 84f3bf19-950c-45a1-a818-91169f7f2489
        config: {}
        dataType: INTEGER IDENTITY(1,1)
        defaultValue: ""
        description: Generated artificial key
        isSurrogateKey: true
        name: DIM_LDDI_REFERENCE_VALUES_KEY
        nullable: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 75ea6cac-3c7a-4b08-af7a-7b3183a58587
          stepCounter: 84f3bf19-950c-45a1-a818-91169f7f2489
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: RFVDM_CODE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: bfc62ce0-01d8-4184-b552-ea19986059b1
                stepCounter: 3f496b2f-dd37-4ac2-9f95-6838236a1a2c
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: fed0186c-ecc5-4df9-a58e-1af4daacb8bb
          stepCounter: 84f3bf19-950c-45a1-a818-91169f7f2489
        config: {}
        dataType: DECIMAL(10)
        defaultValue: ""
        description: ""
        name: RFVAL_REFERENCE_NO
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: cf5fcf4f-a891-4d8c-9541-e679cd965495
                stepCounter: 3f496b2f-dd37-4ac2-9f95-6838236a1a2c
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c2983bd8-79e5-4d7b-8012-9aae5df60fa6
          stepCounter: 84f3bf19-950c-45a1-a818-91169f7f2489
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: RFVAL_REFNO_VARCHAR
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 514952b9-1a7b-4d64-a9d8-d1da3a26bf3d
                stepCounter: 3f496b2f-dd37-4ac2-9f95-6838236a1a2c
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 891c92fa-8613-4924-9b67-103b7858b1a3
          stepCounter: 84f3bf19-950c-45a1-a818-91169f7f2489
        config: {}
        dataType: VARCHAR(25)
        defaultValue: ""
        description: ""
        name: MAIN_CODE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 3a02f84c-c701-45f5-ac6f-d4aebd8b5c99
                stepCounter: 3f496b2f-dd37-4ac2-9f95-6838236a1a2c
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 41da4ac2-164b-47de-aad9-22b95fb5238d
          stepCounter: 84f3bf19-950c-45a1-a818-91169f7f2489
        config: {}
        dataType: VARCHAR(80)
        defaultValue: ""
        description: ""
        name: DESCRIPTION
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 5a4d134d-5cd6-4a72-9887-76e07922df93
                stepCounter: 3f496b2f-dd37-4ac2-9f95-6838236a1a2c
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5e826e3f-8e11-4506-8b20-7a3dcc975e5c
          stepCounter: 84f3bf19-950c-45a1-a818-91169f7f2489
        config: {}
        dataType: VARCHAR(25)
        defaultValue: ""
        description: ""
        name: MHINC_IDENTIFIER
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: bf56ee24-7dc9-4eec-bedf-bb1187914a7e
                stepCounter: 3f496b2f-dd37-4ac2-9f95-6838236a1a2c
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 2d4c15b0-8991-47be-9805-54cda6eb7013
          stepCounter: 84f3bf19-950c-45a1-a818-91169f7f2489
        config: {}
        dataType: VARCHAR(25)
        defaultValue: ""
        description: ""
        name: REPRT_IDENTIFIER
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 4839acbc-42c2-46c5-8e4f-1433354f646e
                stepCounter: 3f496b2f-dd37-4ac2-9f95-6838236a1a2c
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 71a581b5-731f-4a59-bce6-79f2e59f055f
          stepCounter: 84f3bf19-950c-45a1-a818-91169f7f2489
        config: {}
        dataType: VARCHAR(25)
        defaultValue: ""
        description: ""
        name: LOCAL_IDENTIFIER
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 7f69fbff-59b7-461b-82b5-cddc62d55150
                stepCounter: 3f496b2f-dd37-4ac2-9f95-6838236a1a2c
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 4194090b-993c-45e5-974a-4cd48da1fa23
          stepCounter: 84f3bf19-950c-45a1-a818-91169f7f2489
        config: {}
        dataType: VARCHAR(25)
        defaultValue: ""
        description: ""
        name: MHA_IDENTIFIER
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: c1138730-c3da-4438-9b3f-a15d55046d8a
                stepCounter: 3f496b2f-dd37-4ac2-9f95-6838236a1a2c
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c5708b8f-2fc5-4af9-8a56-01a83adc2e8e
          stepCounter: 84f3bf19-950c-45a1-a818-91169f7f2489
        config: {}
        dataType: VARCHAR(25)
        defaultValue: ""
        description: ""
        name: MHS_IDENTIFIER
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: b823e6d0-408f-4d13-b701-5ddef997a099
                stepCounter: 3f496b2f-dd37-4ac2-9f95-6838236a1a2c
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: def5eb9a-7ca9-45f3-8387-c8c5ab4bca12
          stepCounter: 84f3bf19-950c-45a1-a818-91169f7f2489
        config: {}
        dataType: VARCHAR(25)
        defaultValue: ""
        description: ""
        name: NBRS_IDENTIFIER
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: ca753f0e-b884-4417-94b1-e88854ebe355
                stepCounter: 3f496b2f-dd37-4ac2-9f95-6838236a1a2c
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: eb19819b-9f6b-4a85-bcb4-bae643433daf
          stepCounter: 84f3bf19-950c-45a1-a818-91169f7f2489
        config: {}
        dataType: VARCHAR(25)
        defaultValue: ""
        description: ""
        name: NPF_IDENTIFIER
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 62ef27bc-f785-4b33-b28f-55de3a9a5d98
                stepCounter: 3f496b2f-dd37-4ac2-9f95-6838236a1a2c
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 350a34a9-39fc-4e4b-abc8-e5e106e0921b
          stepCounter: 84f3bf19-950c-45a1-a818-91169f7f2489
        config: {}
        dataType: VARCHAR(25)
        defaultValue: ""
        description: ""
        name: ORGID_IDENTIFIER
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: b4d047a7-ea50-430b-9bc2-6d36b652c1e4
                stepCounter: 3f496b2f-dd37-4ac2-9f95-6838236a1a2c
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 212d9bab-031e-4cb1-b393-d6b042c0bbf2
          stepCounter: 84f3bf19-950c-45a1-a818-91169f7f2489
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: Date and time the row was updated in the data warehouse.
        isSystemUpdateDate: true
        name: DSS_UPDATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          S_PIMS_LDDI_REFERENCE_VALUES: 3f496b2f-dd37-4ac2-9f95-6838236a1a2c
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: TGT
            nodeName: S_PIMS_LDDI_REFERENCE_VALUES
        join:
          joinCondition: FROM {{ ref('TGT','S_PIMS_LDDI_REFERENCE_VALUES') }} s_pims_lddi_reference_values
        name: DIM_LDDI_REFERENCE_VALUES
        noLinkRefs: []
  name: DIM_LDDI_REFERENCE_VALUES
  overrideSQL: false
  schema: ""
  sqlType: Dimension
  type: sql
  version: 1
type: Node
