fileVersion: 1
id: 8148efe4-d4ab-42d8-af5d-8704bf01b131
name: DS_PATIENTRACK_OBSERVATION_PROFILE_APPLICATION
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TGT
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d60bfa96-987f-47cc-8bfc-6b26bef2172b
          stepCounter: 8148efe4-d4ab-42d8-af5d-8704bf01b131
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: OBPAP_PK
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 293d9be3-ae94-446f-98da-7513079ad485
                stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: dbe1b17d-434f-4f55-a1c2-67bd18e2b674
          stepCounter: 8148efe4-d4ab-42d8-af5d-8704bf01b131
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: ADMSN_PK
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 7a60eb9f-8753-4ff1-ba21-7a959705841d
                stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3dbd6332-ee44-4b54-85e8-202d474bf2bb
          stepCounter: 8148efe4-d4ab-42d8-af5d-8704bf01b131
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: OBPRF_PK
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 2b614ce0-984e-4780-838e-1d26b03605af
                stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d8156c86-7320-4b49-a4b4-8d2bd9d99762
          stepCounter: 8148efe4-d4ab-42d8-af5d-8704bf01b131
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: DTMPR_PK
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: c05ec2d8-d964-4532-b3e3-4d8df14af1b0
                stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a60c8200-9403-408c-b4cd-22838c5303a4
          stepCounter: 8148efe4-d4ab-42d8-af5d-8704bf01b131
        config: {}
        dataType: VARCHAR(5)
        defaultValue: ""
        description: ""
        name: DRIVING_TABLE_CODE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 1104995d-1caf-4601-bc65-7a8361e5f0f5
                stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 93dd9746-3206-4e8b-a10a-4858c8129897
          stepCounter: 8148efe4-d4ab-42d8-af5d-8704bf01b131
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: DRIVING_TABLE_PK
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 7dd472c9-c8ec-465c-898f-ea766b2da26f
                stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 58ce1ab3-ed9a-4f2f-89cb-4655c82067c2
          stepCounter: 8148efe4-d4ab-42d8-af5d-8704bf01b131
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: OARSN_RFVAL
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: c0d31701-4ff0-4933-b9ea-ec77da9de820
                stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 9b96d3c3-0da1-4f4a-9397-cfe042f6b045
          stepCounter: 8148efe4-d4ab-42d8-af5d-8704bf01b131
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: STEP_NUMBER
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 9ef62a08-5b22-4496-a98f-f600b1447935
                stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 78c85ce9-e0ac-4bc3-bb7e-833369e1282e
          stepCounter: 8148efe4-d4ab-42d8-af5d-8704bf01b131
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: ITERATION_NUMBER
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 90c3ed03-6185-466a-bc31-aafd5bd3e15e
                stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: af8273d7-aa66-43dd-8807-327326827e27
          stepCounter: 8148efe4-d4ab-42d8-af5d-8704bf01b131
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: START_DTTM
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: a8c56b52-4294-4d65-bb2a-090adedfafb4
                stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 95752f83-9051-404a-a2a2-8dd644f86491
          stepCounter: 8148efe4-d4ab-42d8-af5d-8704bf01b131
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: END_DTTM
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: e98ea262-b824-4dc3-b23d-2f9d871a3350
                stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 213d01db-088e-4dff-ba2e-17f40d652c7f
          stepCounter: 8148efe4-d4ab-42d8-af5d-8704bf01b131
        config: {}
        dataType: BIT
        defaultValue: ""
        description: ""
        name: DELETED_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 5cc607da-5750-4b6b-b8f5-99ea4ebe7169
                stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 4b7d2dd5-f81e-48f1-acbe-9eede243a92f
          stepCounter: 8148efe4-d4ab-42d8-af5d-8704bf01b131
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: CREATED_BY_USERR_PK
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: c37d9518-9497-48b1-bb2d-7f860e118e39
                stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8887af7a-2727-4104-9e0f-f815961030dd
          stepCounter: 8148efe4-d4ab-42d8-af5d-8704bf01b131
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: CREATED_DTTM
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: ced5e132-6f6b-4e43-b8ca-81b87b18c60e
                stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d805a23d-b39a-421a-8be8-96315c65fa9f
          stepCounter: 8148efe4-d4ab-42d8-af5d-8704bf01b131
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_BY_USERR_PK
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 27664bb5-4e79-429b-8e67-eebaa99da10c
                stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ba85eb3e-aec9-4dbe-97fe-b8e6904a0cb8
          stepCounter: 8148efe4-d4ab-42d8-af5d-8704bf01b131
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_DTTM
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: bc01aa69-fc02-462d-9ab1-a6ab7144cf8c
                stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8aebaeef-0cd0-4962-a036-88db3bde6748
          stepCounter: 8148efe4-d4ab-42d8-af5d-8704bf01b131
        config: {}
        dataType: BIT
        defaultValue: ""
        description: ""
        name: ACTIVE_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 4e608117-eb94-47f8-b551-d2b1e7b5c27e
                stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 80ca268f-ffa7-4e1d-93b5-9a1ca745f541
          stepCounter: 8148efe4-d4ab-42d8-af5d-8704bf01b131
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: b8fabdd1-9897-436e-aa3f-24481d81f684
                stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 45fd86b4-3d4c-4324-a3a6-21971e6d17fe
          stepCounter: 8148efe4-d4ab-42d8-af5d-8704bf01b131
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 6e65034f-6a55-4912-ad25-6856d2c705fc
                stepCounter: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7e3b0be9-d51d-4bcd-acbd-7aa04a449e68
          stepCounter: 8148efe4-d4ab-42d8-af5d-8704bf01b131
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: Date and time the row was updated in the data warehouse.
        isSystemUpdateDate: true
        name: DSS_UPDATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          L_PATIENTRACK_OBSERVATION_PROFILE_APPLICATION: f5ef8b94-18e1-4e40-8b87-8f1e91c30774
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: TGT
            nodeName: L_PATIENTRACK_OBSERVATION_PROFILE_APPLICATION
        join:
          joinCondition: FROM {{ ref('TGT','L_PATIENTRACK_OBSERVATION_PROFILE_APPLICATION') }} l_Patientrack_OBSERVATION_PROFILE_APPLICATION
        name: DS_PATIENTRACK_OBSERVATION_PROFILE_APPLICATION
        noLinkRefs: []
  name: DS_PATIENTRACK_OBSERVATION_PROFILE_APPLICATION
  overrideSQL: false
  schema: ""
  sqlType: '38'
  type: sql
  version: 1
type: Node
