fileVersion: 1
id: 6e8c1b7f-4a00-4e50-88a5-b6b4321da72e
name: DS_PATIENTRACK_EWS_REGIME_APPLICATION
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: TGT
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c66574c4-db6e-487d-819c-1841ac5570df
          stepCounter: 6e8c1b7f-4a00-4e50-88a5-b6b4321da72e
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: EWSAP_PK
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 511b9104-84a4-419c-bdb7-f3de946de924
                stepCounter: fa2ac20a-a4ea-4529-8d90-52804fd01ebd
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 74f43d54-b340-47ea-993b-ef7212a01e5b
          stepCounter: 6e8c1b7f-4a00-4e50-88a5-b6b4321da72e
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: ADMSN_PK
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 58990ced-b417-4dd0-9cec-03456a2010ac
                stepCounter: fa2ac20a-a4ea-4529-8d90-52804fd01ebd
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b98e691d-3dc5-45bf-bdd2-5b8c0a4b6cc0
          stepCounter: 6e8c1b7f-4a00-4e50-88a5-b6b4321da72e
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: EWSRG_PK
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 88a59740-6e37-4eaa-bdd9-58001b6bb695
                stepCounter: fa2ac20a-a4ea-4529-8d90-52804fd01ebd
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: df99bf0c-0d0f-4564-ab6b-4405fa92a550
          stepCounter: 6e8c1b7f-4a00-4e50-88a5-b6b4321da72e
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: DTMPR_PK
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: ae2e290a-b5ed-42c4-a4e3-189e81ddd74b
                stepCounter: fa2ac20a-a4ea-4529-8d90-52804fd01ebd
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a4210f4d-6c33-4503-a9c1-197b9d809ab5
          stepCounter: 6e8c1b7f-4a00-4e50-88a5-b6b4321da72e
        config: {}
        dataType: VARCHAR(5)
        defaultValue: ""
        description: ""
        name: DRIVING_TABLE_CODE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 569bae30-acc8-4880-a4ac-0b2a21237eab
                stepCounter: fa2ac20a-a4ea-4529-8d90-52804fd01ebd
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a7e70624-1598-44a7-9546-cb0c92f9c9d6
          stepCounter: 6e8c1b7f-4a00-4e50-88a5-b6b4321da72e
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: DRIVING_TABLE_PK
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: baebbd24-13f7-48d9-a15e-6b9d795ef436
                stepCounter: fa2ac20a-a4ea-4529-8d90-52804fd01ebd
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7977e470-3076-4ead-a2a2-cf609947900d
          stepCounter: 6e8c1b7f-4a00-4e50-88a5-b6b4321da72e
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: ALTPR_RFVAL
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 9085e2f4-b568-4160-a3df-949b4c1e86a9
                stepCounter: fa2ac20a-a4ea-4529-8d90-52804fd01ebd
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 01eb051a-9c3f-4d77-8f68-60c427a281b4
          stepCounter: 6e8c1b7f-4a00-4e50-88a5-b6b4321da72e
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: START_DTTM
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: f3259e39-0775-4ed6-8db8-2789fbd344fc
                stepCounter: fa2ac20a-a4ea-4529-8d90-52804fd01ebd
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a283f1e7-c71a-42aa-9d59-2d25083dc66d
          stepCounter: 6e8c1b7f-4a00-4e50-88a5-b6b4321da72e
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: END_DTTM
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 6062bb11-faa8-4cb5-845d-c23323cc52e0
                stepCounter: fa2ac20a-a4ea-4529-8d90-52804fd01ebd
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 09a2b070-193a-4378-b345-e50eff07249a
          stepCounter: 6e8c1b7f-4a00-4e50-88a5-b6b4321da72e
        config: {}
        dataType: BIT
        defaultValue: ""
        description: ""
        name: DELETED_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 3f9f3a89-0dba-4964-ba78-ba8c7ea0a489
                stepCounter: fa2ac20a-a4ea-4529-8d90-52804fd01ebd
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f39ceafa-df68-48ae-a1a6-c67a5d971475
          stepCounter: 6e8c1b7f-4a00-4e50-88a5-b6b4321da72e
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: CREATED_BY_USERR_PK
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 6317329c-3999-493d-b676-ebf6ce037194
                stepCounter: fa2ac20a-a4ea-4529-8d90-52804fd01ebd
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 4dc477cd-a02f-47c4-b44f-6a46e7cedc5f
          stepCounter: 6e8c1b7f-4a00-4e50-88a5-b6b4321da72e
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: CREATED_DTTM
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: ef484b79-10c0-4fc3-b5d2-c3b9272d7231
                stepCounter: fa2ac20a-a4ea-4529-8d90-52804fd01ebd
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 96a7b4bd-581a-4878-9789-ffbf8a0b2507
          stepCounter: 6e8c1b7f-4a00-4e50-88a5-b6b4321da72e
        config: {}
        dataType: INT
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_BY_USERR_PK
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 6f59ddb1-a369-4269-83c1-5d6b308b8ea5
                stepCounter: fa2ac20a-a4ea-4529-8d90-52804fd01ebd
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8f5ffafe-4bef-40bc-88cc-337f0ae434f0
          stepCounter: 6e8c1b7f-4a00-4e50-88a5-b6b4321da72e
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_DTTM
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 9cc5e583-c74d-4aa1-a4e4-581898ae2f5d
                stepCounter: fa2ac20a-a4ea-4529-8d90-52804fd01ebd
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 15c6a7d4-a56f-4cd7-8a16-8c703753a5cf
          stepCounter: 6e8c1b7f-4a00-4e50-88a5-b6b4321da72e
        config: {}
        dataType: DATETIME
        defaultValue: ""
        description: Date and time the row was updated in the data warehouse.
        isSystemUpdateDate: true
        name: DSS_UPDATE_TIME
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          L_PATIENTRACK_EWS_REGIME_APPLICATION: fa2ac20a-a4ea-4529-8d90-52804fd01ebd
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: TGT
            nodeName: L_PATIENTRACK_EWS_REGIME_APPLICATION
        join:
          joinCondition: FROM {{ ref('TGT','L_PATIENTRACK_EWS_REGIME_APPLICATION') }} l_Patientrack_EWS_REGIME_APPLICATION
        name: DS_PATIENTRACK_EWS_REGIME_APPLICATION
        noLinkRefs: []
  name: DS_PATIENTRACK_EWS_REGIME_APPLICATION
  overrideSQL: false
  schema: ""
  sqlType: '38'
  type: sql
  version: 1
type: Node
